import { emptyProviderOptions } from '@/components/machines/machineOverrides'

import type { BasicConfig } from './useAgentBuilderForm'

export const fullConfig: BasicConfig = {
  instruction: 'You are a research assistant.\n\nCite sources.',
  providerConfig: 'anthropic',
  modelName: 'claude-sonnet-5',
  machineSources: [
    {
      id: 'source-1',
      kind: 'pool',
      name: 'default-pool',
      provider: '',
      managementKind: '',
      defaultCwd: '/workspace',
      initialNumMachines: '2',
      maxMachines: '5',
      deleteAfterIdleMinutes: '0',
      machineCpu: '4',
      machineMemoryGb: '8',
      providerOptions: emptyProviderOptions,
      envRows: [{ id: 'env-1', key: 'MODE', value: 'ci' }],
      secretEnvRows: [{ id: 'secret-1', key: 'TOKEN', secretId: 'sec_123' }],
    },
    {
      id: 'source-2',
      kind: 'machine',
      name: 'build-box',
      provider: '',
      managementKind: '',
      defaultCwd: '',
      initialNumMachines: '',
      maxMachines: '',
      deleteAfterIdleMinutes: '',
      machineCpu: '',
      machineMemoryGb: '',
      providerOptions: emptyProviderOptions,
      envRows: [],
      secretEnvRows: [],
    },
  ],
  tools: [
    { name: 'shell', permission: { mode: 'always_ask', parameters: {} } },
    { name: 'browser', permission: { mode: 'allowlist', parameters: { hosts: ['example.com'] } } },
  ],
  mcpServers: [
    {
      id: 'mcp-1',
      name: 'search',
      url: 'https://mcp.example.com',
      permission: { mode: 'always_allow', parameters: {} },
      defaultEnabled: true,
      authType: 'none',
      secretId: '',
      service: '',
      region: '',
      tools: [],
    },
    {
      id: 'mcp-2',
      name: 'aws-docs',
      url: 'https://mcp.aws.example.com',
      permission: { mode: 'always_ask', parameters: {} },
      defaultEnabled: false,
      authType: 'sigv4',
      secretId: 'sec_456',
      service: 'execute-api',
      region: 'us-east-1',
      tools: [],
    },
    {
      id: 'mcp-3',
      name: 'issues',
      url: 'https://mcp.issues.example.com',
      permission: { mode: 'always_ask', parameters: {} },
      defaultEnabled: true,
      authType: 'bearer',
      secretId: 'sec_789',
      service: '',
      region: '',
      tools: [],
    },
  ],
  skillIds: ['skl_1', 'skl_2'],
  subagents: [
    {
      id: 'sub-1',
      key: 'researcher',
      type: 'profile',
      profileName: 'research-agent',
      description: 'Investigate.',
      instructionAppend: 'Report as bullets.',
      maxInstances: '2',
      archiveAfterIdleMinutes: '30',
    },
    {
      id: 'sub-2',
      key: 'fork',
      type: 'self',
      profileName: '',
      description: '',
      instructionAppend: '',
      maxInstances: '',
      archiveAfterIdleMinutes: '',
    },
  ],
  maxSubagents: '4',
  maxDepth: '2',
}
