name: Omnara AI Assistant

on:
  # Trigger via repository_dispatch (from webhook server or API)
  repository_dispatch:
    types: [omnara-trigger]
  
  # Direct triggers from GitHub events
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write
  id-token: write  # Required for OIDC

jobs:
  # Job for repository_dispatch events (triggered from Omnara dashboard)
  omnara-dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Omnara Claude Code Action
        uses: omnara-ai/omnara/integrations/github/claude-code-action@github-action
        with:
          # Use agent mode for repository_dispatch
          mode: agent
          
          # Get prompt from client_payload
          direct_prompt: ${{ github.event.client_payload.prompt }}
          
          # Model configuration
          model: "claude-3-5-sonnet-latest"
          max_turns: 30
          timeout_minutes: 30
          
          # Authentication for Claude
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
        env:
          # Omnara configuration from repository_dispatch payload
          OMNARA_API_KEY: ${{ github.event.client_payload.omnara_api_key }}
          OMNARA_AGENT_INSTANCE_ID: ${{ github.event.client_payload.agent_instance_id }}
          OMNARA_AGENT_TYPE: ${{ github.event.client_payload.agent_type || 'Claude Code' }}
  
  # Job for issue/PR comment events (triggered by @omnara mentions)
  omnara-comment:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'repository_dispatch' &&
      contains(github.event.comment.body || github.event.issue.body || github.event.pull_request.body || '', '@omnara')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Omnara Claude Code Action
        uses: omnara-ai/omnara/integrations/github/claude-code-action@github-action
        with:
          # Use tag mode for comment triggers
          mode: tag
          trigger_phrase: "@omnara"
          
          # Model configuration
          model: "claude-3-5-sonnet-latest"
          max_turns: 30
          timeout_minutes: 30
          
          # Authentication for Claude
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
        env:
          # Omnara configuration from secrets
          OMNARA_API_KEY: ${{ secrets.OMNARA_API_KEY }}
          OMNARA_AGENT_INSTANCE_ID: ${{ format('omnara-{0}', github.run_id) }}
          OMNARA_AGENT_TYPE: 'Claude Code'