name: Omnara AI Assistant

on:
  # Trigger via repository_dispatch (from Omnara dashboard)
  repository_dispatch:
    types: [omnara-trigger]
  
  # Direct triggers from GitHub events (for @omnara mentions)
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write
  id-token: write  # Required for OIDC

jobs:
  omnara-assistant:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Omnara Claude Code Action
        uses: omnara-ai/omnara/integrations/github/claude-code-action-v1@github-action
        with:
          # The prompt will come from repository_dispatch payload
          # For @omnara mentions, the action auto-detects from comments
          prompt: ${{ github.event.client_payload.prompt }}
          
          # Claude configuration using new v1.0 claude_args format
          claude_args: |
            --max-turns 30
            --model claude-3-5-sonnet-latest
          
          # Override trigger phrase to use @omnara instead of @claude
          trigger_phrase: "@omnara"
          
          # Authentication for Claude
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
        env:
          # Omnara configuration from repository_dispatch payload
          # These are automatically used when present
          OMNARA_API_KEY: ${{ github.event.client_payload.omnara_api_key || secrets.OMNARA_API_KEY }}
          OMNARA_AGENT_INSTANCE_ID: ${{ github.event.client_payload.agent_instance_id || format('omnara-{0}', github.run_id) }}
          OMNARA_AGENT_TYPE: ${{ github.event.client_payload.agent_type || 'Claude Code' }}