import { sdk } from '@omnara/sdk'
import * as schemas from '@omnara/sdk/zod'

import { type CommandGroup, op } from './factory.ts'
import { formatRecord, formatTable, formatVoid } from './format.ts'
import { loadSkillArchive, zCreateSkillCliBody } from './skill-archive.ts'

export const commandGroups: CommandGroup[] = [
  {
    name: 'agents',
    aliases: ['agent'],
    summary: 'Launch and manage agents',
    operations: [
      op({
        verb: 'list',
        summary: 'List agents in a project',
        fn: sdk.listAgents,
        format: (response) =>
          formatTable(['id', 'name', 'state', 'model', 'created_at'])({
            data: response.data.map((agent) => ({ ...agent, model: agent.model?.name })),
            next_cursor: response.next_cursor,
          }),
        path: schemas.zListAgentsPath,
        query: schemas.zListAgentsQuery,
      }),
      op({
        verb: 'get',
        summary: 'Fetch an agent',
        fn: sdk.getAgent,
        format: formatRecord(),
        path: schemas.zGetAgentPath,
      }),
      op({
        verb: 'launch',
        summary: 'Launch a new agent',
        fn: sdk.createAgent,
        format: formatRecord(),
        path: schemas.zCreateAgentPath,
        body: schemas.zCreateAgentBody,
      }),
      op({
        verb: 'cancel',
        summary: 'Cancel a running agent',
        fn: sdk.cancelAgent,
        format: formatRecord(),
        path: schemas.zCancelAgentPath,
        body: schemas.zCancelAgentBody,
      }),
      op({
        verb: 'archive',
        summary: 'Archive an agent',
        fn: sdk.archiveAgent,
        format: formatRecord(),
        path: schemas.zArchiveAgentPath,
      }),
    ],
  },
  {
    name: 'orgs',
    aliases: ['org'],
    summary: 'Manage organizations',
    operations: [
      op({
        verb: 'create',
        summary: 'Create an organization',
        fn: sdk.createOrganization,
        format: formatRecord(),
        body: schemas.zCreateOrganizationBody,
      }),
      op({
        verb: 'overview',
        summary: 'Show an organization overview',
        fn: sdk.getOrgOverview,
        format: formatRecord(),
        path: schemas.zGetOrgOverviewPath,
      }),
      op({
        verb: 'delete',
        summary: 'Delete an organization',
        fn: sdk.deleteOrganization,
        format: formatVoid('deleted'),
        path: schemas.zDeleteOrganizationPath,
        positional: ['orgID'],
      }),
    ],
  },
  {
    name: 'projects',
    aliases: ['project'],
    summary: 'Manage projects',
    operations: [
      op({
        verb: 'list',
        summary: 'List projects visible to you',
        fn: sdk.listVisibleProjects,
        format: formatTable(['id', 'name', 'created_at', 'updated_at']),
        path: schemas.zListVisibleProjectsPath,
        query: schemas.zListVisibleProjectsQuery,
      }),
      op({
        verb: 'create',
        summary: 'Create a project',
        fn: sdk.createProject,
        format: formatRecord(),
        path: schemas.zCreateProjectPath,
        body: schemas.zCreateProjectBody,
      }),
      op({
        verb: 'delete',
        summary: 'Delete a project',
        fn: sdk.deleteProject,
        format: formatVoid('deleted'),
        path: schemas.zDeleteProjectPath,
        positional: ['projectID'],
      }),
    ],
  },
  {
    name: 'members',
    aliases: ['member'],
    summary: 'Manage organization members and invitations',
    operations: [
      op({
        verb: 'list',
        summary: 'List organization members',
        fn: sdk.listOrgMembers,
        format: formatTable(['user_id', 'email', 'display_name', 'role', 'created_at']),
        path: schemas.zListOrgMembersPath,
        query: schemas.zListOrgMembersQuery,
      }),
      op({
        verb: 'update',
        summary: "Update a member's role",
        fn: sdk.updateOrgMember,
        format: formatRecord(),
        path: schemas.zUpdateOrgMemberPath,
        body: schemas.zUpdateOrgMemberBody,
      }),
      op({
        verb: 'remove',
        summary: 'Remove a member from the organization',
        fn: sdk.removeOrgMember,
        format: formatVoid('removed'),
        path: schemas.zRemoveOrgMemberPath,
      }),
    ],
    groups: [
      {
        name: 'invites',
        aliases: ['invite'],
        summary: 'Manage organization invitations',
        operations: [
          op({
            verb: 'list',
            summary: "List an organization's invitations",
            fn: sdk.listOrgInvitations,
            format: formatTable(['id', 'email', 'org_role', 'created_at']),
            path: schemas.zListOrgInvitationsPath,
            query: schemas.zListOrgInvitationsQuery,
          }),
          op({
            verb: 'create',
            summary: 'Invite someone to the organization',
            fn: sdk.createOrgInvitation,
            format: formatRecord(),
            path: schemas.zCreateOrgInvitationPath,
            body: schemas.zCreateOrgInvitationBody,
          }),
          op({
            verb: 'delete',
            summary: 'Withdraw an invitation',
            fn: sdk.deleteOrgInvitation,
            format: formatVoid('deleted'),
            path: schemas.zDeleteOrgInvitationPath,
          }),
          op({
            verb: 'pending',
            summary: 'List invitations waiting on you',
            fn: sdk.listPendingInvitations,
            format: formatTable(['id', 'org_name', 'email', 'org_role', 'created_at']),
            query: schemas.zListPendingInvitationsQuery,
          }),
          op({
            verb: 'accept',
            summary: 'Accept an invitation',
            fn: sdk.acceptInvitation,
            format: formatRecord(),
            path: schemas.zAcceptInvitationPath,
          }),
          op({
            verb: 'decline',
            summary: 'Decline an invitation',
            fn: sdk.declineInvitation,
            format: formatRecord(),
            path: schemas.zDeclineInvitationPath,
          }),
        ],
      },
    ],
  },
  {
    name: 'keys',
    aliases: ['key'],
    summary: 'Manage organization API keys and personal access tokens',
    groups: [
      {
        name: 'org',
        summary: 'Inspect organization API keys',
        operations: [
          op({
            verb: 'list',
            summary: 'List organization API keys',
            fn: sdk.listOrgApiKeys,
            format: formatTable([
              'id',
              'name',
              'org_role',
              'created_at',
              'last_used_at',
              'revoked_at',
            ]),
            path: schemas.zListOrgApiKeysPath,
            query: schemas.zListOrgApiKeysQuery,
          }),
          op({
            verb: 'get',
            summary: 'Fetch an organization API key',
            fn: sdk.getOrgApiKey,
            format: formatRecord(),
            path: schemas.zGetOrgApiKeyPath,
          }),
        ],
      },
      {
        name: 'personal',
        summary: 'Manage your personal access tokens',
        operations: [
          op({
            verb: 'list',
            summary: "List the authenticated user's personal access tokens",
            fn: sdk.listPersonalAccessTokens,
            query: schemas.zListPersonalAccessTokensQuery,
            format: formatTable(['id', 'name', 'created_at', 'last_used_at', 'revoked_at']),
          }),
          op({
            verb: 'create',
            summary: 'Create a personal access token',
            fn: sdk.createPersonalAccessToken,
            format: formatRecord(),
            body: schemas.zCreatePersonalAccessTokenBody,
          }),
          op({
            verb: 'revoke',
            summary: 'Revoke a personal access token',
            fn: sdk.revokePersonalAccessToken,
            format: formatRecord(),
            path: schemas.zRevokePersonalAccessTokenPath,
          }),
        ],
      },
    ],
  },
  {
    name: 'machines',
    aliases: ['machine'],
    summary: 'Manage machines',
    operations: [
      op({
        verb: 'list',
        summary: 'List machines visible to you',
        fn: sdk.listVisibleMachines,
        format: formatTable([
          'id',
          'display_name',
          'source_kind',
          'provider',
          'lifecycle_state',
          'connection_state',
          'created_at',
        ]),
        path: schemas.zListVisibleMachinesPath,
        query: schemas.zListVisibleMachinesQuery,
      }),
      op({
        verb: 'get',
        summary: 'Fetch a machine',
        fn: sdk.getMachine,
        format: formatRecord(),
        path: schemas.zGetMachinePath,
      }),
      op({
        verb: 'create',
        summary: 'Create a machine',
        fn: sdk.createMachine,
        format: formatRecord(),
        path: schemas.zCreateMachinePath,
        body: schemas.zCreateMachineBody,
      }),
      op({
        verb: 'update',
        summary: 'Update a machine',
        fn: sdk.updateMachine,
        format: formatRecord(),
        path: schemas.zUpdateMachinePath,
        body: schemas.zUpdateMachineBody,
      }),
      op({
        verb: 'delete',
        summary: 'Delete a machine',
        fn: sdk.deleteMachine,
        format: formatVoid('deleted'),
        path: schemas.zDeleteMachinePath,
      }),
    ],
  },
  {
    name: 'pools',
    aliases: ['pool'],
    summary: 'Manage machine pools',
    operations: [
      op({
        verb: 'list',
        summary: 'List machine pools',
        fn: sdk.listMachinePools,
        format: formatTable(['id', 'name', 'provider', 'max_total_machines', 'created_at']),
        path: schemas.zListMachinePoolsPath,
        query: schemas.zListMachinePoolsQuery,
      }),
      op({
        verb: 'get',
        summary: 'Fetch a machine pool',
        fn: sdk.getMachinePool,
        format: formatRecord(),
        path: schemas.zGetMachinePoolPath,
      }),
      op({
        verb: 'create',
        summary: 'Create a machine pool',
        fn: sdk.createMachinePool,
        format: formatRecord(),
        path: schemas.zCreateMachinePoolPath,
        body: schemas.zCreateMachinePoolBody,
      }),
      op({
        verb: 'update',
        summary: 'Update a machine pool',
        fn: sdk.updateMachinePool,
        format: formatRecord(),
        path: schemas.zUpdateMachinePoolPath,
        body: schemas.zUpdateMachinePoolBody,
      }),
      op({
        verb: 'delete',
        summary: 'Delete a machine pool',
        fn: sdk.deleteMachinePool,
        format: formatVoid('deleted'),
        path: schemas.zDeleteMachinePoolPath,
      }),
    ],
  },
  {
    name: 'model-providers',
    aliases: ['model-provider'],
    summary: 'Manage model provider configs',
    operations: [
      op({
        verb: 'list',
        summary: 'List model provider configs',
        fn: sdk.listModelProviderConfigs,
        format: formatTable(['id', 'name', 'api_format', 'base_url', 'created_at']),
        path: schemas.zListModelProviderConfigsPath,
        query: schemas.zListModelProviderConfigsQuery,
      }),
      op({
        verb: 'get',
        summary: 'Fetch a model provider config',
        fn: sdk.getModelProviderConfig,
        format: formatRecord(),
        path: schemas.zGetModelProviderConfigPath,
      }),
      op({
        verb: 'create',
        summary: 'Create a model provider config',
        fn: sdk.createModelProviderConfig,
        format: formatRecord(),
        path: schemas.zCreateModelProviderConfigPath,
        body: schemas.zCreateModelProviderConfigBody,
      }),
      op({
        verb: 'update',
        summary: 'Update a model provider config',
        fn: sdk.updateModelProviderConfig,
        format: formatRecord(),
        path: schemas.zUpdateModelProviderConfigPath,
        body: schemas.zUpdateModelProviderConfigBody,
      }),
      op({
        verb: 'delete',
        summary: 'Delete a model provider config',
        fn: sdk.deleteModelProviderConfig,
        format: formatVoid('deleted'),
        path: schemas.zDeleteModelProviderConfigPath,
      }),
      op({
        verb: 'catalog',
        summary: "Show a provider's model catalog",
        fn: sdk.getModelCatalog,
        format: formatRecord(),
        path: schemas.zGetModelCatalogPath,
      }),
    ],
  },
  {
    name: 'models',
    aliases: ['model'],
    summary: 'Manage configured models on a provider config',
    operations: [
      op({
        verb: 'list',
        summary: 'List configured models',
        fn: sdk.listConfiguredModels,
        format: formatTable([
          'id',
          'name',
          'provider_model_slug',
          'context_window_tokens',
          'created_at',
        ]),
        path: schemas.zListConfiguredModelsPath,
        query: schemas.zListConfiguredModelsQuery,
      }),
      op({
        verb: 'create',
        summary: 'Configure a model',
        fn: sdk.createConfiguredModel,
        format: formatRecord(),
        path: schemas.zCreateConfiguredModelPath,
        body: schemas.zCreateConfiguredModelBody,
      }),
      op({
        verb: 'update',
        summary: 'Update a configured model',
        fn: sdk.updateConfiguredModel,
        format: formatRecord(),
        path: schemas.zUpdateConfiguredModelPath,
        body: schemas.zUpdateConfiguredModelBody,
      }),
      op({
        verb: 'delete',
        summary: 'Remove a configured model',
        fn: sdk.deleteConfiguredModel,
        format: formatVoid('deleted'),
        path: schemas.zDeleteConfiguredModelPath,
      }),
    ],
  },
  {
    name: 'secrets',
    aliases: ['secret'],
    summary: 'Manage organization secrets',
    operations: [
      op({
        verb: 'list',
        summary: 'List secrets visible through ownership authority',
        fn: sdk.listSecrets,
        format: formatTable([
          'id',
          'name',
          'kind',
          'current_version_number',
          'created_at',
          'updated_at',
        ]),
        path: schemas.zListSecretsPath,
        query: schemas.zListSecretsQuery,
      }),
      op({
        verb: 'get',
        summary: 'Fetch a secret',
        fn: sdk.getSecret,
        format: formatRecord(),
        path: schemas.zGetSecretPath,
      }),
      op({
        verb: 'create',
        summary: 'Create a secret',
        fn: sdk.createSecret,
        format: formatRecord(),
        path: schemas.zCreateSecretPath,
        body: schemas.zCreateSecretBody,
      }),
      op({
        verb: 'update',
        summary: "Update a secret's name or metadata",
        fn: sdk.updateSecret,
        format: formatRecord(),
        path: schemas.zUpdateSecretPath,
        body: schemas.zUpdateSecretBody,
      }),
      op({
        verb: 'delete',
        summary: 'Delete a secret',
        fn: sdk.deleteSecret,
        format: formatVoid('deleted'),
        path: schemas.zDeleteSecretPath,
      }),
    ],
  },
  {
    name: 'skills',
    aliases: ['skill'],
    summary: 'Manage skills',
    operations: [
      op({
        verb: 'list',
        summary: 'List skills',
        fn: sdk.listSkills,
        format: formatTable(['id', 'name', 'description', 'created_at', 'updated_at']),
        path: schemas.zListSkillsPath,
        query: schemas.zListSkillsQuery,
      }),
      op({
        verb: 'get',
        summary: 'Fetch a skill',
        fn: sdk.getSkill,
        format: formatRecord(),
        path: schemas.zGetSkillPath,
      }),
      op({
        verb: 'create',
        summary: 'Create a skill from a directory or a .zip/.tar.gz archive',
        fn: sdk.createSkill,
        format: formatRecord(),
        path: schemas.zCreateSkillPath,
        body: zCreateSkillCliBody,
        transformBody: (body) => ({
          ...body,
          archive: loadSkillArchive(body.archive),
        }),
      }),
      op({
        verb: 'delete',
        summary: 'Delete a skill',
        fn: sdk.deleteSkill,
        format: formatVoid('deleted'),
        path: schemas.zDeleteSkillPath,
      }),
    ],
  },
  {
    name: 'profiles',
    aliases: ['profile'],
    summary: 'Manage agent launch profiles',
    operations: [
      op({
        verb: 'list',
        summary: 'List agent profiles in a project',
        fn: sdk.listAgentProfiles,
        format: formatTable(['id', 'name', 'current_generation', 'created_at', 'updated_at']),
        path: schemas.zListAgentProfilesPath,
        query: schemas.zListAgentProfilesQuery,
      }),
      op({
        verb: 'get',
        summary: 'Fetch an agent profile',
        fn: sdk.getAgentProfile,
        format: formatRecord(),
        path: schemas.zGetAgentProfilePath,
      }),
      op({
        verb: 'create',
        summary: 'Create an agent profile',
        fn: sdk.createAgentProfile,
        format: formatRecord(),
        path: schemas.zCreateAgentProfilePath,
        body: schemas.zCreateAgentProfileBody,
      }),
      op({
        verb: 'rename',
        summary: 'Rename an agent profile',
        fn: sdk.renameAgentProfile,
        format: formatRecord(),
        path: schemas.zRenameAgentProfilePath,
        body: schemas.zRenameAgentProfileBody,
      }),
      op({
        verb: 'delete',
        summary: 'Delete an agent profile',
        fn: sdk.deleteAgentProfile,
        format: formatVoid('deleted'),
        path: schemas.zDeleteAgentProfilePath,
      }),
    ],
    groups: [
      {
        name: 'cron',
        summary: 'Manage cron triggers',
        operations: [
          op({
            verb: 'list',
            summary: 'List cron triggers in a project',
            fn: sdk.listCronTriggers,
            format: formatTable([
              'id',
              'name',
              'cron',
              'timezone',
              'enabled',
              'next_fire_at',
              'created_at',
            ]),
            path: schemas.zListCronTriggersPath,
            query: schemas.zListCronTriggersQuery,
          }),
          op({
            verb: 'get',
            summary: 'Fetch a cron trigger',
            fn: sdk.getCronTrigger,
            format: formatRecord(),
            path: schemas.zGetCronTriggerPath,
          }),
          op({
            verb: 'create',
            summary: 'Create a cron trigger',
            fn: sdk.createCronTrigger,
            format: formatRecord(),
            path: schemas.zCreateCronTriggerPath,
            body: schemas.zCreateCronTriggerBody,
          }),
          op({
            verb: 'update',
            summary: 'Update a cron trigger',
            fn: sdk.updateCronTrigger,
            format: formatRecord(),
            path: schemas.zUpdateCronTriggerPath,
            body: schemas.zUpdateCronTriggerBody,
          }),
          op({
            verb: 'delete',
            summary: 'Delete a cron trigger',
            fn: sdk.deleteCronTrigger,
            format: formatVoid('deleted'),
            path: schemas.zDeleteCronTriggerPath,
          }),
        ],
      },
    ],
  },
]
