// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands_processes.sql

package executiondb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/omnara-ai/omnara/internal/processcmd"
)

const readExecutionActionOwner = `-- name: ReadExecutionActionOwner :one
SELECT a.id,a.process_id,a.tool_call_id,a.action_kind,a.seq,a.payload,a.state,a.state_reason_code,a.state_reason_message,
 EXISTS(SELECT 1 FROM process_actions earlier WHERE earlier.agent_id=a.agent_id AND earlier.process_id=a.process_id
 AND earlier.seq<a.seq AND earlier.state IN ('queued','accepted')) AS earlier_pending
FROM process_actions a WHERE a.agent_id=$1 AND a.id=$2 FOR UPDATE
`

type ReadExecutionActionOwnerParams struct {
	AgentID uuid.UUID
	ID      uuid.UUID
}

type ReadExecutionActionOwnerRow struct {
	ID                 uuid.UUID
	ProcessID          uuid.UUID
	ToolCallID         uuid.UUID
	ActionKind         string
	Seq                int64
	Payload            json.RawMessage
	State              string
	StateReasonCode    *string
	StateReasonMessage string
	EarlierPending     bool
}

func (q *Queries) ReadExecutionActionOwner(ctx context.Context, db DBTX, arg ReadExecutionActionOwnerParams) (ReadExecutionActionOwnerRow, error) {
	row := db.QueryRow(ctx, readExecutionActionOwner, arg.AgentID, arg.ID)
	var i ReadExecutionActionOwnerRow
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.ToolCallID,
		&i.ActionKind,
		&i.Seq,
		&i.Payload,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.EarlierPending,
	)
	return i, err
}

const readExecutionProcessOwner = `-- name: ReadExecutionProcessOwner :one
SELECT p.id,p.org_id,p.machine_id,p.tool_call_id,p.state,p.state_reason_code,p.state_reason_message,p.exit_code,
 p.exit_signal,p.execution_spec,p.execution_granted_at,p.source_started_at,p.source_ended_at,p.default_output_cursor
FROM processes p WHERE p.agent_id=$1 AND p.id=$2 FOR UPDATE
`

type ReadExecutionProcessOwnerParams struct {
	AgentID uuid.UUID
	ID      uuid.UUID
}

type ReadExecutionProcessOwnerRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	MachineID           uuid.UUID
	ToolCallID          uuid.UUID
	State               string
	StateReasonCode     *string
	StateReasonMessage  string
	ExitCode            *int32
	ExitSignal          string
	ExecutionSpec       processcmd.ExecutionSpec
	ExecutionGrantedAt  *time.Time
	SourceStartedAt     *time.Time
	SourceEndedAt       *time.Time
	DefaultOutputCursor int64
}

func (q *Queries) ReadExecutionProcessOwner(ctx context.Context, db DBTX, arg ReadExecutionProcessOwnerParams) (ReadExecutionProcessOwnerRow, error) {
	row := db.QueryRow(ctx, readExecutionProcessOwner, arg.AgentID, arg.ID)
	var i ReadExecutionProcessOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.MachineID,
		&i.ToolCallID,
		&i.State,
		&i.StateReasonCode,
		&i.StateReasonMessage,
		&i.ExitCode,
		&i.ExitSignal,
		&i.ExecutionSpec,
		&i.ExecutionGrantedAt,
		&i.SourceStartedAt,
		&i.SourceEndedAt,
		&i.DefaultOutputCursor,
	)
	return i, err
}
