"""Add messages table

Revision ID: 40d4252deb5b
Revises: dc285eabea90
Create Date: 2025-07-31 11:25:30.567076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40d4252deb5b"
down_revision: Union[str, None] = "dc285eabea90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_instance_id", sa.UUID(), nullable=False),
        sa.Column(
            "sender_type", sa.Enum("AGENT", "USER", name="sendertype"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("requires_user_input", sa.Boolean(), nullable=False),
        sa.Column(
            "message_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["agent_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_messages_instance_created",
        "messages",
        ["agent_instance_id", "created_at"],
        unique=False,
    )

    # Add last_read_message_id to agent_instances
    op.add_column(
        "agent_instances",
        sa.Column("last_read_message_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    # Create the foreign key constraint after both tables exist to avoid circular dependency
    op.create_foreign_key(
        "fk_agent_instances_last_read_message",
        "agent_instances",
        "messages",
        ["last_read_message_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_agent_instances_last_read_message", "agent_instances", type_="foreignkey"
    )
    op.drop_column("agent_instances", "last_read_message_id")
    op.drop_index("idx_messages_instance_created", table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
