// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_machine_bindings.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countActiveAgentPoolMachines = `-- name: CountActiveAgentPoolMachines :one
SELECT count(*)::integer
FROM agent_machine_bindings binding
JOIN machines machine ON machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND binding.binding_kind = 'pool'
  AND binding.state = 'attached'
  AND machine.source_kind = 'pool'
  AND machine.machine_pool_id = $3::uuid
  AND machine.lifecycle_state <> 'deleted'
`

type CountActiveAgentPoolMachinesParams struct {
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	MachinePoolID uuid.UUID
}

// @sqlc-vet-disable machines-deleted-at
// lifecycle_state <> 'deleted' also excludes soft-deleted machines: DeleteMachine sets both together.
func (q *Queries) CountActiveAgentPoolMachines(ctx context.Context, arg CountActiveAgentPoolMachinesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveAgentPoolMachines, arg.ProjectID, arg.AgentID, arg.MachinePoolID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getAgentMachineBindingByCreateToolCall = `-- name: GetAgentMachineBindingByCreateToolCall :one
SELECT id, org_id, project_id, agent_id, create_tool_call_id, delete_tool_call_id, machine_id, machine_ref, binding_kind, state, description, cwd, env_overlay, secret_env_overlay, metadata, created_at, updated_at, delete_after_idle_minutes
FROM agent_machine_bindings
WHERE project_id = $1
  AND agent_id = $2
  AND create_tool_call_id = $3::uuid
`

type GetAgentMachineBindingByCreateToolCallParams struct {
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	CreateToolCallID uuid.UUID
}

func (q *Queries) GetAgentMachineBindingByCreateToolCall(ctx context.Context, arg GetAgentMachineBindingByCreateToolCallParams) (AgentMachineBinding, error) {
	row := q.db.QueryRow(ctx, getAgentMachineBindingByCreateToolCall, arg.ProjectID, arg.AgentID, arg.CreateToolCallID)
	var i AgentMachineBinding
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.CreateToolCallID,
		&i.DeleteToolCallID,
		&i.MachineID,
		&i.MachineRef,
		&i.BindingKind,
		&i.State,
		&i.Description,
		&i.Cwd,
		&i.EnvOverlay,
		&i.SecretEnvOverlay,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfterIdleMinutes,
	)
	return i, err
}

const getAgentMachineBindingByDeleteToolCall = `-- name: GetAgentMachineBindingByDeleteToolCall :one
SELECT id, org_id, project_id, agent_id, create_tool_call_id, delete_tool_call_id, machine_id, machine_ref, binding_kind, state, description, cwd, env_overlay, secret_env_overlay, metadata, created_at, updated_at, delete_after_idle_minutes
FROM agent_machine_bindings
WHERE project_id = $1
  AND agent_id = $2
  AND delete_tool_call_id = $3::uuid
`

type GetAgentMachineBindingByDeleteToolCallParams struct {
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	DeleteToolCallID uuid.UUID
}

func (q *Queries) GetAgentMachineBindingByDeleteToolCall(ctx context.Context, arg GetAgentMachineBindingByDeleteToolCallParams) (AgentMachineBinding, error) {
	row := q.db.QueryRow(ctx, getAgentMachineBindingByDeleteToolCall, arg.ProjectID, arg.AgentID, arg.DeleteToolCallID)
	var i AgentMachineBinding
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.CreateToolCallID,
		&i.DeleteToolCallID,
		&i.MachineID,
		&i.MachineRef,
		&i.BindingKind,
		&i.State,
		&i.Description,
		&i.Cwd,
		&i.EnvOverlay,
		&i.SecretEnvOverlay,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfterIdleMinutes,
	)
	return i, err
}

const getAgentMachineBindingByMachine = `-- name: GetAgentMachineBindingByMachine :one
SELECT id, org_id, project_id, agent_id, create_tool_call_id, delete_tool_call_id, machine_id, machine_ref, binding_kind, state, description, cwd, env_overlay, secret_env_overlay, metadata, created_at, updated_at, delete_after_idle_minutes
FROM agent_machine_bindings
WHERE project_id = $1
  AND agent_id = $2
  AND machine_id = $3
  AND binding_kind = $4
  AND ($5::boolean OR state = 'attached')
ORDER BY created_at, id
LIMIT 1
`

type GetAgentMachineBindingByMachineParams struct {
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
	MachineID       uuid.UUID
	BindingKind     string
	IncludeReleased bool
}

func (q *Queries) GetAgentMachineBindingByMachine(ctx context.Context, arg GetAgentMachineBindingByMachineParams) (AgentMachineBinding, error) {
	row := q.db.QueryRow(ctx, getAgentMachineBindingByMachine,
		arg.ProjectID,
		arg.AgentID,
		arg.MachineID,
		arg.BindingKind,
		arg.IncludeReleased,
	)
	var i AgentMachineBinding
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.CreateToolCallID,
		&i.DeleteToolCallID,
		&i.MachineID,
		&i.MachineRef,
		&i.BindingKind,
		&i.State,
		&i.Description,
		&i.Cwd,
		&i.EnvOverlay,
		&i.SecretEnvOverlay,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfterIdleMinutes,
	)
	return i, err
}

const getToolCallAgentConfigID = `-- name: GetToolCallAgentConfigID :one
SELECT context.agent_config_id
FROM tool_call_read_projection tool_call
JOIN model_call_contexts context ON context.project_id = tool_call.project_id
  AND context.agent_id = tool_call.agent_id
  AND context.id = tool_call.model_call_context_id
WHERE tool_call.project_id = $1
  AND tool_call.agent_id = $2
  AND tool_call.id = $3
`

type GetToolCallAgentConfigIDParams struct {
	ProjectID  uuid.UUID
	AgentID    uuid.UUID
	ToolCallID uuid.UUID
}

func (q *Queries) GetToolCallAgentConfigID(ctx context.Context, arg GetToolCallAgentConfigIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getToolCallAgentConfigID, arg.ProjectID, arg.AgentID, arg.ToolCallID)
	var agent_config_id uuid.UUID
	err := row.Scan(&agent_config_id)
	return agent_config_id, err
}

const insertAgentMachineBinding = `-- name: InsertAgentMachineBinding :one
INSERT INTO agent_machine_bindings(org_id, project_id, agent_id, create_tool_call_id, machine_id, machine_ref, binding_kind, state, description, cwd, env_overlay, secret_env_overlay, delete_after_idle_minutes, metadata, created_at, updated_at)
SELECT agent.org_id, agent.project_id, agent.id, $1::uuid, pmgrant.machine_id, $2, $3, 'attached', $4, $5, $6::jsonb, $7::jsonb, $8::integer, $9, statement_timestamp(), statement_timestamp()
FROM agents agent
JOIN project_machine_grants pmgrant ON pmgrant.project_id = agent.project_id
  AND pmgrant.id = $10
JOIN machines machine ON machine.org_id = agent.org_id
  AND machine.id = pmgrant.machine_id
  AND machine.deleted_at IS NULL
  AND (
    machine.lifecycle_state = 'active'
    OR (pmgrant.source_kind = 'pool' AND machine.source_kind = 'pool')
  )
WHERE agent.project_id = $11 AND agent.id = $12
  AND (
    $3::text = 'explicit'
    OR (
      $3::text = 'pool'
      AND pmgrant.source_kind = 'pool'
      AND machine.source_kind = 'pool'
    )
  )
ON CONFLICT (project_id, agent_id, machine_id) WHERE state = 'attached' DO NOTHING
RETURNING id, org_id, project_id, agent_id, create_tool_call_id, delete_tool_call_id, machine_id, machine_ref, binding_kind, state, description, cwd, env_overlay, secret_env_overlay, metadata, created_at, updated_at, delete_after_idle_minutes
`

type InsertAgentMachineBindingParams struct {
	CreateToolCallID       *uuid.UUID
	MachineRef             string
	BindingKind            string
	Description            string
	Cwd                    string
	EnvOverlay             json.RawMessage
	SecretEnvOverlay       json.RawMessage
	DeleteAfterIdleMinutes *int32
	Metadata               json.RawMessage
	ProjectMachineGrantID  uuid.UUID
	ProjectID              uuid.UUID
	AgentID                uuid.UUID
}

func (q *Queries) InsertAgentMachineBinding(ctx context.Context, arg InsertAgentMachineBindingParams) (AgentMachineBinding, error) {
	row := q.db.QueryRow(ctx, insertAgentMachineBinding,
		arg.CreateToolCallID,
		arg.MachineRef,
		arg.BindingKind,
		arg.Description,
		arg.Cwd,
		arg.EnvOverlay,
		arg.SecretEnvOverlay,
		arg.DeleteAfterIdleMinutes,
		arg.Metadata,
		arg.ProjectMachineGrantID,
		arg.ProjectID,
		arg.AgentID,
	)
	var i AgentMachineBinding
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.CreateToolCallID,
		&i.DeleteToolCallID,
		&i.MachineID,
		&i.MachineRef,
		&i.BindingKind,
		&i.State,
		&i.Description,
		&i.Cwd,
		&i.EnvOverlay,
		&i.SecretEnvOverlay,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfterIdleMinutes,
	)
	return i, err
}

const listAgentMachineBindings = `-- name: ListAgentMachineBindings :many
SELECT binding.id, binding.org_id, binding.project_id, binding.agent_id,
       binding.create_tool_call_id, binding.delete_tool_call_id, binding.machine_id,
       binding.machine_ref, binding.binding_kind, binding.state, binding.description,
       binding.env_overlay, binding.secret_env_overlay, binding.metadata,
       binding.created_at, binding.updated_at,
       coalesce(nullif(binding.cwd, ''), machine.cwd, '') AS effective_cwd
FROM agent_machine_bindings binding
LEFT JOIN machines machine ON machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
  AND machine.deleted_at IS NULL
WHERE binding.project_id = $1
  AND binding.agent_id = $2
ORDER BY binding.created_at, binding.id
`

type ListAgentMachineBindingsParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type ListAgentMachineBindingsRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	CreateToolCallID *uuid.UUID
	DeleteToolCallID *uuid.UUID
	MachineID        uuid.UUID
	MachineRef       string
	BindingKind      string
	State            string
	Description      string
	EnvOverlay       json.RawMessage
	SecretEnvOverlay json.RawMessage
	Metadata         json.RawMessage
	CreatedAt        time.Time
	UpdatedAt        time.Time
	EffectiveCwd     string
}

func (q *Queries) ListAgentMachineBindings(ctx context.Context, arg ListAgentMachineBindingsParams) ([]ListAgentMachineBindingsRow, error) {
	rows, err := q.db.Query(ctx, listAgentMachineBindings, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentMachineBindingsRow{}
	for rows.Next() {
		var i ListAgentMachineBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.CreateToolCallID,
			&i.DeleteToolCallID,
			&i.MachineID,
			&i.MachineRef,
			&i.BindingKind,
			&i.State,
			&i.Description,
			&i.EnvOverlay,
			&i.SecretEnvOverlay,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EffectiveCwd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachedAgentPoolMachineIDsForLifecycle = `-- name: ListAttachedAgentPoolMachineIDsForLifecycle :many
SELECT machine.id
FROM machines machine
JOIN agent_machine_bindings binding ON binding.org_id = machine.org_id
  AND binding.machine_id = machine.id
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND binding.binding_kind = 'pool'
  AND binding.state = 'attached'
  AND machine.source_kind = 'pool'
  AND machine.deleted_at IS NULL
  AND machine.lifecycle_state NOT IN ('deleting', 'delete_failed', 'deleted')
ORDER BY machine.id
`

type ListAttachedAgentPoolMachineIDsForLifecycleParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

func (q *Queries) ListAttachedAgentPoolMachineIDsForLifecycle(ctx context.Context, arg ListAttachedAgentPoolMachineIDsForLifecycleParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAttachedAgentPoolMachineIDsForLifecycle, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachedMachineBindingOverlays = `-- name: ListAttachedMachineBindingOverlays :many
SELECT id, env_overlay, secret_env_overlay
FROM agent_machine_bindings
WHERE org_id = $1
  AND machine_id = $2
  AND state = 'attached'
ORDER BY id
`

type ListAttachedMachineBindingOverlaysParams struct {
	OrgID     uuid.UUID
	MachineID uuid.UUID
}

type ListAttachedMachineBindingOverlaysRow struct {
	ID               uuid.UUID
	EnvOverlay       json.RawMessage
	SecretEnvOverlay json.RawMessage
}

func (q *Queries) ListAttachedMachineBindingOverlays(ctx context.Context, arg ListAttachedMachineBindingOverlaysParams) ([]ListAttachedMachineBindingOverlaysRow, error) {
	rows, err := q.db.Query(ctx, listAttachedMachineBindingOverlays, arg.OrgID, arg.MachineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachedMachineBindingOverlaysRow{}
	for rows.Next() {
		var i ListAttachedMachineBindingOverlaysRow
		if err := rows.Scan(&i.ID, &i.EnvOverlay, &i.SecretEnvOverlay); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutableAgentMachineBindings = `-- name: ListExecutableAgentMachineBindings :many
SELECT binding.id, binding.org_id, binding.project_id, binding.agent_id,
       binding.create_tool_call_id, binding.delete_tool_call_id, binding.machine_id,
       binding.machine_ref, binding.binding_kind, binding.state, binding.description,
       binding.env_overlay, binding.secret_env_overlay, binding.metadata,
       binding.created_at, binding.updated_at,
       coalesce(nullif(binding.cwd, ''), machine.cwd, '') AS effective_cwd
FROM agent_machine_bindings binding
JOIN project_machine_grants pmgrant ON pmgrant.project_id = binding.project_id
  AND pmgrant.machine_id = binding.machine_id
JOIN machines machine ON machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
  AND machine.deleted_at IS NULL
  AND machine.lifecycle_state = 'active'
JOIN machine_connection_states connection ON connection.org_id = machine.org_id
  AND connection.machine_id = machine.id
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND binding.state = 'attached'
  AND connection.connection_state IN ('online', 'asleep')
ORDER BY binding.created_at, binding.id
`

type ListExecutableAgentMachineBindingsParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type ListExecutableAgentMachineBindingsRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	CreateToolCallID *uuid.UUID
	DeleteToolCallID *uuid.UUID
	MachineID        uuid.UUID
	MachineRef       string
	BindingKind      string
	State            string
	Description      string
	EnvOverlay       json.RawMessage
	SecretEnvOverlay json.RawMessage
	Metadata         json.RawMessage
	CreatedAt        time.Time
	UpdatedAt        time.Time
	EffectiveCwd     string
}

func (q *Queries) ListExecutableAgentMachineBindings(ctx context.Context, arg ListExecutableAgentMachineBindingsParams) ([]ListExecutableAgentMachineBindingsRow, error) {
	rows, err := q.db.Query(ctx, listExecutableAgentMachineBindings, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutableAgentMachineBindingsRow{}
	for rows.Next() {
		var i ListExecutableAgentMachineBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.CreateToolCallID,
			&i.DeleteToolCallID,
			&i.MachineID,
			&i.MachineRef,
			&i.BindingKind,
			&i.State,
			&i.Description,
			&i.EnvOverlay,
			&i.SecretEnvOverlay,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EffectiveCwd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentMachineSources = `-- name: LockAgentMachineSources :exec
SELECT pg_advisory_xact_lock(
  hashtextextended('agent_machine_sources:' || $1::uuid::text, 0)
)
`

type LockAgentMachineSourcesParams struct {
	AgentID uuid.UUID
}

func (q *Queries) LockAgentMachineSources(ctx context.Context, arg LockAgentMachineSourcesParams) error {
	_, err := q.db.Exec(ctx, lockAgentMachineSources, arg.AgentID)
	return err
}

const lockAttachedAgentPoolMachines = `-- name: LockAttachedAgentPoolMachines :exec
SELECT machine.id
FROM machines machine
JOIN agent_machine_bindings binding ON binding.org_id = machine.org_id
  AND binding.machine_id = machine.id
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND binding.binding_kind = 'pool'
  AND binding.state = 'attached'
  AND machine.source_kind = 'pool'
  AND machine.deleted_at IS NULL
  AND machine.lifecycle_state NOT IN ('deleting', 'delete_failed', 'deleted')
ORDER BY machine.id
FOR UPDATE OF machine
`

type LockAttachedAgentPoolMachinesParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

func (q *Queries) LockAttachedAgentPoolMachines(ctx context.Context, arg LockAttachedAgentPoolMachinesParams) error {
	_, err := q.db.Exec(ctx, lockAttachedAgentPoolMachines, arg.ProjectID, arg.AgentID)
	return err
}

const markAgentMachineBindingDeleteRequested = `-- name: MarkAgentMachineBindingDeleteRequested :one
UPDATE agent_machine_bindings
SET delete_tool_call_id = $1::uuid,
    updated_at = statement_timestamp()
WHERE project_id = $2
  AND agent_id = $3
  AND id = $4
  AND state = 'attached'
  AND delete_tool_call_id IS NULL
RETURNING id, org_id, project_id, agent_id, create_tool_call_id, delete_tool_call_id, machine_id, machine_ref, binding_kind, state, description, cwd, env_overlay, secret_env_overlay, metadata, created_at, updated_at, delete_after_idle_minutes
`

type MarkAgentMachineBindingDeleteRequestedParams struct {
	DeleteToolCallID uuid.UUID
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	ID               uuid.UUID
}

func (q *Queries) MarkAgentMachineBindingDeleteRequested(ctx context.Context, arg MarkAgentMachineBindingDeleteRequestedParams) (AgentMachineBinding, error) {
	row := q.db.QueryRow(ctx, markAgentMachineBindingDeleteRequested,
		arg.DeleteToolCallID,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
	)
	var i AgentMachineBinding
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.CreateToolCallID,
		&i.DeleteToolCallID,
		&i.MachineID,
		&i.MachineRef,
		&i.BindingKind,
		&i.State,
		&i.Description,
		&i.Cwd,
		&i.EnvOverlay,
		&i.SecretEnvOverlay,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeleteAfterIdleMinutes,
	)
	return i, err
}

const markArchivedAgentPoolMachinesDeleting = `-- name: MarkArchivedAgentPoolMachinesDeleting :many
UPDATE machines machine
SET lifecycle_state = 'deleting',
    lifecycle_changed_at = agent.archived_at,
    lifecycle_version = machine.lifecycle_version + 1,
    lifecycle_reason_code = $1,
    lifecycle_reason_message = $2,
    next_reconcile_after = agent.archived_at,
    provider_runtime_mismatch_since = NULL,
    wake_attempt_expires_at = NULL,
    updated_at = agent.archived_at
FROM agent_machine_bindings binding
JOIN agents agent ON agent.org_id = binding.org_id
  AND agent.project_id = binding.project_id
  AND agent.id = binding.agent_id
WHERE binding.project_id = $3
  AND binding.agent_id = $4
  AND binding.binding_kind = 'pool'
  AND binding.state = 'attached'
  AND machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
  AND machine.source_kind = 'pool'
  AND agent.state = 'archived'
  AND agent.archived_at IS NOT NULL
  AND machine.deleted_at IS NULL
  AND machine.lifecycle_state NOT IN ('deleting', 'delete_failed', 'deleted')
RETURNING machine.id, machine.org_id, machine.machine_pool_id, machine.source_kind, machine.display_name, machine.description, machine.provider, machine.lifecycle_state, machine.provider_resource_id, machine.provider_provision_attempted_at, 'offline'::text AS connection_state, machine.last_observed_at, machine.cpu, machine.memory_mb, machine.cwd, machine.env, machine.secret_env, machine.provider_options, coalesce(machine.idempotency_key, '') AS idempotency_key, coalesce(machine.lifecycle_reason_code, '') AS lifecycle_reason_code, machine.lifecycle_reason_message, machine.next_reconcile_after, machine.provision_attempts, machine.delete_attempts, machine.metadata, machine.deleted_at, machine.created_at, machine.updated_at, machine.lifecycle_changed_at, machine.lifecycle_version
`

type MarkArchivedAgentPoolMachinesDeletingParams struct {
	LifecycleReasonCode    *string
	LifecycleReasonMessage string
	ProjectID              uuid.UUID
	AgentID                uuid.UUID
}

type MarkArchivedAgentPoolMachinesDeletingRow struct {
	ID                           uuid.UUID
	OrgID                        uuid.UUID
	MachinePoolID                *uuid.UUID
	SourceKind                   string
	DisplayName                  string
	Description                  string
	Provider                     string
	LifecycleState               string
	ProviderResourceID           *string
	ProviderProvisionAttemptedAt *time.Time
	ConnectionState              string
	LastObservedAt               *time.Time
	Cpu                          *int32
	MemoryMb                     *int32
	Cwd                          string
	Env                          json.RawMessage
	SecretEnv                    json.RawMessage
	ProviderOptions              *json.RawMessage
	IdempotencyKey               string
	LifecycleReasonCode          string
	LifecycleReasonMessage       string
	NextReconcileAfter           *time.Time
	ProvisionAttempts            int32
	DeleteAttempts               int32
	Metadata                     json.RawMessage
	DeletedAt                    *time.Time
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	LifecycleChangedAt           time.Time
	LifecycleVersion             int64
}

func (q *Queries) MarkArchivedAgentPoolMachinesDeleting(ctx context.Context, arg MarkArchivedAgentPoolMachinesDeletingParams) ([]MarkArchivedAgentPoolMachinesDeletingRow, error) {
	rows, err := q.db.Query(ctx, markArchivedAgentPoolMachinesDeleting,
		arg.LifecycleReasonCode,
		arg.LifecycleReasonMessage,
		arg.ProjectID,
		arg.AgentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkArchivedAgentPoolMachinesDeletingRow{}
	for rows.Next() {
		var i MarkArchivedAgentPoolMachinesDeletingRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.MachinePoolID,
			&i.SourceKind,
			&i.DisplayName,
			&i.Description,
			&i.Provider,
			&i.LifecycleState,
			&i.ProviderResourceID,
			&i.ProviderProvisionAttemptedAt,
			&i.ConnectionState,
			&i.LastObservedAt,
			&i.Cpu,
			&i.MemoryMb,
			&i.Cwd,
			&i.Env,
			&i.SecretEnv,
			&i.ProviderOptions,
			&i.IdempotencyKey,
			&i.LifecycleReasonCode,
			&i.LifecycleReasonMessage,
			&i.NextReconcileAfter,
			&i.ProvisionAttempts,
			&i.DeleteAttempts,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LifecycleChangedAt,
			&i.LifecycleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRemovedAgentPoolSourceMachinesDeleting = `-- name: MarkRemovedAgentPoolSourceMachinesDeleting :many
UPDATE machines machine
SET lifecycle_state = 'deleting',
    lifecycle_changed_at = statement_timestamp(),
    lifecycle_version = machine.lifecycle_version + 1,
    lifecycle_reason_code = $1,
    lifecycle_reason_message = $2,
    next_reconcile_after = statement_timestamp(),
    provider_runtime_mismatch_since = NULL,
    wake_attempt_expires_at = NULL,
    updated_at = statement_timestamp()
FROM agent_machine_bindings binding
WHERE binding.project_id = $3
  AND binding.agent_id = $4
  AND binding.binding_kind = 'pool'
  AND binding.state = 'attached'
  AND machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
  AND machine.source_kind = 'pool'
  AND machine.machine_pool_id = $5::uuid
  AND machine.deleted_at IS NULL
  AND machine.lifecycle_state NOT IN ('deleting', 'delete_failed', 'deleted')
RETURNING machine.id, machine.org_id, machine.machine_pool_id, machine.source_kind, machine.display_name, machine.description, machine.provider, machine.lifecycle_state, machine.provider_resource_id, machine.provider_provision_attempted_at, 'offline'::text AS connection_state, machine.last_observed_at, machine.cpu, machine.memory_mb, machine.cwd, machine.env, machine.secret_env, machine.provider_options, coalesce(machine.idempotency_key, '') AS idempotency_key, coalesce(machine.lifecycle_reason_code, '') AS lifecycle_reason_code, machine.lifecycle_reason_message, machine.next_reconcile_after, machine.provision_attempts, machine.delete_attempts, machine.metadata, machine.deleted_at, machine.created_at, machine.updated_at, machine.lifecycle_changed_at, machine.lifecycle_version
`

type MarkRemovedAgentPoolSourceMachinesDeletingParams struct {
	LifecycleReasonCode    *string
	LifecycleReasonMessage string
	ProjectID              uuid.UUID
	AgentID                uuid.UUID
	MachinePoolID          uuid.UUID
}

type MarkRemovedAgentPoolSourceMachinesDeletingRow struct {
	ID                           uuid.UUID
	OrgID                        uuid.UUID
	MachinePoolID                *uuid.UUID
	SourceKind                   string
	DisplayName                  string
	Description                  string
	Provider                     string
	LifecycleState               string
	ProviderResourceID           *string
	ProviderProvisionAttemptedAt *time.Time
	ConnectionState              string
	LastObservedAt               *time.Time
	Cpu                          *int32
	MemoryMb                     *int32
	Cwd                          string
	Env                          json.RawMessage
	SecretEnv                    json.RawMessage
	ProviderOptions              *json.RawMessage
	IdempotencyKey               string
	LifecycleReasonCode          string
	LifecycleReasonMessage       string
	NextReconcileAfter           *time.Time
	ProvisionAttempts            int32
	DeleteAttempts               int32
	Metadata                     json.RawMessage
	DeletedAt                    *time.Time
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	LifecycleChangedAt           time.Time
	LifecycleVersion             int64
}

func (q *Queries) MarkRemovedAgentPoolSourceMachinesDeleting(ctx context.Context, arg MarkRemovedAgentPoolSourceMachinesDeletingParams) ([]MarkRemovedAgentPoolSourceMachinesDeletingRow, error) {
	rows, err := q.db.Query(ctx, markRemovedAgentPoolSourceMachinesDeleting,
		arg.LifecycleReasonCode,
		arg.LifecycleReasonMessage,
		arg.ProjectID,
		arg.AgentID,
		arg.MachinePoolID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkRemovedAgentPoolSourceMachinesDeletingRow{}
	for rows.Next() {
		var i MarkRemovedAgentPoolSourceMachinesDeletingRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.MachinePoolID,
			&i.SourceKind,
			&i.DisplayName,
			&i.Description,
			&i.Provider,
			&i.LifecycleState,
			&i.ProviderResourceID,
			&i.ProviderProvisionAttemptedAt,
			&i.ConnectionState,
			&i.LastObservedAt,
			&i.Cpu,
			&i.MemoryMb,
			&i.Cwd,
			&i.Env,
			&i.SecretEnv,
			&i.ProviderOptions,
			&i.IdempotencyKey,
			&i.LifecycleReasonCode,
			&i.LifecycleReasonMessage,
			&i.NextReconcileAfter,
			&i.ProvisionAttempts,
			&i.DeleteAttempts,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LifecycleChangedAt,
			&i.LifecycleVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAgentMachineBindingsForMachine = `-- name: ReleaseAgentMachineBindingsForMachine :exec
UPDATE agent_machine_bindings
SET state = 'released',
    updated_at = statement_timestamp()
WHERE org_id = $1
  AND machine_id = $2
  AND state = 'attached'
`

type ReleaseAgentMachineBindingsForMachineParams struct {
	OrgID     uuid.UUID
	MachineID uuid.UUID
}

func (q *Queries) ReleaseAgentMachineBindingsForMachine(ctx context.Context, arg ReleaseAgentMachineBindingsForMachineParams) error {
	_, err := q.db.Exec(ctx, releaseAgentMachineBindingsForMachine, arg.OrgID, arg.MachineID)
	return err
}

const releaseExplicitAgentMachineBinding = `-- name: ReleaseExplicitAgentMachineBinding :execrows
UPDATE agent_machine_bindings
SET state = 'released',
    updated_at = statement_timestamp()
WHERE project_id = $1
  AND agent_id = $2
  AND machine_id = $3
  AND binding_kind = 'explicit'
  AND state = 'attached'
`

type ReleaseExplicitAgentMachineBindingParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	MachineID uuid.UUID
}

func (q *Queries) ReleaseExplicitAgentMachineBinding(ctx context.Context, arg ReleaseExplicitAgentMachineBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseExplicitAgentMachineBinding, arg.ProjectID, arg.AgentID, arg.MachineID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseExplicitAgentMachineBindingsForAgent = `-- name: ReleaseExplicitAgentMachineBindingsForAgent :exec
UPDATE agent_machine_bindings binding
SET state = 'released',
    updated_at = agent.archived_at
FROM agents agent
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND agent.org_id = binding.org_id
  AND agent.project_id = binding.project_id
  AND agent.id = binding.agent_id
  AND agent.state = 'archived'
  AND agent.archived_at IS NOT NULL
  AND binding.state = 'attached'
  AND binding.binding_kind = 'explicit'
`

type ReleaseExplicitAgentMachineBindingsForAgentParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

func (q *Queries) ReleaseExplicitAgentMachineBindingsForAgent(ctx context.Context, arg ReleaseExplicitAgentMachineBindingsForAgentParams) error {
	_, err := q.db.Exec(ctx, releaseExplicitAgentMachineBindingsForAgent, arg.ProjectID, arg.AgentID)
	return err
}

const selectAgentMachineObservations = `-- name: SelectAgentMachineObservations :many
SELECT binding.machine_ref,
       binding.binding_kind,
       binding.state AS binding_state,
       binding.description,
       coalesce(nullif(binding.cwd, ''), machine.cwd, '') AS effective_cwd,
       binding.created_at,
       binding.updated_at,
       machine.source_kind,
       machine.display_name,
       machine.lifecycle_state,
       machine.failure_report,
       connection.connection_state,
       coalesce(current_runtime.state_reason_code, '') AS connection_state_reason,
       coalesce(machine.lifecycle_reason_code, '') AS lifecycle_reason_code,
       machine.lifecycle_reason_message,
       coalesce(pool.name, '') AS machine_pool_name,
       (binding.state = 'attached' AND pmgrant.id IS NULL)::boolean AS project_grant_missing,
       coalesce((
         binding.state = 'attached'
         AND pmgrant.id IS NOT NULL
         AND machine.deleted_at IS NULL
         AND machine.lifecycle_state = 'active'
         AND connection.connection_state IN ('online', 'asleep')
       ), false)::boolean AS executable
FROM agent_machine_bindings binding
JOIN machines machine ON machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
LEFT JOIN project_machine_grants pmgrant ON pmgrant.org_id = binding.org_id
  AND pmgrant.project_id = binding.project_id
  AND pmgrant.machine_id = binding.machine_id
JOIN machine_connection_states connection ON connection.org_id = machine.org_id
  AND connection.machine_id = machine.id
LEFT JOIN daemon_runtimes current_runtime ON current_runtime.org_id = machine.org_id
  AND current_runtime.id = machine.current_daemon_runtime_id
LEFT JOIN machine_pools pool ON pool.org_id = machine.org_id
  AND pool.id = machine.machine_pool_id
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND ($3::text IS NULL OR binding.machine_ref = $3::text)
  AND (
    binding.state = 'attached'
    OR (
      $4::boolean
      AND $3::text IS NOT NULL
      AND binding.state = 'released'
      AND binding.binding_kind = 'pool'
      AND machine.source_kind = 'pool'
    )
  )
ORDER BY binding.created_at, binding.id
`

type SelectAgentMachineObservationsParams struct {
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
	MachineRef          *string
	IncludeReleasedPool bool
}

type SelectAgentMachineObservationsRow struct {
	MachineRef             string
	BindingKind            string
	BindingState           string
	Description            string
	EffectiveCwd           string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	SourceKind             string
	DisplayName            string
	LifecycleState         string
	FailureReport          *json.RawMessage
	ConnectionState        string
	ConnectionStateReason  string
	LifecycleReasonCode    string
	LifecycleReasonMessage string
	MachinePoolName        string
	ProjectGrantMissing    bool
	Executable             bool
}

func (q *Queries) SelectAgentMachineObservations(ctx context.Context, arg SelectAgentMachineObservationsParams) ([]SelectAgentMachineObservationsRow, error) {
	rows, err := q.db.Query(ctx, selectAgentMachineObservations,
		arg.ProjectID,
		arg.AgentID,
		arg.MachineRef,
		arg.IncludeReleasedPool,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectAgentMachineObservationsRow{}
	for rows.Next() {
		var i SelectAgentMachineObservationsRow
		if err := rows.Scan(
			&i.MachineRef,
			&i.BindingKind,
			&i.BindingState,
			&i.Description,
			&i.EffectiveCwd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceKind,
			&i.DisplayName,
			&i.LifecycleState,
			&i.FailureReport,
			&i.ConnectionState,
			&i.ConnectionStateReason,
			&i.LifecycleReasonCode,
			&i.LifecycleReasonMessage,
			&i.MachinePoolName,
			&i.ProjectGrantMissing,
			&i.Executable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPoolMachines = `-- name: SelectPoolMachines :many
SELECT binding.id,
       binding.org_id,
       binding.project_id,
       binding.agent_id,
       binding.create_tool_call_id,
       binding.delete_tool_call_id,
       binding.machine_id,
       binding.machine_ref,
       binding.binding_kind,
       binding.state,
       binding.description,
       binding.cwd,
       binding.env_overlay,
       binding.secret_env_overlay,
       binding.delete_after_idle_minutes,
       binding.metadata,
       binding.created_at,
       binding.updated_at,
       machine.machine_pool_id,
       machine.source_kind AS machine_source_kind,
       machine.display_name AS machine_display_name,
       machine.description AS machine_description,
       machine.provider,
       machine.lifecycle_state,
       machine.failure_report,
       machine.provider_resource_id,
       machine.provider_provision_attempted_at,
       connection.connection_state,
       coalesce(current_runtime.state_reason_code, '') AS connection_state_reason,
       machine.last_observed_at,
       machine.cpu,
       machine.memory_mb,
       machine.cwd AS machine_cwd,
       machine.env AS machine_env,
       machine.secret_env AS machine_secret_env,
       machine.provider_options,
       coalesce(machine.idempotency_key, '') AS machine_idempotency_key,
       coalesce(machine.lifecycle_reason_code, '') AS lifecycle_reason_code,
       machine.lifecycle_reason_message,
       machine.next_reconcile_after,
       machine.provision_attempts,
       machine.delete_attempts,
       machine.metadata AS machine_metadata,
       machine.deleted_at,
       machine.created_at AS machine_created_at,
       machine.updated_at AS machine_updated_at,
       machine.lifecycle_changed_at,
       machine.lifecycle_version,
       pool.name AS pool_name
FROM agent_machine_bindings binding
JOIN machines machine ON machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
  AND machine.source_kind = 'pool'
JOIN machine_pools pool ON pool.org_id = machine.org_id
  AND pool.id = machine.machine_pool_id
JOIN machine_connection_states connection ON connection.org_id = machine.org_id
  AND connection.machine_id = machine.id
LEFT JOIN daemon_runtimes current_runtime ON current_runtime.org_id = machine.org_id
  AND current_runtime.id = machine.current_daemon_runtime_id
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND binding.binding_kind = $3
  AND ($4::text IS NULL OR binding.machine_ref = $4::text)
  AND ($5::boolean OR binding.state = 'attached')
ORDER BY binding.created_at, binding.id
`

type SelectPoolMachinesParams struct {
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
	BindingKind     string
	MachineRef      *string
	IncludeReleased bool
}

type SelectPoolMachinesRow struct {
	ID                           uuid.UUID
	OrgID                        uuid.UUID
	ProjectID                    uuid.UUID
	AgentID                      uuid.UUID
	CreateToolCallID             *uuid.UUID
	DeleteToolCallID             *uuid.UUID
	MachineID                    uuid.UUID
	MachineRef                   string
	BindingKind                  string
	State                        string
	Description                  string
	Cwd                          string
	EnvOverlay                   json.RawMessage
	SecretEnvOverlay             json.RawMessage
	DeleteAfterIdleMinutes       *int32
	Metadata                     json.RawMessage
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	MachinePoolID                *uuid.UUID
	MachineSourceKind            string
	MachineDisplayName           string
	MachineDescription           string
	Provider                     string
	LifecycleState               string
	FailureReport                *json.RawMessage
	ProviderResourceID           *string
	ProviderProvisionAttemptedAt *time.Time
	ConnectionState              string
	ConnectionStateReason        string
	LastObservedAt               *time.Time
	Cpu                          *int32
	MemoryMb                     *int32
	MachineCwd                   string
	MachineEnv                   json.RawMessage
	MachineSecretEnv             json.RawMessage
	ProviderOptions              *json.RawMessage
	MachineIdempotencyKey        string
	LifecycleReasonCode          string
	LifecycleReasonMessage       string
	NextReconcileAfter           *time.Time
	ProvisionAttempts            int32
	DeleteAttempts               int32
	MachineMetadata              json.RawMessage
	DeletedAt                    *time.Time
	MachineCreatedAt             time.Time
	MachineUpdatedAt             time.Time
	LifecycleChangedAt           time.Time
	LifecycleVersion             int64
	PoolName                     string
}

func (q *Queries) SelectPoolMachines(ctx context.Context, arg SelectPoolMachinesParams) ([]SelectPoolMachinesRow, error) {
	rows, err := q.db.Query(ctx, selectPoolMachines,
		arg.ProjectID,
		arg.AgentID,
		arg.BindingKind,
		arg.MachineRef,
		arg.IncludeReleased,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectPoolMachinesRow{}
	for rows.Next() {
		var i SelectPoolMachinesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentID,
			&i.CreateToolCallID,
			&i.DeleteToolCallID,
			&i.MachineID,
			&i.MachineRef,
			&i.BindingKind,
			&i.State,
			&i.Description,
			&i.Cwd,
			&i.EnvOverlay,
			&i.SecretEnvOverlay,
			&i.DeleteAfterIdleMinutes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MachinePoolID,
			&i.MachineSourceKind,
			&i.MachineDisplayName,
			&i.MachineDescription,
			&i.Provider,
			&i.LifecycleState,
			&i.FailureReport,
			&i.ProviderResourceID,
			&i.ProviderProvisionAttemptedAt,
			&i.ConnectionState,
			&i.ConnectionStateReason,
			&i.LastObservedAt,
			&i.Cpu,
			&i.MemoryMb,
			&i.MachineCwd,
			&i.MachineEnv,
			&i.MachineSecretEnv,
			&i.ProviderOptions,
			&i.MachineIdempotencyKey,
			&i.LifecycleReasonCode,
			&i.LifecycleReasonMessage,
			&i.NextReconcileAfter,
			&i.ProvisionAttempts,
			&i.DeleteAttempts,
			&i.MachineMetadata,
			&i.DeletedAt,
			&i.MachineCreatedAt,
			&i.MachineUpdatedAt,
			&i.LifecycleChangedAt,
			&i.LifecycleVersion,
			&i.PoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttachedAgentMachineBindingConfig = `-- name: UpdateAttachedAgentMachineBindingConfig :execrows
UPDATE agent_machine_bindings
SET description = $1,
    cwd = $2,
    env_overlay = $3::jsonb,
    secret_env_overlay = $4::jsonb,
    delete_after_idle_minutes = $5::integer,
    updated_at = statement_timestamp()
WHERE project_id = $6
  AND agent_id = $7
  AND id = $8
  AND state = 'attached'
`

type UpdateAttachedAgentMachineBindingConfigParams struct {
	Description            string
	Cwd                    string
	EnvOverlay             json.RawMessage
	SecretEnvOverlay       json.RawMessage
	DeleteAfterIdleMinutes *int32
	ProjectID              uuid.UUID
	AgentID                uuid.UUID
	ID                     uuid.UUID
}

func (q *Queries) UpdateAttachedAgentMachineBindingConfig(ctx context.Context, arg UpdateAttachedAgentMachineBindingConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAttachedAgentMachineBindingConfig,
		arg.Description,
		arg.Cwd,
		arg.EnvOverlay,
		arg.SecretEnvOverlay,
		arg.DeleteAfterIdleMinutes,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
