// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_interactions.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const agentInteractionHasLaterStop = `-- name: AgentInteractionHasLaterStop :one
SELECT EXISTS (
  SELECT 1
FROM agent_interactions interaction
  JOIN tool_call_read_projection tool_call ON tool_call.agent_id = interaction.agent_id
    AND tool_call.id = interaction.tool_call_id
  JOIN agent_stop_events stop_event ON stop_event.project_id = tool_call.project_id
    AND stop_event.agent_id = tool_call.agent_id
    AND stop_event.sequence > tool_call.source_event_sequence
  WHERE tool_call.project_id = $1
    AND interaction.agent_id = $2
    AND interaction.id = $3
) AS stopped
`

type AgentInteractionHasLaterStopParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) AgentInteractionHasLaterStop(ctx context.Context, arg AgentInteractionHasLaterStopParams) (bool, error) {
	row := q.db.QueryRow(ctx, agentInteractionHasLaterStop, arg.ProjectID, arg.AgentID, arg.ID)
	var stopped bool
	err := row.Scan(&stopped)
	return stopped, err
}

const cancelOpenAgentInteractionsForAgent = `-- name: CancelOpenAgentInteractionsForAgent :many
UPDATE agent_interactions interaction
SET state = 'canceled',
	  resolution = jsonb_build_object('reason', $1::text),
	  resolved_by_input_id = $2::uuid,
	  resolved_at = statement_timestamp()
FROM agent_interaction_read_projection projection
WHERE interaction.agent_id = $3
	AND interaction.state = 'open'
	AND projection.project_id = $4
	AND projection.agent_id = interaction.agent_id
	AND projection.id = interaction.id
	AND projection.turn_id = $5
RETURNING interaction.id
`

type CancelOpenAgentInteractionsForAgentParams struct {
	Reason            string
	ResolvedByInputID *uuid.UUID
	AgentID           uuid.UUID
	ProjectID         uuid.UUID
	TurnID            uuid.UUID
}

func (q *Queries) CancelOpenAgentInteractionsForAgent(ctx context.Context, arg CancelOpenAgentInteractionsForAgentParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, cancelOpenAgentInteractionsForAgent,
		arg.Reason,
		arg.ResolvedByInputID,
		arg.AgentID,
		arg.ProjectID,
		arg.TurnID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelOpenAgentInteractionsForToolCall = `-- name: CancelOpenAgentInteractionsForToolCall :execrows
UPDATE agent_interactions
SET state = 'canceled',
    resolution = jsonb_build_object('reason', $1::text),
    resolved_by_input_id = NULL,
    resolved_at = statement_timestamp()
WHERE agent_interactions.agent_id = $2
  AND agent_interactions.tool_call_id = $3
  AND agent_interactions.state = 'open'
  AND EXISTS (
    SELECT 1
    FROM agents agent
    WHERE agent.id = agent_interactions.agent_id
      AND agent.project_id = $4
  )
`

type CancelOpenAgentInteractionsForToolCallParams struct {
	Reason     string
	AgentID    uuid.UUID
	ToolCallID uuid.UUID
	ProjectID  uuid.UUID
}

func (q *Queries) CancelOpenAgentInteractionsForToolCall(ctx context.Context, arg CancelOpenAgentInteractionsForToolCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOpenAgentInteractionsForToolCall,
		arg.Reason,
		arg.AgentID,
		arg.ToolCallID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentInteraction = `-- name: GetAgentInteraction :one
SELECT id, project_id, agent_id, turn_id,
       model_call_context_id, tool_call_id, provider_call_id,
       interaction_kind, state, request, resolution,
       resolved_by_input_id, created_at, resolved_at
FROM agent_interaction_read_projection
WHERE project_id = $1
  AND agent_id = $2
  AND id = $3
`

type GetAgentInteractionParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetAgentInteraction(ctx context.Context, arg GetAgentInteractionParams) (AgentInteractionReadProjection, error) {
	row := q.db.QueryRow(ctx, getAgentInteraction, arg.ProjectID, arg.AgentID, arg.ID)
	var i AgentInteractionReadProjection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.ModelCallContextID,
		&i.ToolCallID,
		&i.ProviderCallID,
		&i.InteractionKind,
		&i.State,
		&i.Request,
		&i.Resolution,
		&i.ResolvedByInputID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getAgentInteractionByToolCallKind = `-- name: GetAgentInteractionByToolCallKind :one
SELECT id, project_id, agent_id, turn_id,
       model_call_context_id, tool_call_id, provider_call_id,
       interaction_kind, state, request, resolution,
       resolved_by_input_id, created_at, resolved_at
FROM agent_interaction_read_projection
WHERE project_id = $1
  AND agent_id = $2
  AND tool_call_id = $3
  AND interaction_kind = $4
`

type GetAgentInteractionByToolCallKindParams struct {
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
	ToolCallID      uuid.UUID
	InteractionKind string
}

func (q *Queries) GetAgentInteractionByToolCallKind(ctx context.Context, arg GetAgentInteractionByToolCallKindParams) (AgentInteractionReadProjection, error) {
	row := q.db.QueryRow(ctx, getAgentInteractionByToolCallKind,
		arg.ProjectID,
		arg.AgentID,
		arg.ToolCallID,
		arg.InteractionKind,
	)
	var i AgentInteractionReadProjection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.ModelCallContextID,
		&i.ToolCallID,
		&i.ProviderCallID,
		&i.InteractionKind,
		&i.State,
		&i.Request,
		&i.Resolution,
		&i.ResolvedByInputID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertAgentInteraction = `-- name: InsertAgentInteraction :one
INSERT INTO agent_interactions(
  agent_id, tool_call_id,
  interaction_kind, state, request, created_at
)
SELECT tool_call.agent_id,
	     tool_call.id, $1, 'open',
	     $2, statement_timestamp()
FROM tool_call_read_projection tool_call
WHERE tool_call.project_id = $3
	AND tool_call.agent_id = $4
	AND tool_call.id = $5
RETURNING id
`

type InsertAgentInteractionParams struct {
	InteractionKind string
	Request         json.RawMessage
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
	ToolCallID      uuid.UUID
}

func (q *Queries) InsertAgentInteraction(ctx context.Context, arg InsertAgentInteractionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAgentInteraction,
		arg.InteractionKind,
		arg.Request,
		arg.ProjectID,
		arg.AgentID,
		arg.ToolCallID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertInteractionResponseAgentInput = `-- name: InsertInteractionResponseAgentInput :one
WITH target AS (
  SELECT projection.project_id, interaction.agent_id, interaction.id
  FROM agent_interactions interaction
  JOIN agent_interaction_read_projection projection
    ON projection.agent_id = interaction.agent_id
   AND projection.id = interaction.id
  WHERE projection.project_id = $7
    AND interaction.agent_id = $8
    AND interaction.id = $9
)
INSERT INTO agent_inputs(
  project_id, agent_id, state,
  actor_id, input_kind, integration_target_id, integration_target_binding_id,
  delivery_mode, target_interaction_id,
  idempotency_scope, input_idempotency_key, queued_at, metadata
)
SELECT target.project_id, target.agent_id, 'received',
       $1::uuid, 'interaction_response',
       $2::uuid,
       $3::uuid,
       'immediate', target.id,
       $4, $5,
       statement_timestamp(), $6
FROM target
ON CONFLICT (project_id, agent_id, idempotency_scope, input_idempotency_key) WHERE idempotency_scope IS NOT NULL AND input_idempotency_key IS NOT NULL DO NOTHING
RETURNING id, project_id, agent_id, state, input_rank, actor_id, input_kind,
  integration_target_id, integration_target_binding_id,
  coalesce(idempotency_scope, '') AS idempotency_scope,
  coalesce(input_idempotency_key, '') AS input_idempotency_key,
  queued_at, admitted_event_id, admitted_at, canceled_at, delivery_mode,
  coalesce(control_type, '') AS control_type, target_interaction_id,
  agent_config_id, resolved_at, coalesce(rejected_reason, '') AS rejected_reason, metadata
`

type InsertInteractionResponseAgentInputParams struct {
	ActorID                    *uuid.UUID
	IntegrationTargetID        *uuid.UUID
	IntegrationTargetBindingID *uuid.UUID
	IdempotencyScope           *string
	InputIdempotencyKey        *string
	Metadata                   json.RawMessage
	ProjectID                  uuid.UUID
	AgentID                    uuid.UUID
	TargetInteractionID        uuid.UUID
}

type InsertInteractionResponseAgentInputRow struct {
	ID                         uuid.UUID
	ProjectID                  uuid.UUID
	AgentID                    uuid.UUID
	State                      string
	InputRank                  int64
	ActorID                    *uuid.UUID
	InputKind                  string
	IntegrationTargetID        *uuid.UUID
	IntegrationTargetBindingID *uuid.UUID
	IdempotencyScope           string
	InputIdempotencyKey        string
	QueuedAt                   time.Time
	AdmittedEventID            *uuid.UUID
	AdmittedAt                 *time.Time
	CanceledAt                 *time.Time
	DeliveryMode               string
	ControlType                string
	TargetInteractionID        *uuid.UUID
	AgentConfigID              *uuid.UUID
	ResolvedAt                 *time.Time
	RejectedReason             string
	Metadata                   json.RawMessage
}

func (q *Queries) InsertInteractionResponseAgentInput(ctx context.Context, arg InsertInteractionResponseAgentInputParams) (InsertInteractionResponseAgentInputRow, error) {
	row := q.db.QueryRow(ctx, insertInteractionResponseAgentInput,
		arg.ActorID,
		arg.IntegrationTargetID,
		arg.IntegrationTargetBindingID,
		arg.IdempotencyScope,
		arg.InputIdempotencyKey,
		arg.Metadata,
		arg.ProjectID,
		arg.AgentID,
		arg.TargetInteractionID,
	)
	var i InsertInteractionResponseAgentInputRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.State,
		&i.InputRank,
		&i.ActorID,
		&i.InputKind,
		&i.IntegrationTargetID,
		&i.IntegrationTargetBindingID,
		&i.IdempotencyScope,
		&i.InputIdempotencyKey,
		&i.QueuedAt,
		&i.AdmittedEventID,
		&i.AdmittedAt,
		&i.CanceledAt,
		&i.DeliveryMode,
		&i.ControlType,
		&i.TargetInteractionID,
		&i.AgentConfigID,
		&i.ResolvedAt,
		&i.RejectedReason,
		&i.Metadata,
	)
	return i, err
}

const listAgentInteractionsByIDs = `-- name: ListAgentInteractionsByIDs :many
SELECT id, project_id, agent_id, turn_id,
	   model_call_context_id, tool_call_id, provider_call_id,
	   interaction_kind, state, request, resolution,
	   resolved_by_input_id, created_at, resolved_at
FROM agent_interaction_read_projection
WHERE project_id = $1
	AND agent_id = $2
	AND id = ANY($3::uuid[])
ORDER BY created_at, id
`

type ListAgentInteractionsByIDsParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	Ids       []uuid.UUID
}

func (q *Queries) ListAgentInteractionsByIDs(ctx context.Context, arg ListAgentInteractionsByIDsParams) ([]AgentInteractionReadProjection, error) {
	rows, err := q.db.Query(ctx, listAgentInteractionsByIDs, arg.ProjectID, arg.AgentID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentInteractionReadProjection{}
	for rows.Next() {
		var i AgentInteractionReadProjection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.TurnID,
			&i.ModelCallContextID,
			&i.ToolCallID,
			&i.ProviderCallID,
			&i.InteractionKind,
			&i.State,
			&i.Request,
			&i.Resolution,
			&i.ResolvedByInputID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentInteractionsForAgent = `-- name: ListAgentInteractionsForAgent :many
SELECT id, project_id, agent_id, turn_id,
       model_call_context_id, tool_call_id, provider_call_id,
       interaction_kind, state, request, resolution,
       resolved_by_input_id, created_at, resolved_at
FROM agent_interaction_read_projection
WHERE project_id = $1
  AND agent_id = $2
  AND ($3::text = '' OR state = $3)
  AND (
    $4::timestamptz IS NULL
    OR (created_at, id) > ($4::timestamptz, $5::uuid)
  )
ORDER BY created_at ASC, id ASC
LIMIT $6::bigint
`

type ListAgentInteractionsForAgentParams struct {
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
	State           string
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	RowLimit        int64
}

func (q *Queries) ListAgentInteractionsForAgent(ctx context.Context, arg ListAgentInteractionsForAgentParams) ([]AgentInteractionReadProjection, error) {
	rows, err := q.db.Query(ctx, listAgentInteractionsForAgent,
		arg.ProjectID,
		arg.AgentID,
		arg.State,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentInteractionReadProjection{}
	for rows.Next() {
		var i AgentInteractionReadProjection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.TurnID,
			&i.ModelCallContextID,
			&i.ToolCallID,
			&i.ProviderCallID,
			&i.InteractionKind,
			&i.State,
			&i.Request,
			&i.Resolution,
			&i.ResolvedByInputID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAgentInteraction = `-- name: ResolveAgentInteraction :one
UPDATE agent_interactions interaction
SET state = 'resolved',
	  resolution = $1,
	  resolved_by_input_id = $2::uuid,
	  resolved_at = statement_timestamp()
WHERE interaction.agent_id = $3
	AND interaction.id = $4
	AND interaction.state = 'open'
	AND EXISTS (
	  SELECT 1
	  FROM agents agent
	  WHERE agent.id = interaction.agent_id
	    AND agent.project_id = $5
	)
RETURNING interaction.id
`

type ResolveAgentInteractionParams struct {
	Resolution        json.RawMessage
	ResolvedByInputID *uuid.UUID
	AgentID           uuid.UUID
	ID                uuid.UUID
	ProjectID         uuid.UUID
}

func (q *Queries) ResolveAgentInteraction(ctx context.Context, arg ResolveAgentInteractionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveAgentInteraction,
		arg.Resolution,
		arg.ResolvedByInputID,
		arg.AgentID,
		arg.ID,
		arg.ProjectID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const resolveInteractionResponseAgentInput = `-- name: ResolveInteractionResponseAgentInput :one
UPDATE agent_inputs
SET state = 'resolved',
    admitted_event_id = $1,
    admitted_at = statement_timestamp(),
    resolved_at = statement_timestamp()
WHERE project_id = $2
  AND agent_id = $3
  AND id = $4
  AND input_kind = 'interaction_response'
  AND target_interaction_id = $5
  AND state = 'received'
RETURNING id, project_id, agent_id, state, input_rank, actor_id, input_kind, coalesce(idempotency_scope, '') AS idempotency_scope, coalesce(input_idempotency_key, '') AS input_idempotency_key, queued_at, admitted_event_id, admitted_at, canceled_at, delivery_mode, coalesce(control_type, '') AS control_type, target_interaction_id, agent_config_id, resolved_at, coalesce(rejected_reason, '') AS rejected_reason, metadata
`

type ResolveInteractionResponseAgentInputParams struct {
	EventID             *uuid.UUID
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
	ID                  uuid.UUID
	TargetInteractionID *uuid.UUID
}

type ResolveInteractionResponseAgentInputRow struct {
	ID                  uuid.UUID
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
	State               string
	InputRank           int64
	ActorID             *uuid.UUID
	InputKind           string
	IdempotencyScope    string
	InputIdempotencyKey string
	QueuedAt            time.Time
	AdmittedEventID     *uuid.UUID
	AdmittedAt          *time.Time
	CanceledAt          *time.Time
	DeliveryMode        string
	ControlType         string
	TargetInteractionID *uuid.UUID
	AgentConfigID       *uuid.UUID
	ResolvedAt          *time.Time
	RejectedReason      string
	Metadata            json.RawMessage
}

func (q *Queries) ResolveInteractionResponseAgentInput(ctx context.Context, arg ResolveInteractionResponseAgentInputParams) (ResolveInteractionResponseAgentInputRow, error) {
	row := q.db.QueryRow(ctx, resolveInteractionResponseAgentInput,
		arg.EventID,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
		arg.TargetInteractionID,
	)
	var i ResolveInteractionResponseAgentInputRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.State,
		&i.InputRank,
		&i.ActorID,
		&i.InputKind,
		&i.IdempotencyScope,
		&i.InputIdempotencyKey,
		&i.QueuedAt,
		&i.AdmittedEventID,
		&i.AdmittedAt,
		&i.CanceledAt,
		&i.DeliveryMode,
		&i.ControlType,
		&i.TargetInteractionID,
		&i.AgentConfigID,
		&i.ResolvedAt,
		&i.RejectedReason,
		&i.Metadata,
	)
	return i, err
}
