// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runtime.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const agentExistsInProject = `-- name: AgentExistsInProject :one
SELECT EXISTS (
    SELECT 1
    FROM agents
    WHERE project_id = $1 AND id = $2
)
`

type AgentExistsInProjectParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) AgentExistsInProject(ctx context.Context, arg AgentExistsInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, agentExistsInProject, arg.ProjectID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const archiveAgent = `-- name: ArchiveAgent :execrows
UPDATE agents
SET state = 'archived',
    archived_at = coalesce(archived_at, statement_timestamp()),
    updated_at = CASE
      WHEN state = 'archived' THEN updated_at
      ELSE statement_timestamp()
    END
WHERE project_id = $1
  AND id = $2
`

type ArchiveAgentParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

// Idempotent: archiving an already-archived agent matches the row and keeps
// the original archived_at.
func (q *Queries) ArchiveAgent(ctx context.Context, arg ArchiveAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveAgent, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgent = `-- name: GetAgent :one
SELECT id, org_id, project_id, state, name,
       agent_profile_id, current_config_id, integration_target_id,
       coalesce(idempotency_key, '') AS idempotency_key,
       next_event_sequence, created_at, updated_at, archived_at
FROM agents
WHERE id = $1
`

type GetAgentParams struct {
	ID uuid.UUID
}

type GetAgentRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	State               string
	Name                string
	AgentProfileID      *uuid.UUID
	CurrentConfigID     uuid.UUID
	IntegrationTargetID *uuid.UUID
	IdempotencyKey      string
	NextEventSequence   int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ArchivedAt          *time.Time
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.ID)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.State,
		&i.Name,
		&i.AgentProfileID,
		&i.CurrentConfigID,
		&i.IntegrationTargetID,
		&i.IdempotencyKey,
		&i.NextEventSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAgentByIdempotencyKey = `-- name: GetAgentByIdempotencyKey :one
SELECT id, org_id, project_id, state, name,
       agent_profile_id, current_config_id, integration_target_id,
       coalesce(idempotency_key, '') AS idempotency_key,
       next_event_sequence, created_at, updated_at, archived_at
FROM agents
WHERE project_id = $1
  AND idempotency_key = $2::text
`

type GetAgentByIdempotencyKeyParams struct {
	ProjectID      uuid.UUID
	IdempotencyKey string
}

type GetAgentByIdempotencyKeyRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	State               string
	Name                string
	AgentProfileID      *uuid.UUID
	CurrentConfigID     uuid.UUID
	IntegrationTargetID *uuid.UUID
	IdempotencyKey      string
	NextEventSequence   int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ArchivedAt          *time.Time
}

func (q *Queries) GetAgentByIdempotencyKey(ctx context.Context, arg GetAgentByIdempotencyKeyParams) (GetAgentByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getAgentByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i GetAgentByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.State,
		&i.Name,
		&i.AgentProfileID,
		&i.CurrentConfigID,
		&i.IntegrationTargetID,
		&i.IdempotencyKey,
		&i.NextEventSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAgentInProject = `-- name: GetAgentInProject :one
SELECT id, org_id, project_id, state, name,
       agent_profile_id, current_config_id, integration_target_id,
       coalesce(idempotency_key, '') AS idempotency_key,
       next_event_sequence, created_at, updated_at, archived_at
FROM agents
WHERE project_id = $1 AND id = $2
`

type GetAgentInProjectParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

type GetAgentInProjectRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	State               string
	Name                string
	AgentProfileID      *uuid.UUID
	CurrentConfigID     uuid.UUID
	IntegrationTargetID *uuid.UUID
	IdempotencyKey      string
	NextEventSequence   int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ArchivedAt          *time.Time
}

func (q *Queries) GetAgentInProject(ctx context.Context, arg GetAgentInProjectParams) (GetAgentInProjectRow, error) {
	row := q.db.QueryRow(ctx, getAgentInProject, arg.ProjectID, arg.ID)
	var i GetAgentInProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.State,
		&i.Name,
		&i.AgentProfileID,
		&i.CurrentConfigID,
		&i.IntegrationTargetID,
		&i.IdempotencyKey,
		&i.NextEventSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertAgent = `-- name: InsertAgent :one
INSERT INTO agents(
    org_id, project_id, state, name, agent_profile_id, current_config_id,
    idempotency_key, created_at, updated_at
)
VALUES (
    $1, $2, 'active', $3,
    $4, $5, $6,
    transaction_timestamp(), transaction_timestamp()
)
ON CONFLICT (project_id, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, org_id, project_id, state, name,
          agent_profile_id, current_config_id, integration_target_id,
          coalesce(idempotency_key, '') AS idempotency_key,
          next_event_sequence, created_at, updated_at, archived_at
`

type InsertAgentParams struct {
	OrgID           uuid.UUID
	ProjectID       uuid.UUID
	Name            string
	AgentProfileID  *uuid.UUID
	CurrentConfigID uuid.UUID
	IdempotencyKey  *string
}

type InsertAgentRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	State               string
	Name                string
	AgentProfileID      *uuid.UUID
	CurrentConfigID     uuid.UUID
	IntegrationTargetID *uuid.UUID
	IdempotencyKey      string
	NextEventSequence   int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ArchivedAt          *time.Time
}

func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (InsertAgentRow, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.AgentProfileID,
		arg.CurrentConfigID,
		arg.IdempotencyKey,
	)
	var i InsertAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.State,
		&i.Name,
		&i.AgentProfileID,
		&i.CurrentConfigID,
		&i.IntegrationTargetID,
		&i.IdempotencyKey,
		&i.NextEventSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listAgentsForProject = `-- name: ListAgentsForProject :many
WITH listed AS (
SELECT agent.id,
       agent.org_id,
       agent.project_id,
       agent.state,
       agent.name,
       agent.agent_profile_id,
       agent.current_config_id,
       agent.integration_target_id,
       coalesce(agent.idempotency_key, '') AS idempotency_key,
       agent.next_event_sequence,
       agent.created_at,
       agent.updated_at,
       agent.archived_at,
       coalesce(install.provider, '') AS integration_target_provider,
       coalesce(install.provider_tenant_id, '') AS integration_target_provider_tenant_id,
       coalesce(target.provider_ref, '') AS integration_target_provider_ref,
       coalesce(target.provider_ref_kind, '') AS integration_target_provider_ref_kind,
       coalesce(target.display_name, '') AS integration_target_display_name,
       configured_model.name AS model_name,
       model_provider_config.name AS model_provider_config_name,
       CASE $7::text
         WHEN 'name' THEN lower(agent.name)
         WHEN 'created_at' THEN to_char(agent.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
         WHEN 'updated_at' THEN to_char(agent.updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
         WHEN 'state' THEN agent.state
         WHEN 'integration_provider' THEN lower(install.provider)
         WHEN 'integration_target_kind' THEN lower(target.provider_ref_kind)
       END::text AS sort_key,
       CASE $7::text
         WHEN 'integration_provider' THEN target.id IS NULL
         WHEN 'integration_target_kind' THEN target.id IS NULL
         ELSE false
       END AS sort_is_null
FROM agents agent
LEFT JOIN integration_targets target
  ON target.project_id = agent.project_id
 AND target.agent_id = agent.id
 AND target.id = agent.integration_target_id
 AND target.deleted_at IS NULL
LEFT JOIN integration_installs install
  ON install.project_id = target.project_id
 AND install.id = target.integration_install_id
 AND install.deleted_at IS NULL
JOIN agent_configs agent_config
  ON agent_config.project_id = agent.project_id
 AND agent_config.id = agent.current_config_id
JOIN configured_models configured_model
  ON configured_model.org_id = agent.org_id
 AND configured_model.id = agent_config.configured_model_id
JOIN model_provider_configs model_provider_config
  ON model_provider_config.org_id = configured_model.org_id
 AND model_provider_config.id = configured_model.model_provider_config_id
WHERE agent.project_id = $8
  AND agent.state = 'active'
  AND ($9::text = '' OR agent.name ILIKE $9::text ESCAPE '\')
  AND (COALESCE(cardinality($10::text[]), 0) = 0 OR install.provider = ANY($10::text[]))
  AND (COALESCE(cardinality($11::text[]), 0) = 0 OR target.provider_ref_kind = ANY($11::text[]))
  AND ($12::boolean IS NULL OR (target.id IS NOT NULL) = $12::boolean)
  AND ($13::uuid IS NULL OR agent.agent_profile_id = $13::uuid)
)
SELECT id, org_id, project_id, state, name, agent_profile_id, current_config_id,
       integration_target_id, idempotency_key,
       next_event_sequence, created_at, updated_at,
       archived_at, integration_target_provider,
       integration_target_provider_tenant_id, integration_target_provider_ref,
       integration_target_provider_ref_kind,
       integration_target_display_name, model_name,
       model_provider_config_name, sort_key, sort_is_null
FROM listed
WHERE $1::boolean = false
   OR sort_is_null > $2::boolean
   OR (sort_is_null = $2::boolean AND (
        ($3::boolean = false AND (sort_key, id) > ($4::text, $5::uuid))
     OR ($3::boolean = true AND (sort_key, id) < ($4::text, $5::uuid))
   ))
ORDER BY sort_is_null ASC,
         CASE WHEN $3::boolean = false THEN sort_key END ASC,
         CASE WHEN $3::boolean = true THEN sort_key END DESC,
         CASE WHEN $3::boolean = false THEN id END ASC,
         CASE WHEN $3::boolean = true THEN id END DESC
LIMIT $6::bigint
`

type ListAgentsForProjectParams struct {
	CursorSet              bool
	CursorIsNull           bool
	SortDesc               bool
	CursorKey              string
	CursorID               uuid.UUID
	RowLimit               int64
	SortField              string
	ProjectID              uuid.UUID
	NamePattern            string
	IntegrationProviders   []string
	IntegrationTargetKinds []string
	HasIntegrationTarget   *bool
	AgentProfileID         *uuid.UUID
}

type ListAgentsForProjectRow struct {
	ID                                uuid.UUID
	OrgID                             uuid.UUID
	ProjectID                         uuid.UUID
	State                             string
	Name                              string
	AgentProfileID                    *uuid.UUID
	CurrentConfigID                   uuid.UUID
	IntegrationTargetID               *uuid.UUID
	IdempotencyKey                    string
	NextEventSequence                 int64
	CreatedAt                         time.Time
	UpdatedAt                         time.Time
	ArchivedAt                        *time.Time
	IntegrationTargetProvider         string
	IntegrationTargetProviderTenantID string
	IntegrationTargetProviderRef      string
	IntegrationTargetProviderRefKind  string
	IntegrationTargetDisplayName      string
	ModelName                         string
	ModelProviderConfigName           string
	SortKey                           string
	SortIsNull                        bool
}

func (q *Queries) ListAgentsForProject(ctx context.Context, arg ListAgentsForProjectParams) ([]ListAgentsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listAgentsForProject,
		arg.CursorSet,
		arg.CursorIsNull,
		arg.SortDesc,
		arg.CursorKey,
		arg.CursorID,
		arg.RowLimit,
		arg.SortField,
		arg.ProjectID,
		arg.NamePattern,
		arg.IntegrationProviders,
		arg.IntegrationTargetKinds,
		arg.HasIntegrationTarget,
		arg.AgentProfileID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsForProjectRow{}
	for rows.Next() {
		var i ListAgentsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.State,
			&i.Name,
			&i.AgentProfileID,
			&i.CurrentConfigID,
			&i.IntegrationTargetID,
			&i.IdempotencyKey,
			&i.NextEventSequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.IntegrationTargetProvider,
			&i.IntegrationTargetProviderTenantID,
			&i.IntegrationTargetProviderRef,
			&i.IntegrationTargetProviderRefKind,
			&i.IntegrationTargetDisplayName,
			&i.ModelName,
			&i.ModelProviderConfigName,
			&i.SortKey,
			&i.SortIsNull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsForProjectByCreatedAtDesc = `-- name: ListAgentsForProjectByCreatedAtDesc :many
SELECT agent.id,
       agent.org_id,
       agent.project_id,
       agent.state,
       agent.name,
       agent.agent_profile_id,
       agent.current_config_id,
       agent.integration_target_id,
       coalesce(agent.idempotency_key, '') AS idempotency_key,
       agent.next_event_sequence,
       agent.created_at,
       agent.updated_at,
       agent.archived_at,
       coalesce(install.provider, '') AS integration_target_provider,
       coalesce(install.provider_tenant_id, '') AS integration_target_provider_tenant_id,
       coalesce(target.provider_ref, '') AS integration_target_provider_ref,
       coalesce(target.provider_ref_kind, '') AS integration_target_provider_ref_kind,
       coalesce(target.display_name, '') AS integration_target_display_name,
       configured_model.name AS model_name,
       model_provider_config.name AS model_provider_config_name
FROM agents agent
LEFT JOIN integration_targets target
  ON target.project_id = agent.project_id
 AND target.agent_id = agent.id
 AND target.id = agent.integration_target_id
 AND target.deleted_at IS NULL
LEFT JOIN integration_installs install
  ON install.project_id = target.project_id
 AND install.id = target.integration_install_id
 AND install.deleted_at IS NULL
JOIN agent_configs agent_config
  ON agent_config.project_id = agent.project_id
 AND agent_config.id = agent.current_config_id
JOIN configured_models configured_model
  ON configured_model.org_id = agent.org_id
 AND configured_model.id = agent_config.configured_model_id
JOIN model_provider_configs model_provider_config
  ON model_provider_config.org_id = configured_model.org_id
 AND model_provider_config.id = configured_model.model_provider_config_id
WHERE agent.project_id = $1
  AND agent.state = 'active'
  AND ($2::text = '' OR agent.name ILIKE $2::text ESCAPE '\')
  AND (COALESCE(cardinality($3::text[]), 0) = 0 OR install.provider = ANY($3::text[]))
  AND (COALESCE(cardinality($4::text[]), 0) = 0 OR target.provider_ref_kind = ANY($4::text[]))
  AND ($5::boolean IS NULL OR (target.id IS NOT NULL) = $5::boolean)
  AND ($6::uuid IS NULL OR agent.agent_profile_id = $6::uuid)
  AND (
    $7::boolean = false
    OR (agent.created_at, agent.id) < ($8::timestamptz, $9::uuid)
  )
ORDER BY agent.created_at DESC, agent.id DESC
LIMIT $10::bigint
`

type ListAgentsForProjectByCreatedAtDescParams struct {
	ProjectID              uuid.UUID
	NamePattern            string
	IntegrationProviders   []string
	IntegrationTargetKinds []string
	HasIntegrationTarget   *bool
	AgentProfileID         *uuid.UUID
	CursorSet              bool
	CursorCreatedAt        time.Time
	CursorID               uuid.UUID
	RowLimit               int64
}

type ListAgentsForProjectByCreatedAtDescRow struct {
	ID                                uuid.UUID
	OrgID                             uuid.UUID
	ProjectID                         uuid.UUID
	State                             string
	Name                              string
	AgentProfileID                    *uuid.UUID
	CurrentConfigID                   uuid.UUID
	IntegrationTargetID               *uuid.UUID
	IdempotencyKey                    string
	NextEventSequence                 int64
	CreatedAt                         time.Time
	UpdatedAt                         time.Time
	ArchivedAt                        *time.Time
	IntegrationTargetProvider         string
	IntegrationTargetProviderTenantID string
	IntegrationTargetProviderRef      string
	IntegrationTargetProviderRefKind  string
	IntegrationTargetDisplayName      string
	ModelName                         string
	ModelProviderConfigName           string
}

func (q *Queries) ListAgentsForProjectByCreatedAtDesc(ctx context.Context, arg ListAgentsForProjectByCreatedAtDescParams) ([]ListAgentsForProjectByCreatedAtDescRow, error) {
	rows, err := q.db.Query(ctx, listAgentsForProjectByCreatedAtDesc,
		arg.ProjectID,
		arg.NamePattern,
		arg.IntegrationProviders,
		arg.IntegrationTargetKinds,
		arg.HasIntegrationTarget,
		arg.AgentProfileID,
		arg.CursorSet,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsForProjectByCreatedAtDescRow{}
	for rows.Next() {
		var i ListAgentsForProjectByCreatedAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.State,
			&i.Name,
			&i.AgentProfileID,
			&i.CurrentConfigID,
			&i.IntegrationTargetID,
			&i.IdempotencyKey,
			&i.NextEventSequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.IntegrationTargetProvider,
			&i.IntegrationTargetProviderTenantID,
			&i.IntegrationTargetProviderRef,
			&i.IntegrationTargetProviderRefKind,
			&i.IntegrationTargetDisplayName,
			&i.ModelName,
			&i.ModelProviderConfigName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentInProject = `-- name: LockAgentInProject :one
SELECT id, org_id
FROM agents
WHERE project_id = $1 AND id = $2
FOR UPDATE
`

type LockAgentInProjectParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

type LockAgentInProjectRow struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) LockAgentInProject(ctx context.Context, arg LockAgentInProjectParams) (LockAgentInProjectRow, error) {
	row := q.db.QueryRow(ctx, lockAgentInProject, arg.ProjectID, arg.ID)
	var i LockAgentInProjectRow
	err := row.Scan(&i.ID, &i.OrgID)
	return i, err
}

const lockAgentLaunchIdempotencyKey = `-- name: LockAgentLaunchIdempotencyKey :exec
SELECT pg_advisory_xact_lock(
  hashtextextended(
    $1::uuid::text,
    hashtextextended($2::text, 0)
  )
)
`

type LockAgentLaunchIdempotencyKeyParams struct {
	ProjectID      uuid.UUID
	IdempotencyKey string
}

func (q *Queries) LockAgentLaunchIdempotencyKey(ctx context.Context, arg LockAgentLaunchIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, lockAgentLaunchIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	return err
}

const lockProjectAgentLifecycleExclusive = `-- name: LockProjectAgentLifecycleExclusive :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

type LockProjectAgentLifecycleExclusiveParams struct {
	ProjectID string
}

func (q *Queries) LockProjectAgentLifecycleExclusive(ctx context.Context, arg LockProjectAgentLifecycleExclusiveParams) error {
	_, err := q.db.Exec(ctx, lockProjectAgentLifecycleExclusive, arg.ProjectID)
	return err
}

const lockProjectAgentLifecycleShared = `-- name: LockProjectAgentLifecycleShared :exec
SELECT pg_advisory_xact_lock_shared(hashtextextended($1::text, 0))
`

type LockProjectAgentLifecycleSharedParams struct {
	ProjectID string
}

// Agent creation takes the shared side: creates never conflict with each
// other, only with project/org deletion, which holds the exclusive side.
func (q *Queries) LockProjectAgentLifecycleShared(ctx context.Context, arg LockProjectAgentLifecycleSharedParams) error {
	_, err := q.db.Exec(ctx, lockProjectAgentLifecycleShared, arg.ProjectID)
	return err
}
