// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_targets.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getAgentConversationTarget = `-- name: GetAgentConversationTarget :one
SELECT id, project_id, agent_id, app_id, provider_ref,
       provider_ref_kind, display_name, provider_metadata, selection_slot, is_tool_context,
       deleted_at, created_at, updated_at
FROM integration_targets
WHERE project_id = $1 AND agent_id = $2
  AND app_id = $3
  AND provider_ref_kind = $4 AND provider_ref = $5
  AND deleted_at IS NULL
`

type GetAgentConversationTargetParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	AppID     uuid.UUID
	Kind      string
	Ref       string
}

type GetAgentConversationTargetRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	AppID            uuid.UUID
	ProviderRef      string
	ProviderRefKind  string
	DisplayName      string
	ProviderMetadata json.RawMessage
	SelectionSlot    *string
	IsToolContext    bool
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetAgentConversationTarget(ctx context.Context, arg GetAgentConversationTargetParams) (GetAgentConversationTargetRow, error) {
	row := q.db.QueryRow(ctx, getAgentConversationTarget,
		arg.ProjectID,
		arg.AgentID,
		arg.AppID,
		arg.Kind,
		arg.Ref,
	)
	var i GetAgentConversationTargetRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.AppID,
		&i.ProviderRef,
		&i.ProviderRefKind,
		&i.DisplayName,
		&i.ProviderMetadata,
		&i.SelectionSlot,
		&i.IsToolContext,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppSelectionTarget = `-- name: GetAppSelectionTarget :one
SELECT id, project_id, agent_id, app_id, provider_ref,
       provider_ref_kind, display_name, provider_metadata, selection_slot, is_tool_context,
       deleted_at, created_at, updated_at
FROM integration_targets
WHERE project_id = $1 AND app_id = $2
  AND provider_ref_kind = $3 AND provider_ref = $4
  AND selection_slot = $5
`

type GetAppSelectionTargetParams struct {
	ProjectID uuid.UUID
	AppID     uuid.UUID
	Kind      string
	Ref       string
	Slot      *string
}

type GetAppSelectionTargetRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	AppID            uuid.UUID
	ProviderRef      string
	ProviderRefKind  string
	DisplayName      string
	ProviderMetadata json.RawMessage
	SelectionSlot    *string
	IsToolContext    bool
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetAppSelectionTarget(ctx context.Context, arg GetAppSelectionTargetParams) (GetAppSelectionTargetRow, error) {
	row := q.db.QueryRow(ctx, getAppSelectionTarget,
		arg.ProjectID,
		arg.AppID,
		arg.Kind,
		arg.Ref,
		arg.Slot,
	)
	var i GetAppSelectionTargetRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.AppID,
		&i.ProviderRef,
		&i.ProviderRefKind,
		&i.DisplayName,
		&i.ProviderMetadata,
		&i.SelectionSlot,
		&i.IsToolContext,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationDisplayName = `-- name: GetConversationDisplayName :one
SELECT display_name
FROM integration_targets
WHERE project_id = $1 AND app_id = $2
  AND provider_ref_kind = $3 AND provider_ref = $4
  AND deleted_at IS NULL AND display_name <> ''
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetConversationDisplayNameParams struct {
	ProjectID uuid.UUID
	AppID     uuid.UUID
	Kind      string
	Ref       string
}

// Presentation only: several agents may have targets at this exact address.
// Reuse the latest known nonempty label without selecting a routing authority.
func (q *Queries) GetConversationDisplayName(ctx context.Context, arg GetConversationDisplayNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getConversationDisplayName,
		arg.ProjectID,
		arg.AppID,
		arg.Kind,
		arg.Ref,
	)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const insertAppConversationTarget = `-- name: InsertAppConversationTarget :one
INSERT INTO integration_targets(project_id, agent_id, app_id,
    provider_ref_kind, provider_ref, display_name, selection_slot, is_tool_context, created_at, updated_at)
VALUES ($1, $2, $3,
    $4, $5, $6, $7, $8,
    transaction_timestamp(), transaction_timestamp())
ON CONFLICT DO NOTHING
RETURNING id, project_id, agent_id, app_id, provider_ref,
          provider_ref_kind, display_name, provider_metadata, selection_slot, is_tool_context,
          deleted_at, created_at, updated_at
`

type InsertAppConversationTargetParams struct {
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	AppID         uuid.UUID
	Kind          string
	Ref           string
	DisplayName   string
	Slot          *string
	IsToolContext bool
}

type InsertAppConversationTargetRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	AppID            uuid.UUID
	ProviderRef      string
	ProviderRefKind  string
	DisplayName      string
	ProviderMetadata json.RawMessage
	SelectionSlot    *string
	IsToolContext    bool
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertAppConversationTarget(ctx context.Context, arg InsertAppConversationTargetParams) (InsertAppConversationTargetRow, error) {
	row := q.db.QueryRow(ctx, insertAppConversationTarget,
		arg.ProjectID,
		arg.AgentID,
		arg.AppID,
		arg.Kind,
		arg.Ref,
		arg.DisplayName,
		arg.Slot,
		arg.IsToolContext,
	)
	var i InsertAppConversationTargetRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.AppID,
		&i.ProviderRef,
		&i.ProviderRefKind,
		&i.DisplayName,
		&i.ProviderMetadata,
		&i.SelectionSlot,
		&i.IsToolContext,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationSelections = `-- name: ListConversationSelections :many
SELECT id, project_id, agent_id, app_id, provider_ref,
       provider_ref_kind, display_name, provider_metadata, selection_slot, is_tool_context,
       deleted_at, created_at, updated_at
FROM integration_targets target
WHERE target.project_id = $1 AND target.app_id = $2
  AND target.provider_ref_kind = $3 AND target.provider_ref = $4
  AND target.selection_slot IS NOT NULL
ORDER BY target.id
`

type ListConversationSelectionsParams struct {
	ProjectID uuid.UUID
	AppID     uuid.UUID
	Kind      string
	Ref       string
}

type ListConversationSelectionsRow struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	AppID            uuid.UUID
	ProviderRef      string
	ProviderRefKind  string
	DisplayName      string
	ProviderMetadata json.RawMessage
	SelectionSlot    *string
	IsToolContext    bool
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// Retired selections intentionally remain visible: stopping a selected agent
// must not cause the next comment to launch a replacement.
func (q *Queries) ListConversationSelections(ctx context.Context, arg ListConversationSelectionsParams) ([]ListConversationSelectionsRow, error) {
	rows, err := q.db.Query(ctx, listConversationSelections,
		arg.ProjectID,
		arg.AppID,
		arg.Kind,
		arg.Ref,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationSelectionsRow{}
	for rows.Next() {
		var i ListConversationSelectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.AppID,
			&i.ProviderRef,
			&i.ProviderRefKind,
			&i.DisplayName,
			&i.ProviderMetadata,
			&i.SelectionSlot,
			&i.IsToolContext,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAppConversation = `-- name: LockAppConversation :exec
SELECT pg_advisory_xact_lock(hashtextextended(
    'app_conversation:' || jsonb_build_array($1::uuid, $2::uuid,
        $3::text, $4::text)::text, 0))
`

type LockAppConversationParams struct {
	ProjectID uuid.UUID
	AppID     uuid.UUID
	Kind      string
	Ref       string
}

// The conversation gate serializes launcher selection with subscription changes.
// Acquire it after project/app gates and before agent locks.
func (q *Queries) LockAppConversation(ctx context.Context, arg LockAppConversationParams) error {
	_, err := q.db.Exec(ctx, lockAppConversation,
		arg.ProjectID,
		arg.AppID,
		arg.Kind,
		arg.Ref,
	)
	return err
}
