// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_definitions.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getChannelDefinition = `-- name: GetChannelDefinition :one
SELECT id, project_id, integration_install_id, implementation_key, kind,
  description, send_params_schema, capabilities, created_at, updated_at
FROM integration_channel_definitions
WHERE project_id = $1
  AND integration_install_id = $2
  AND id = $3
`

type GetChannelDefinitionParams struct {
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
	ID                   uuid.UUID
}

func (q *Queries) GetChannelDefinition(ctx context.Context, arg GetChannelDefinitionParams) (IntegrationChannelDefinition, error) {
	row := q.db.QueryRow(ctx, getChannelDefinition, arg.ProjectID, arg.IntegrationInstallID, arg.ID)
	var i IntegrationChannelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IntegrationInstallID,
		&i.ImplementationKey,
		&i.Kind,
		&i.Description,
		&i.SendParamsSchema,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelDefinitionByImplementation = `-- name: GetChannelDefinitionByImplementation :one
SELECT id, project_id, integration_install_id, implementation_key, kind,
  description, send_params_schema, capabilities, created_at, updated_at
FROM integration_channel_definitions
WHERE project_id = $1 AND integration_install_id = $2
  AND implementation_key = $3
`

type GetChannelDefinitionByImplementationParams struct {
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
	ImplementationKey    string
}

func (q *Queries) GetChannelDefinitionByImplementation(ctx context.Context, arg GetChannelDefinitionByImplementationParams) (IntegrationChannelDefinition, error) {
	row := q.db.QueryRow(ctx, getChannelDefinitionByImplementation, arg.ProjectID, arg.IntegrationInstallID, arg.ImplementationKey)
	var i IntegrationChannelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IntegrationInstallID,
		&i.ImplementationKey,
		&i.Kind,
		&i.Description,
		&i.SendParamsSchema,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockChannelDefinition = `-- name: LockChannelDefinition :one
SELECT id
FROM integration_channel_definitions
WHERE project_id = $1
  AND integration_install_id = $2
  AND id = $3
FOR SHARE
`

type LockChannelDefinitionParams struct {
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
	ID                   uuid.UUID
}

func (q *Queries) LockChannelDefinition(ctx context.Context, arg LockChannelDefinitionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockChannelDefinition, arg.ProjectID, arg.IntegrationInstallID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertChannelDefinition = `-- name: UpsertChannelDefinition :one
INSERT INTO integration_channel_definitions (
  project_id, integration_install_id, implementation_key, kind, description,
  send_params_schema, capabilities, created_at, updated_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, statement_timestamp(), statement_timestamp()
)
ON CONFLICT (project_id, integration_install_id, implementation_key)
DO UPDATE SET description = EXCLUDED.description,
  send_params_schema = EXCLUDED.send_params_schema,
  capabilities = EXCLUDED.capabilities, updated_at = statement_timestamp()
WHERE integration_channel_definitions.kind = EXCLUDED.kind
RETURNING id, project_id, integration_install_id, implementation_key, kind,
  description, send_params_schema, capabilities, created_at, updated_at
`

type UpsertChannelDefinitionParams struct {
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
	ImplementationKey    string
	Kind                 string
	Description          string
	SendParamsSchema     json.RawMessage
	Capabilities         json.RawMessage
}

func (q *Queries) UpsertChannelDefinition(ctx context.Context, arg UpsertChannelDefinitionParams) (IntegrationChannelDefinition, error) {
	row := q.db.QueryRow(ctx, upsertChannelDefinition,
		arg.ProjectID,
		arg.IntegrationInstallID,
		arg.ImplementationKey,
		arg.Kind,
		arg.Description,
		arg.SendParamsSchema,
		arg.Capabilities,
	)
	var i IntegrationChannelDefinition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IntegrationInstallID,
		&i.ImplementationKey,
		&i.Kind,
		&i.Description,
		&i.SendParamsSchema,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
