// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cron_triggers.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimCronTrigger = `-- name: ClaimCronTrigger :execrows
UPDATE cron_triggers
SET claimed_until = $1,
    claim_token = $2,
    updated_at = statement_timestamp()
WHERE project_id = $3
  AND id = $4
  AND deleted_at IS NULL
`

type ClaimCronTriggerParams struct {
	ClaimedUntil *time.Time
	ClaimToken   *uuid.UUID
	ProjectID    uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) ClaimCronTrigger(ctx context.Context, arg ClaimCronTriggerParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimCronTrigger,
		arg.ClaimedUntil,
		arg.ClaimToken,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeCronTriggerFiring = `-- name: CompleteCronTriggerFiring :execrows
UPDATE cron_triggers
SET last_fired_at = CASE WHEN $1::boolean THEN transaction_timestamp() ELSE last_fired_at END,
    failure_report = CASE WHEN $1::boolean THEN NULL ELSE failure_report END,
    next_fire_after = $2,
    claimed_until = NULL,
    claim_token = NULL,
    updated_at = statement_timestamp()
WHERE project_id = $3
  AND id = $4
  AND claim_token = $5
  AND deleted_at IS NULL
`

type CompleteCronTriggerFiringParams struct {
	Fired         bool
	NextFireAfter *time.Time
	ProjectID     uuid.UUID
	ID            uuid.UUID
	ClaimToken    *uuid.UUID
}

func (q *Queries) CompleteCronTriggerFiring(ctx context.Context, arg CompleteCronTriggerFiringParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCronTriggerFiring,
		arg.Fired,
		arg.NextFireAfter,
		arg.ProjectID,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveCronTriggersForProject = `-- name: CountActiveCronTriggersForProject :one
SELECT count(*) AS active_count
FROM cron_triggers trigger
WHERE trigger.project_id = $1
  AND trigger.deleted_at IS NULL
`

type CountActiveCronTriggersForProjectParams struct {
	ProjectID uuid.UUID
}

func (q *Queries) CountActiveCronTriggersForProject(ctx context.Context, arg CountActiveCronTriggersForProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCronTriggersForProject, arg.ProjectID)
	var active_count int64
	err := row.Scan(&active_count)
	return active_count, err
}

const cronTriggerClaimIsLive = `-- name: CronTriggerClaimIsLive :one
SELECT EXISTS (
    SELECT 1 FROM cron_triggers
    WHERE project_id = $1 AND id = $2
      AND claim_token = $3 AND claimed_until > statement_timestamp()
      AND deleted_at IS NULL
)::boolean AS live
`

type CronTriggerClaimIsLiveParams struct {
	ProjectID  uuid.UUID
	ID         uuid.UUID
	ClaimToken *uuid.UUID
}

// Use a fresh statement after locking: statement_timestamp() does not advance during lock waits.
func (q *Queries) CronTriggerClaimIsLive(ctx context.Context, arg CronTriggerClaimIsLiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, cronTriggerClaimIsLive, arg.ProjectID, arg.ID, arg.ClaimToken)
	var live bool
	err := row.Scan(&live)
	return live, err
}

const deleteCronTrigger = `-- name: DeleteCronTrigger :execrows
UPDATE cron_triggers
SET deleted_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type DeleteCronTriggerParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteCronTrigger(ctx context.Context, arg DeleteCronTriggerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCronTrigger, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCronTriggersForAgent = `-- name: DeleteCronTriggersForAgent :execrows
UPDATE cron_triggers
SET deleted_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE project_id = $1
  AND agent_id = $2
  AND deleted_at IS NULL
`

type DeleteCronTriggersForAgentParams struct {
	ProjectID uuid.UUID
	AgentID   *uuid.UUID
}

func (q *Queries) DeleteCronTriggersForAgent(ctx context.Context, arg DeleteCronTriggersForAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCronTriggersForAgent, arg.ProjectID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCronTriggersForAgentProfile = `-- name: DeleteCronTriggersForAgentProfile :execrows
UPDATE cron_triggers
SET deleted_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE project_id = $1
  AND agent_profile_id = $2
  AND deleted_at IS NULL
`

type DeleteCronTriggersForAgentProfileParams struct {
	ProjectID      uuid.UUID
	AgentProfileID *uuid.UUID
}

func (q *Queries) DeleteCronTriggersForAgentProfile(ctx context.Context, arg DeleteCronTriggersForAgentProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCronTriggersForAgentProfile, arg.ProjectID, arg.AgentProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCronTriggersForIntegration = `-- name: DeleteCronTriggersForIntegration :execrows
UPDATE cron_triggers
SET deleted_at = statement_timestamp(), updated_at = statement_timestamp()
WHERE project_id = $1 AND integration_id = $2 AND deleted_at IS NULL
`

type DeleteCronTriggersForIntegrationParams struct {
	ProjectID     uuid.UUID
	IntegrationID *uuid.UUID
}

func (q *Queries) DeleteCronTriggersForIntegration(ctx context.Context, arg DeleteCronTriggersForIntegrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCronTriggersForIntegration, arg.ProjectID, arg.IntegrationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableCronTrigger = `-- name: DisableCronTrigger :execrows
UPDATE cron_triggers
SET enabled = false,
    next_fire_after = NULL,
    claimed_until = NULL,
    claim_token = NULL,
    failure_report = jsonb_build_object(
        'message', $1::text,
        'will_retry', false,
        'failed_at', to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
    ),
    updated_at = statement_timestamp()
WHERE project_id = $2
  AND id = $3
  AND deleted_at IS NULL
`

type DisableCronTriggerParams struct {
	FailureMessage string
	ProjectID      uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) DisableCronTrigger(ctx context.Context, arg DisableCronTriggerParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableCronTrigger, arg.FailureMessage, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCronTrigger = `-- name: GetCronTrigger :one
SELECT trigger.id, project.org_id, trigger.project_id, trigger.name,
       trigger.agent_profile_id, trigger.agent_id,
       trigger.integration_id, trigger.integration_settings,
       trigger.cron_expression, trigger.timezone, coalesce(trigger.message_template, '')::text AS message_template,
       trigger.delivery_mode, trigger.enabled, trigger.last_fired_at, trigger.next_fire_after,
       trigger.failure_report,
       CASE WHEN receipt.id IS NOT NULL THEN jsonb_build_object(
           'state', CASE receipt.state WHEN 'pending' THEN 'queued' ELSE receipt.state END,
           'created_at', receipt.created_at, 'updated_at', receipt.updated_at,
           'failure_message', CASE WHEN receipt.state = 'failed' THEN 'Scheduled integration action failed.' ELSE NULL END
       ) END::jsonb AS last_run,
       coalesce(trigger.idempotency_key, '') AS idempotency_key,
       trigger.created_at, trigger.updated_at
FROM cron_triggers trigger
JOIN projects project ON project.id = trigger.project_id
LEFT JOIN integration_inbox receipt ON receipt.id = trigger.last_integration_receipt_id
    AND receipt.project_id = trigger.project_id AND receipt.integration_id = trigger.integration_id
    AND receipt.source = 'scheduled'
WHERE trigger.project_id = $1
  AND trigger.id = $2
  AND trigger.deleted_at IS NULL
`

type GetCronTriggerParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

type GetCronTriggerRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	Name                string
	AgentProfileID      *uuid.UUID
	AgentID             *uuid.UUID
	IntegrationID       *uuid.UUID
	IntegrationSettings *json.RawMessage
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	DeliveryMode        string
	Enabled             bool
	LastFiredAt         *time.Time
	NextFireAfter       *time.Time
	FailureReport       *json.RawMessage
	LastRun             json.RawMessage
	IdempotencyKey      string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetCronTrigger(ctx context.Context, arg GetCronTriggerParams) (GetCronTriggerRow, error) {
	row := q.db.QueryRow(ctx, getCronTrigger, arg.ProjectID, arg.ID)
	var i GetCronTriggerRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.AgentProfileID,
		&i.AgentID,
		&i.IntegrationID,
		&i.IntegrationSettings,
		&i.CronExpression,
		&i.Timezone,
		&i.MessageTemplate,
		&i.DeliveryMode,
		&i.Enabled,
		&i.LastFiredAt,
		&i.NextFireAfter,
		&i.FailureReport,
		&i.LastRun,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCronTriggerByIdempotencyKey = `-- name: GetCronTriggerByIdempotencyKey :one
SELECT trigger.id, project.org_id, trigger.project_id, trigger.name,
       trigger.agent_profile_id, trigger.agent_id,
       trigger.integration_id, trigger.integration_settings,
       trigger.cron_expression, trigger.timezone, coalesce(trigger.message_template, '')::text AS message_template,
       trigger.delivery_mode, trigger.enabled, trigger.last_fired_at, trigger.next_fire_after,
       trigger.failure_report,
       CASE WHEN receipt.id IS NOT NULL THEN jsonb_build_object(
           'state', CASE receipt.state WHEN 'pending' THEN 'queued' ELSE receipt.state END,
           'created_at', receipt.created_at, 'updated_at', receipt.updated_at,
           'failure_message', CASE WHEN receipt.state = 'failed' THEN 'Scheduled integration action failed.' ELSE NULL END
       ) END::jsonb AS last_run,
       coalesce(trigger.idempotency_key, '') AS idempotency_key,
       trigger.created_at, trigger.updated_at
FROM cron_triggers trigger
JOIN projects project ON project.id = trigger.project_id
LEFT JOIN integration_inbox receipt ON receipt.id = trigger.last_integration_receipt_id
    AND receipt.project_id = trigger.project_id AND receipt.integration_id = trigger.integration_id
    AND receipt.source = 'scheduled'
WHERE trigger.project_id = $1
  AND trigger.idempotency_key = $2::text
  AND trigger.deleted_at IS NULL
`

type GetCronTriggerByIdempotencyKeyParams struct {
	ProjectID      uuid.UUID
	IdempotencyKey string
}

type GetCronTriggerByIdempotencyKeyRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	Name                string
	AgentProfileID      *uuid.UUID
	AgentID             *uuid.UUID
	IntegrationID       *uuid.UUID
	IntegrationSettings *json.RawMessage
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	DeliveryMode        string
	Enabled             bool
	LastFiredAt         *time.Time
	NextFireAfter       *time.Time
	FailureReport       *json.RawMessage
	LastRun             json.RawMessage
	IdempotencyKey      string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetCronTriggerByIdempotencyKey(ctx context.Context, arg GetCronTriggerByIdempotencyKeyParams) (GetCronTriggerByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getCronTriggerByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i GetCronTriggerByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.AgentProfileID,
		&i.AgentID,
		&i.IntegrationID,
		&i.IntegrationSettings,
		&i.CronExpression,
		&i.Timezone,
		&i.MessageTemplate,
		&i.DeliveryMode,
		&i.Enabled,
		&i.LastFiredAt,
		&i.NextFireAfter,
		&i.FailureReport,
		&i.LastRun,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCronTriggerForUpdate = `-- name: GetCronTriggerForUpdate :one
SELECT trigger.id, project.org_id, trigger.project_id, trigger.name,
       trigger.agent_profile_id, trigger.agent_id,
       trigger.integration_id, trigger.integration_settings,
       trigger.cron_expression, trigger.timezone, coalesce(trigger.message_template, '')::text AS message_template,
       trigger.delivery_mode, trigger.enabled, trigger.last_fired_at, trigger.next_fire_after,
       trigger.failure_report,
       CASE WHEN receipt.id IS NOT NULL THEN jsonb_build_object(
           'state', CASE receipt.state WHEN 'pending' THEN 'queued' ELSE receipt.state END,
           'created_at', receipt.created_at, 'updated_at', receipt.updated_at,
           'failure_message', CASE WHEN receipt.state = 'failed' THEN 'Scheduled integration action failed.' ELSE NULL END
       ) END::jsonb AS last_run,
       coalesce(trigger.idempotency_key, '') AS idempotency_key,
       trigger.created_at, trigger.updated_at
FROM cron_triggers trigger
JOIN projects project ON project.id = trigger.project_id
LEFT JOIN integration_inbox receipt ON receipt.id = trigger.last_integration_receipt_id
    AND receipt.project_id = trigger.project_id AND receipt.integration_id = trigger.integration_id
    AND receipt.source = 'scheduled'
WHERE trigger.project_id = $1
  AND trigger.id = $2
  AND trigger.deleted_at IS NULL
FOR UPDATE OF trigger
`

type GetCronTriggerForUpdateParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

type GetCronTriggerForUpdateRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	Name                string
	AgentProfileID      *uuid.UUID
	AgentID             *uuid.UUID
	IntegrationID       *uuid.UUID
	IntegrationSettings *json.RawMessage
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	DeliveryMode        string
	Enabled             bool
	LastFiredAt         *time.Time
	NextFireAfter       *time.Time
	FailureReport       *json.RawMessage
	LastRun             json.RawMessage
	IdempotencyKey      string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetCronTriggerForUpdate(ctx context.Context, arg GetCronTriggerForUpdateParams) (GetCronTriggerForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCronTriggerForUpdate, arg.ProjectID, arg.ID)
	var i GetCronTriggerForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.AgentProfileID,
		&i.AgentID,
		&i.IntegrationID,
		&i.IntegrationSettings,
		&i.CronExpression,
		&i.Timezone,
		&i.MessageTemplate,
		&i.DeliveryMode,
		&i.Enabled,
		&i.LastFiredAt,
		&i.NextFireAfter,
		&i.FailureReport,
		&i.LastRun,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCronTrigger = `-- name: InsertCronTrigger :one
INSERT INTO cron_triggers(
    id, project_id, name, agent_profile_id, agent_id,
    integration_id, integration_settings,
    cron_expression, timezone, message_template, delivery_mode, enabled,
    next_fire_after, idempotency_key, created_at, updated_at
)
VALUES (
    uuidv7(), $1, $2,
    $3, $4,
    $5, $6,
    $7, $8, NULLIF($9::text, ''),
    $10, $11, $12,
    $13, transaction_timestamp(), transaction_timestamp()
)
ON CONFLICT (project_id, idempotency_key) DO NOTHING
RETURNING id, project_id, name, agent_profile_id, agent_id,
          integration_id, integration_settings,
          cron_expression, timezone, coalesce(message_template, '')::text AS message_template, delivery_mode, enabled,
          last_fired_at, next_fire_after, failure_report,
          coalesce(idempotency_key, '') AS idempotency_key,
          created_at, updated_at
`

type InsertCronTriggerParams struct {
	ProjectID           uuid.UUID
	Name                string
	AgentProfileID      *uuid.UUID
	AgentID             *uuid.UUID
	IntegrationID       *uuid.UUID
	IntegrationSettings *json.RawMessage
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	DeliveryMode        string
	Enabled             bool
	NextFireAfter       *time.Time
	IdempotencyKey      *string
}

type InsertCronTriggerRow struct {
	ID                  uuid.UUID
	ProjectID           uuid.UUID
	Name                string
	AgentProfileID      *uuid.UUID
	AgentID             *uuid.UUID
	IntegrationID       *uuid.UUID
	IntegrationSettings *json.RawMessage
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	DeliveryMode        string
	Enabled             bool
	LastFiredAt         *time.Time
	NextFireAfter       *time.Time
	FailureReport       *json.RawMessage
	IdempotencyKey      string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) InsertCronTrigger(ctx context.Context, arg InsertCronTriggerParams) (InsertCronTriggerRow, error) {
	row := q.db.QueryRow(ctx, insertCronTrigger,
		arg.ProjectID,
		arg.Name,
		arg.AgentProfileID,
		arg.AgentID,
		arg.IntegrationID,
		arg.IntegrationSettings,
		arg.CronExpression,
		arg.Timezone,
		arg.MessageTemplate,
		arg.DeliveryMode,
		arg.Enabled,
		arg.NextFireAfter,
		arg.IdempotencyKey,
	)
	var i InsertCronTriggerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.AgentProfileID,
		&i.AgentID,
		&i.IntegrationID,
		&i.IntegrationSettings,
		&i.CronExpression,
		&i.Timezone,
		&i.MessageTemplate,
		&i.DeliveryMode,
		&i.Enabled,
		&i.LastFiredAt,
		&i.NextFireAfter,
		&i.FailureReport,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCronTriggersForProject = `-- name: ListCronTriggersForProject :many
WITH listed AS (
SELECT trigger.id, project.org_id, trigger.project_id, trigger.name,
       trigger.agent_profile_id, trigger.agent_id,
       trigger.integration_id, trigger.integration_settings,
       trigger.cron_expression, trigger.timezone, coalesce(trigger.message_template, '')::text AS message_template,
       trigger.delivery_mode, trigger.enabled, trigger.last_fired_at, trigger.next_fire_after,
       trigger.failure_report,
       CASE WHEN receipt.id IS NOT NULL THEN jsonb_build_object(
           'state', CASE receipt.state WHEN 'pending' THEN 'queued' ELSE receipt.state END,
           'created_at', receipt.created_at, 'updated_at', receipt.updated_at,
           'failure_message', CASE WHEN receipt.state = 'failed' THEN 'Scheduled integration action failed.' ELSE NULL END
       ) END::jsonb AS last_run,
       coalesce(trigger.idempotency_key, '') AS idempotency_key,
       trigger.created_at, trigger.updated_at,
       CASE $6::text
         WHEN 'name' THEN lower(trigger.name)
         WHEN 'created_at' THEN to_char(trigger.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
         WHEN 'updated_at' THEN to_char(trigger.updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
       END::text AS sort_key,
       false AS sort_is_null
FROM cron_triggers trigger
JOIN projects project ON project.id = trigger.project_id
LEFT JOIN integration_inbox receipt ON receipt.id = trigger.last_integration_receipt_id
    AND receipt.project_id = trigger.project_id AND receipt.integration_id = trigger.integration_id
    AND receipt.source = 'scheduled'
WHERE trigger.project_id = $7
  AND trigger.deleted_at IS NULL
  AND ($8::text = '' OR trigger.name ILIKE $8::text ESCAPE '\')
  AND ($9::uuid IS NULL OR trigger.agent_profile_id = $9::uuid)
  AND ($10::uuid IS NULL OR trigger.agent_id = $10::uuid)
  AND ($11::uuid IS NULL OR trigger.integration_id = $11::uuid)
)
SELECT id, org_id, project_id, name, agent_profile_id, agent_id,
       integration_id, integration_settings, last_run,
       cron_expression, timezone, message_template, delivery_mode, enabled,
       last_fired_at, next_fire_after, failure_report, idempotency_key,
       created_at, updated_at, sort_key, sort_is_null
FROM listed
WHERE $1::boolean = false
   OR ($2::boolean = false AND (sort_key, id) > ($3::text, $4::uuid))
   OR ($2::boolean = true AND (sort_key, id) < ($3::text, $4::uuid))
ORDER BY CASE WHEN $2::boolean = false THEN sort_key END ASC,
         CASE WHEN $2::boolean = true THEN sort_key END DESC,
         CASE WHEN $2::boolean = false THEN id END ASC,
         CASE WHEN $2::boolean = true THEN id END DESC
LIMIT $5::bigint
`

type ListCronTriggersForProjectParams struct {
	CursorSet      bool
	SortDesc       bool
	CursorKey      string
	CursorID       uuid.UUID
	RowLimit       int64
	SortField      string
	ProjectID      uuid.UUID
	NamePattern    string
	AgentProfileID *uuid.UUID
	AgentID        *uuid.UUID
	IntegrationID  *uuid.UUID
}

type ListCronTriggersForProjectRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	Name                string
	AgentProfileID      *uuid.UUID
	AgentID             *uuid.UUID
	IntegrationID       *uuid.UUID
	IntegrationSettings *json.RawMessage
	LastRun             json.RawMessage
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	DeliveryMode        string
	Enabled             bool
	LastFiredAt         *time.Time
	NextFireAfter       *time.Time
	FailureReport       *json.RawMessage
	IdempotencyKey      string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SortKey             string
	SortIsNull          bool
}

func (q *Queries) ListCronTriggersForProject(ctx context.Context, arg ListCronTriggersForProjectParams) ([]ListCronTriggersForProjectRow, error) {
	rows, err := q.db.Query(ctx, listCronTriggersForProject,
		arg.CursorSet,
		arg.SortDesc,
		arg.CursorKey,
		arg.CursorID,
		arg.RowLimit,
		arg.SortField,
		arg.ProjectID,
		arg.NamePattern,
		arg.AgentProfileID,
		arg.AgentID,
		arg.IntegrationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCronTriggersForProjectRow{}
	for rows.Next() {
		var i ListCronTriggersForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.AgentProfileID,
			&i.AgentID,
			&i.IntegrationID,
			&i.IntegrationSettings,
			&i.LastRun,
			&i.CronExpression,
			&i.Timezone,
			&i.MessageTemplate,
			&i.DeliveryMode,
			&i.Enabled,
			&i.LastFiredAt,
			&i.NextFireAfter,
			&i.FailureReport,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortKey,
			&i.SortIsNull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCronTriggerFailure = `-- name: RecordCronTriggerFailure :execrows
UPDATE cron_triggers
SET failure_report = jsonb_build_object(
        'message', $1::text,
        'will_retry', $2::boolean,
        'failed_at', to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
    ),
    updated_at = statement_timestamp()
WHERE project_id = $3
  AND id = $4
  AND claim_token = $5
  AND deleted_at IS NULL
`

type RecordCronTriggerFailureParams struct {
	FailureMessage string
	WillRetry      bool
	ProjectID      uuid.UUID
	ID             uuid.UUID
	ClaimToken     *uuid.UUID
}

func (q *Queries) RecordCronTriggerFailure(ctx context.Context, arg RecordCronTriggerFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordCronTriggerFailure,
		arg.FailureMessage,
		arg.WillRetry,
		arg.ProjectID,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseCronTriggerClaim = `-- name: ReleaseCronTriggerClaim :execrows
UPDATE cron_triggers
SET claimed_until = NULL, claim_token = NULL, updated_at = statement_timestamp()
WHERE project_id = $1 AND id = $2
  AND claim_token = $3 AND deleted_at IS NULL
`

type ReleaseCronTriggerClaimParams struct {
	ProjectID  uuid.UUID
	ID         uuid.UUID
	ClaimToken *uuid.UUID
}

func (q *Queries) ReleaseCronTriggerClaim(ctx context.Context, arg ReleaseCronTriggerClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseCronTriggerClaim, arg.ProjectID, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectDueCronTriggers = `-- name: SelectDueCronTriggers :many
SELECT trigger.id, project.org_id, trigger.project_id, trigger.name,
       trigger.agent_profile_id, trigger.agent_id,
       trigger.integration_id, trigger.integration_settings,
       trigger.cron_expression, trigger.timezone, coalesce(trigger.message_template, '')::text AS message_template,
       trigger.delivery_mode, trigger.last_fired_at, trigger.next_fire_after
FROM cron_triggers trigger
JOIN projects project ON project.id = trigger.project_id AND project.deleted_at IS NULL
WHERE trigger.enabled
  AND trigger.deleted_at IS NULL
  AND trigger.next_fire_after <= transaction_timestamp()
  AND (trigger.claimed_until IS NULL OR trigger.claimed_until < transaction_timestamp())
ORDER BY trigger.next_fire_after ASC, trigger.id ASC
LIMIT $1::bigint
FOR UPDATE OF trigger SKIP LOCKED
`

type SelectDueCronTriggersParams struct {
	RowLimit int64
}

type SelectDueCronTriggersRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	Name                string
	AgentProfileID      *uuid.UUID
	AgentID             *uuid.UUID
	IntegrationID       *uuid.UUID
	IntegrationSettings *json.RawMessage
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	DeliveryMode        string
	LastFiredAt         *time.Time
	NextFireAfter       *time.Time
}

func (q *Queries) SelectDueCronTriggers(ctx context.Context, arg SelectDueCronTriggersParams) ([]SelectDueCronTriggersRow, error) {
	rows, err := q.db.Query(ctx, selectDueCronTriggers, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectDueCronTriggersRow{}
	for rows.Next() {
		var i SelectDueCronTriggersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.AgentProfileID,
			&i.AgentID,
			&i.IntegrationID,
			&i.IntegrationSettings,
			&i.CronExpression,
			&i.Timezone,
			&i.MessageTemplate,
			&i.DeliveryMode,
			&i.LastFiredAt,
			&i.NextFireAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCronTriggerIntegrationReceipt = `-- name: SetCronTriggerIntegrationReceipt :execrows
UPDATE cron_triggers
SET last_integration_receipt_id = $1, updated_at = statement_timestamp()
WHERE project_id = $2 AND id = $3
  AND claim_token = $4 AND claimed_until > statement_timestamp() AND deleted_at IS NULL
`

type SetCronTriggerIntegrationReceiptParams struct {
	ReceiptID  *uuid.UUID
	ProjectID  uuid.UUID
	ID         uuid.UUID
	ClaimToken *uuid.UUID
}

func (q *Queries) SetCronTriggerIntegrationReceipt(ctx context.Context, arg SetCronTriggerIntegrationReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCronTriggerIntegrationReceipt,
		arg.ReceiptID,
		arg.ProjectID,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCronTrigger = `-- name: UpdateCronTrigger :one
UPDATE cron_triggers
SET name = $1,
    cron_expression = $2,
    timezone = $3,
    message_template = NULLIF($4::text, ''),
    integration_settings = $5,
    delivery_mode = $6,
    enabled = $7,
    next_fire_after = $8,
    updated_at = statement_timestamp()
WHERE project_id = $9
  AND id = $10
  AND deleted_at IS NULL
RETURNING id, project_id, name, agent_profile_id, agent_id,
          integration_id, integration_settings,
          cron_expression, timezone, coalesce(message_template, '')::text AS message_template, delivery_mode, enabled,
          last_fired_at, next_fire_after, failure_report,
          coalesce(idempotency_key, '') AS idempotency_key,
          created_at, updated_at
`

type UpdateCronTriggerParams struct {
	Name                string
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	IntegrationSettings *json.RawMessage
	DeliveryMode        string
	Enabled             bool
	NextFireAfter       *time.Time
	ProjectID           uuid.UUID
	ID                  uuid.UUID
}

type UpdateCronTriggerRow struct {
	ID                  uuid.UUID
	ProjectID           uuid.UUID
	Name                string
	AgentProfileID      *uuid.UUID
	AgentID             *uuid.UUID
	IntegrationID       *uuid.UUID
	IntegrationSettings *json.RawMessage
	CronExpression      string
	Timezone            string
	MessageTemplate     string
	DeliveryMode        string
	Enabled             bool
	LastFiredAt         *time.Time
	NextFireAfter       *time.Time
	FailureReport       *json.RawMessage
	IdempotencyKey      string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) UpdateCronTrigger(ctx context.Context, arg UpdateCronTriggerParams) (UpdateCronTriggerRow, error) {
	row := q.db.QueryRow(ctx, updateCronTrigger,
		arg.Name,
		arg.CronExpression,
		arg.Timezone,
		arg.MessageTemplate,
		arg.IntegrationSettings,
		arg.DeliveryMode,
		arg.Enabled,
		arg.NextFireAfter,
		arg.ProjectID,
		arg.ID,
	)
	var i UpdateCronTriggerRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.AgentProfileID,
		&i.AgentID,
		&i.IntegrationID,
		&i.IntegrationSettings,
		&i.CronExpression,
		&i.Timezone,
		&i.MessageTemplate,
		&i.DeliveryMode,
		&i.Enabled,
		&i.LastFiredAt,
		&i.NextFireAfter,
		&i.FailureReport,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
