// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const configureIntegration = `-- name: ConfigureIntegration :one
UPDATE integrations
SET installed_by_user_id = $1,
    provider_tenant_id = $2,
    provider_account_ref = $3,
    provider_agent_display_name = $4,
    credential_secret_id = $5::uuid,
    provider_config = $6, provider_identity = $7,
    provider_metadata = $8,
    last_oauth_flow_id = coalesce($9::uuid, last_oauth_flow_id),
    state = 'active', setup_revision = setup_revision + 1, updated_at = statement_timestamp()
WHERE project_id = $10 AND id = $11 AND deleted_at IS NULL
  AND setup_revision = $12
RETURNING id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_kind, settings, setup_revision
`

type ConfigureIntegrationParams struct {
	InstalledByUserID        *uuid.UUID
	ProviderTenantID         *string
	ProviderAccountRef       *string
	ProviderAgentDisplayName string
	CredentialSecretID       uuid.UUID
	ProviderConfig           json.RawMessage
	ProviderIdentity         json.RawMessage
	ProviderMetadata         json.RawMessage
	OauthFlowID              *uuid.UUID
	ProjectID                uuid.UUID
	ID                       uuid.UUID
	ExpectedSetupRevision    int64
}

func (q *Queries) ConfigureIntegration(ctx context.Context, arg ConfigureIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, configureIntegration,
		arg.InstalledByUserID,
		arg.ProviderTenantID,
		arg.ProviderAccountRef,
		arg.ProviderAgentDisplayName,
		arg.CredentialSecretID,
		arg.ProviderConfig,
		arg.ProviderIdentity,
		arg.ProviderMetadata,
		arg.OauthFlowID,
		arg.ProjectID,
		arg.ID,
		arg.ExpectedSetupRevision,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationKind,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const countIntegrations = `-- name: CountIntegrations :one
SELECT count(*)::bigint FROM integrations WHERE project_id = $1 AND deleted_at IS NULL
`

type CountIntegrationsParams struct {
	ProjectID uuid.UUID
}

func (q *Queries) CountIntegrations(ctx context.Context, arg CountIntegrationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIntegrations, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteIntegration = `-- name: DeleteIntegration :execrows
UPDATE integrations
SET state = 'disconnected', credential_secret_id = NULL, deleted_at = statement_timestamp(),
    setup_revision = setup_revision + 1, updated_at = statement_timestamp()
WHERE project_id = $1 AND id = $2 AND deleted_at IS NULL
`

type DeleteIntegrationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntegration, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIntegrationsForProjectDeletion = `-- name: DeleteIntegrationsForProjectDeletion :exec
UPDATE integrations
SET state = 'disconnected', credential_secret_id = NULL, deleted_at = statement_timestamp(),
    setup_revision = setup_revision + 1, updated_at = statement_timestamp()
WHERE project_id = $1 AND deleted_at IS NULL
`

type DeleteIntegrationsForProjectDeletionParams struct {
	ProjectID uuid.UUID
}

func (q *Queries) DeleteIntegrationsForProjectDeletion(ctx context.Context, arg DeleteIntegrationsForProjectDeletionParams) error {
	_, err := q.db.Exec(ctx, deleteIntegrationsForProjectDeletion, arg.ProjectID)
	return err
}

const disconnectIntegration = `-- name: DisconnectIntegration :execrows
UPDATE integrations
SET state = 'disconnected', setup_revision = setup_revision + 1, updated_at = statement_timestamp()
WHERE project_id = $1 AND id = $2
  AND deleted_at IS NULL
  AND ($3::bigint IS NULL OR setup_revision = $3)
`

type DisconnectIntegrationParams struct {
	ProjectID             uuid.UUID
	ID                    uuid.UUID
	ExpectedSetupRevision *int64
}

func (q *Queries) DisconnectIntegration(ctx context.Context, arg DisconnectIntegrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, disconnectIntegration, arg.ProjectID, arg.ID, arg.ExpectedSetupRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_kind, settings, setup_revision
FROM integrations
WHERE project_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetIntegrationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, arg.ProjectID, arg.ID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationKind,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_kind, settings, setup_revision
FROM integrations WHERE id = $1 AND deleted_at IS NULL
`

type GetIntegrationByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetIntegrationByID(ctx context.Context, arg GetIntegrationByIDParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, arg.ID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationKind,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const getIntegrationByName = `-- name: GetIntegrationByName :one
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_kind, settings, setup_revision
FROM integrations
WHERE project_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetIntegrationByNameParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) GetIntegrationByName(ctx context.Context, arg GetIntegrationByNameParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByName, arg.ProjectID, arg.Name)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationKind,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const insertIntegration = `-- name: InsertIntegration :one
INSERT INTO integrations(org_id, project_id, name, integration_kind, settings, state, created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5, 'disconnected', statement_timestamp(), statement_timestamp())
RETURNING id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_kind, settings, setup_revision
`

type InsertIntegrationParams struct {
	OrgID           uuid.UUID
	ProjectID       uuid.UUID
	Name            string
	IntegrationKind string
	Settings        json.RawMessage
}

func (q *Queries) InsertIntegration(ctx context.Context, arg InsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, insertIntegration,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.IntegrationKind,
		arg.Settings,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationKind,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const integrationOAuthFlowConsumed = `-- name: IntegrationOAuthFlowConsumed :one
SELECT EXISTS (SELECT 1 FROM integrations WHERE last_oauth_flow_id = $1) AS consumed
`

type IntegrationOAuthFlowConsumedParams struct {
	FlowID *uuid.UUID
}

// @sqlc-vet-disable integrations-deleted-at
func (q *Queries) IntegrationOAuthFlowConsumed(ctx context.Context, arg IntegrationOAuthFlowConsumedParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationOAuthFlowConsumed, arg.FlowID)
	var consumed bool
	err := row.Scan(&consumed)
	return consumed, err
}

const listIntegrationMetadataByIDs = `-- name: ListIntegrationMetadataByIDs :many
SELECT id, project_id, name, integration_kind, state, deleted_at
FROM integrations
WHERE project_id = $1 AND id = ANY($2::uuid[])
ORDER BY id
`

type ListIntegrationMetadataByIDsParams struct {
	ProjectID uuid.UUID
	Ids       []uuid.UUID
}

type ListIntegrationMetadataByIDsRow struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	Name            string
	IntegrationKind string
	State           string
	DeletedAt       *time.Time
}

func (q *Queries) ListIntegrationMetadataByIDs(ctx context.Context, arg ListIntegrationMetadataByIDsParams) ([]ListIntegrationMetadataByIDsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationMetadataByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationMetadataByIDsRow{}
	for rows.Next() {
		var i ListIntegrationMetadataByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IntegrationKind,
			&i.State,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_kind, settings, setup_revision
FROM integrations
WHERE project_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE $2::text ESCAPE '\')
  AND (NOT $3::boolean OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListIntegrationsParams struct {
	ProjectID       uuid.UUID
	NamePattern     string
	CursorSet       bool
	CursorCreatedAt time.Time
	CursorID        uuid.UUID
	RowLimit        int32
}

func (q *Queries) ListIntegrations(ctx context.Context, arg ListIntegrationsParams) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations,
		arg.ProjectID,
		arg.NamePattern,
		arg.CursorSet,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.InstalledByUserID,
			&i.State,
			&i.ProviderTenantID,
			&i.ProviderAccountRef,
			&i.ProviderAgentDisplayName,
			&i.CredentialSecretID,
			&i.ProviderConfig,
			&i.ProviderIdentity,
			&i.ProviderMetadata,
			&i.LastOauthFlowID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.IntegrationKind,
			&i.Settings,
			&i.SetupRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsByProviderIdentity = `-- name: ListIntegrationsByProviderIdentity :many
SELECT integration.id, integration.org_id, integration.project_id, integration.installed_by_user_id, integration.state, integration.provider_tenant_id, integration.provider_account_ref, integration.provider_agent_display_name, integration.credential_secret_id, integration.provider_config, integration.provider_identity, integration.provider_metadata, integration.last_oauth_flow_id, integration.deleted_at, integration.created_at, integration.updated_at, integration.name, integration.integration_kind, integration.settings, integration.setup_revision
FROM integrations integration
JOIN projects project ON project.id = integration.project_id
JOIN orgs org ON org.id = integration.org_id
WHERE integration.integration_kind = ANY($1::text[]) AND integration.provider_tenant_id = $2
  AND ($3::text IS NULL OR integration.provider_account_ref = $3::text)
  AND (integration.state = 'active' OR ($4::boolean
    AND integration.state = 'disconnected' AND integration.credential_secret_id IS NOT NULL))
  AND integration.deleted_at IS NULL
  AND project.deleted_at IS NULL AND org.deleted_at IS NULL
  AND ($5::uuid IS NULL OR integration.id > $5::uuid)
ORDER BY integration.id LIMIT $6
`

type ListIntegrationsByProviderIdentityParams struct {
	IntegrationKinds    []string
	ProviderTenantID    *string
	ProviderAccountRef  *string
	IncludeDisconnected bool
	AfterID             *uuid.UUID
	RowLimit            int32
}

func (q *Queries) ListIntegrationsByProviderIdentity(ctx context.Context, arg ListIntegrationsByProviderIdentityParams) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByProviderIdentity,
		arg.IntegrationKinds,
		arg.ProviderTenantID,
		arg.ProviderAccountRef,
		arg.IncludeDisconnected,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.InstalledByUserID,
			&i.State,
			&i.ProviderTenantID,
			&i.ProviderAccountRef,
			&i.ProviderAgentDisplayName,
			&i.CredentialSecretID,
			&i.ProviderConfig,
			&i.ProviderIdentity,
			&i.ProviderMetadata,
			&i.LastOauthFlowID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.IntegrationKind,
			&i.Settings,
			&i.SetupRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIntegration = `-- name: LockIntegration :one
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_kind, settings, setup_revision
FROM integrations
WHERE project_id = $1 AND id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type LockIntegrationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) LockIntegration(ctx context.Context, arg LockIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, lockIntegration, arg.ProjectID, arg.ID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationKind,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const lockIntegrationLifecycleExclusive = `-- name: LockIntegrationLifecycleExclusive :exec
SELECT pg_advisory_xact_lock(hashtextextended('integration:' || $1::uuid::text, 0))
`

type LockIntegrationLifecycleExclusiveParams struct {
	IntegrationID uuid.UUID
}

func (q *Queries) LockIntegrationLifecycleExclusive(ctx context.Context, arg LockIntegrationLifecycleExclusiveParams) error {
	_, err := q.db.Exec(ctx, lockIntegrationLifecycleExclusive, arg.IntegrationID)
	return err
}

const lockIntegrationLifecycleShared = `-- name: LockIntegrationLifecycleShared :exec
SELECT pg_advisory_xact_lock_shared(hashtextextended('integration:' || $1::uuid::text, 0))
`

type LockIntegrationLifecycleSharedParams struct {
	IntegrationID uuid.UUID
}

func (q *Queries) LockIntegrationLifecycleShared(ctx context.Context, arg LockIntegrationLifecycleSharedParams) error {
	_, err := q.db.Exec(ctx, lockIntegrationLifecycleShared, arg.IntegrationID)
	return err
}

const updateIntegrationSettings = `-- name: UpdateIntegrationSettings :one
UPDATE integrations SET settings = $1, updated_at = statement_timestamp()
WHERE project_id = $2 AND id = $3 AND deleted_at IS NULL
RETURNING id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_kind, settings, setup_revision
`

type UpdateIntegrationSettingsParams struct {
	Settings  json.RawMessage
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) UpdateIntegrationSettings(ctx context.Context, arg UpdateIntegrationSettingsParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegrationSettings, arg.Settings, arg.ProjectID, arg.ID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationKind,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}
