// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const clearDeletedIntegrationTargetsFromAgents = `-- name: ClearDeletedIntegrationTargetsFromAgents :exec
UPDATE agents agent SET integration_target_id = NULL, updated_at = statement_timestamp()
WHERE agent.project_id = $1
  AND agent.integration_target_id IN (
    SELECT target.id FROM integration_targets target
    WHERE target.project_id = $1
      AND target.integration_install_id = $2
  )
`

type ClearDeletedIntegrationTargetsFromAgentsParams struct {
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
}

// @sqlc-vet-disable integration-targets-deleted-at
// Clears agent references to targets that were just soft deleted.
func (q *Queries) ClearDeletedIntegrationTargetsFromAgents(ctx context.Context, arg ClearDeletedIntegrationTargetsFromAgentsParams) error {
	_, err := q.db.Exec(ctx, clearDeletedIntegrationTargetsFromAgents, arg.ProjectID, arg.IntegrationInstallID)
	return err
}

const deleteIntegrationInstall = `-- name: DeleteIntegrationInstall :execrows
UPDATE integration_installs
SET credential_secret_id = NULL, deleted_at = statement_timestamp(), updated_at = statement_timestamp()
WHERE project_id = $1 AND id = $2 AND deleted_at IS NULL
`

type DeleteIntegrationInstallParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

// Clearing the credential releases the secret for deletion; the install
// keeps whatever active/disabled state it had as provenance.
func (q *Queries) DeleteIntegrationInstall(ctx context.Context, arg DeleteIntegrationInstallParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntegrationInstall, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIntegrationTargets = `-- name: DeleteIntegrationTargets :exec
UPDATE integration_targets SET deleted_at = statement_timestamp(), updated_at = statement_timestamp()
WHERE project_id = $1 AND integration_install_id = $2
  AND deleted_at IS NULL
`

type DeleteIntegrationTargetsParams struct {
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
}

func (q *Queries) DeleteIntegrationTargets(ctx context.Context, arg DeleteIntegrationTargetsParams) error {
	_, err := q.db.Exec(ctx, deleteIntegrationTargets, arg.ProjectID, arg.IntegrationInstallID)
	return err
}

const disableIntegrationInstall = `-- name: DisableIntegrationInstall :execrows
UPDATE integration_installs
SET state = 'disabled',
    updated_at = statement_timestamp()
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
  AND state = 'active'
  AND last_oauth_flow_id IS NOT DISTINCT FROM $3::uuid
`

type DisableIntegrationInstallParams struct {
	ProjectID           uuid.UUID
	ID                  uuid.UUID
	ExpectedOauthFlowID *uuid.UUID
}

func (q *Queries) DisableIntegrationInstall(ctx context.Context, arg DisableIntegrationInstallParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableIntegrationInstall, arg.ProjectID, arg.ID, arg.ExpectedOauthFlowID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntegrationInstall = `-- name: GetIntegrationInstall :one
SELECT id, org_id, project_id, agent_profile_id, agent_id, installed_by_user_id,
  provider, integration_kind, connection_mode, state,
  provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id,
  provider_config, provider_identity, provider_metadata,
  last_oauth_flow_id, deleted_at, created_at, updated_at
FROM integration_installs
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetIntegrationInstallParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetIntegrationInstall(ctx context.Context, arg GetIntegrationInstallParams) (IntegrationInstall, error) {
	row := q.db.QueryRow(ctx, getIntegrationInstall, arg.ProjectID, arg.ID)
	var i IntegrationInstall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentProfileID,
		&i.AgentID,
		&i.InstalledByUserID,
		&i.Provider,
		&i.IntegrationKind,
		&i.ConnectionMode,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationInstallByID = `-- name: GetIntegrationInstallByID :one
SELECT id, org_id, project_id, agent_profile_id, agent_id, installed_by_user_id,
  provider, integration_kind, connection_mode, state,
  provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id,
  provider_config, provider_identity, provider_metadata,
  last_oauth_flow_id, deleted_at, created_at, updated_at
FROM integration_installs
WHERE id = $1 AND deleted_at IS NULL
`

type GetIntegrationInstallByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetIntegrationInstallByID(ctx context.Context, arg GetIntegrationInstallByIDParams) (IntegrationInstall, error) {
	row := q.db.QueryRow(ctx, getIntegrationInstallByID, arg.ID)
	var i IntegrationInstall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentProfileID,
		&i.AgentID,
		&i.InstalledByUserID,
		&i.Provider,
		&i.IntegrationKind,
		&i.ConnectionMode,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationInstallByProviderAccount = `-- name: GetIntegrationInstallByProviderAccount :one
SELECT id, org_id, project_id, agent_profile_id, agent_id, installed_by_user_id,
  provider, integration_kind, connection_mode, state,
  provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id,
  provider_config, provider_identity, provider_metadata,
  last_oauth_flow_id, deleted_at, created_at, updated_at
FROM integration_installs
WHERE provider = $1
  AND provider_tenant_id IS NOT DISTINCT FROM $2
  AND provider_account_ref = $3
  AND deleted_at IS NULL
`

type GetIntegrationInstallByProviderAccountParams struct {
	Provider           string
	ProviderTenantID   *string
	ProviderAccountRef string
}

func (q *Queries) GetIntegrationInstallByProviderAccount(ctx context.Context, arg GetIntegrationInstallByProviderAccountParams) (IntegrationInstall, error) {
	row := q.db.QueryRow(ctx, getIntegrationInstallByProviderAccount, arg.Provider, arg.ProviderTenantID, arg.ProviderAccountRef)
	var i IntegrationInstall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentProfileID,
		&i.AgentID,
		&i.InstalledByUserID,
		&i.Provider,
		&i.IntegrationKind,
		&i.ConnectionMode,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationTarget = `-- name: GetIntegrationTarget :one
SELECT target.id, project.org_id, target.project_id, target.agent_id, target.integration_install_id, target.target_ref, target.provider_ref,
  target.provider_ref_kind, target.display_name, target.provider_metadata, target.deleted_at, target.created_at, target.updated_at
FROM integration_targets target
JOIN projects project ON project.id = target.project_id
WHERE target.project_id = $1
  AND target.id = $2
  AND target.deleted_at IS NULL
`

type GetIntegrationTargetParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

type GetIntegrationTargetRow struct {
	ID                   uuid.UUID
	OrgID                uuid.UUID
	ProjectID            uuid.UUID
	AgentID              uuid.UUID
	IntegrationInstallID uuid.UUID
	TargetRef            string
	ProviderRef          string
	ProviderRefKind      string
	DisplayName          string
	ProviderMetadata     json.RawMessage
	DeletedAt            *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetIntegrationTarget(ctx context.Context, arg GetIntegrationTargetParams) (GetIntegrationTargetRow, error) {
	row := q.db.QueryRow(ctx, getIntegrationTarget, arg.ProjectID, arg.ID)
	var i GetIntegrationTargetRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.IntegrationInstallID,
		&i.TargetRef,
		&i.ProviderRef,
		&i.ProviderRefKind,
		&i.DisplayName,
		&i.ProviderMetadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationTargetByProviderRef = `-- name: GetIntegrationTargetByProviderRef :one
SELECT target.id, project.org_id, target.project_id, target.agent_id, target.integration_install_id, target.target_ref, target.provider_ref,
  target.provider_ref_kind, target.display_name, target.provider_metadata, target.deleted_at, target.created_at, target.updated_at
FROM integration_targets target
JOIN projects project ON project.id = target.project_id
WHERE target.project_id = $1
  AND target.integration_install_id = $2
  AND target.provider_ref = $3
  AND target.deleted_at IS NULL
`

type GetIntegrationTargetByProviderRefParams struct {
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
	ProviderRef          string
}

type GetIntegrationTargetByProviderRefRow struct {
	ID                   uuid.UUID
	OrgID                uuid.UUID
	ProjectID            uuid.UUID
	AgentID              uuid.UUID
	IntegrationInstallID uuid.UUID
	TargetRef            string
	ProviderRef          string
	ProviderRefKind      string
	DisplayName          string
	ProviderMetadata     json.RawMessage
	DeletedAt            *time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetIntegrationTargetByProviderRef(ctx context.Context, arg GetIntegrationTargetByProviderRefParams) (GetIntegrationTargetByProviderRefRow, error) {
	row := q.db.QueryRow(ctx, getIntegrationTargetByProviderRef, arg.ProjectID, arg.IntegrationInstallID, arg.ProviderRef)
	var i GetIntegrationTargetByProviderRefRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentID,
		&i.IntegrationInstallID,
		&i.TargetRef,
		&i.ProviderRef,
		&i.ProviderRefKind,
		&i.DisplayName,
		&i.ProviderMetadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIntegrationInstall = `-- name: InsertIntegrationInstall :one
INSERT INTO integration_installs(
  org_id, project_id, agent_profile_id, agent_id, installed_by_user_id,
  provider, integration_kind, connection_mode, state,
  provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id,
  provider_config, provider_identity, provider_metadata,
  last_oauth_flow_id, created_at, updated_at
)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15, $16,
  $17, transaction_timestamp(), transaction_timestamp()
)
ON CONFLICT (provider, provider_tenant_id, provider_account_ref) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, org_id, project_id, agent_profile_id, agent_id, installed_by_user_id,
  provider, integration_kind, connection_mode, state,
  provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id,
  provider_config, provider_identity, provider_metadata,
  last_oauth_flow_id, deleted_at, created_at, updated_at
`

type InsertIntegrationInstallParams struct {
	OrgID                    uuid.UUID
	ProjectID                uuid.UUID
	AgentProfileID           *uuid.UUID
	AgentID                  *uuid.UUID
	InstalledByUserID        uuid.UUID
	Provider                 string
	IntegrationKind          string
	ConnectionMode           string
	State                    string
	ProviderTenantID         string
	ProviderAccountRef       string
	ProviderAgentDisplayName string
	CredentialSecretID       *uuid.UUID
	ProviderConfig           json.RawMessage
	ProviderIdentity         json.RawMessage
	ProviderMetadata         json.RawMessage
	LastOauthFlowID          *uuid.UUID
}

func (q *Queries) InsertIntegrationInstall(ctx context.Context, arg InsertIntegrationInstallParams) (IntegrationInstall, error) {
	row := q.db.QueryRow(ctx, insertIntegrationInstall,
		arg.OrgID,
		arg.ProjectID,
		arg.AgentProfileID,
		arg.AgentID,
		arg.InstalledByUserID,
		arg.Provider,
		arg.IntegrationKind,
		arg.ConnectionMode,
		arg.State,
		arg.ProviderTenantID,
		arg.ProviderAccountRef,
		arg.ProviderAgentDisplayName,
		arg.CredentialSecretID,
		arg.ProviderConfig,
		arg.ProviderIdentity,
		arg.ProviderMetadata,
		arg.LastOauthFlowID,
	)
	var i IntegrationInstall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentProfileID,
		&i.AgentID,
		&i.InstalledByUserID,
		&i.Provider,
		&i.IntegrationKind,
		&i.ConnectionMode,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIntegrationTarget = `-- name: InsertIntegrationTarget :one
INSERT INTO integration_targets(
  project_id, agent_id, integration_install_id, target_ref, provider_ref,
  provider_ref_kind, display_name, created_at, updated_at
)
SELECT agent.project_id, agent.id, install.id,
       $1, $2, $3,
       $4, transaction_timestamp(), transaction_timestamp()
FROM agents agent
JOIN integration_installs install
  ON install.project_id = agent.project_id
 AND install.id = $5
 AND install.state = 'active'
 AND install.deleted_at IS NULL
WHERE agent.project_id = $6
  AND agent.id = $7
ON CONFLICT (project_id, integration_install_id, provider_ref) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, project_id, agent_id, integration_install_id, target_ref, provider_ref,
  provider_ref_kind, display_name, provider_metadata, deleted_at, created_at, updated_at
`

type InsertIntegrationTargetParams struct {
	TargetRef            string
	ProviderRef          string
	ProviderRefKind      string
	DisplayName          string
	IntegrationInstallID uuid.UUID
	ProjectID            uuid.UUID
	AgentID              uuid.UUID
}

func (q *Queries) InsertIntegrationTarget(ctx context.Context, arg InsertIntegrationTargetParams) (IntegrationTarget, error) {
	row := q.db.QueryRow(ctx, insertIntegrationTarget,
		arg.TargetRef,
		arg.ProviderRef,
		arg.ProviderRefKind,
		arg.DisplayName,
		arg.IntegrationInstallID,
		arg.ProjectID,
		arg.AgentID,
	)
	var i IntegrationTarget
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.IntegrationInstallID,
		&i.TargetRef,
		&i.ProviderRef,
		&i.ProviderRefKind,
		&i.DisplayName,
		&i.ProviderMetadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const integrationOAuthFlowConsumed = `-- name: IntegrationOAuthFlowConsumed :one
SELECT EXISTS (
  SELECT 1 FROM integration_installs WHERE last_oauth_flow_id = $1 AND deleted_at IS NULL
) AS consumed
`

type IntegrationOAuthFlowConsumedParams struct {
	LastOauthFlowID *uuid.UUID
}

func (q *Queries) IntegrationOAuthFlowConsumed(ctx context.Context, arg IntegrationOAuthFlowConsumedParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationOAuthFlowConsumed, arg.LastOauthFlowID)
	var consumed bool
	err := row.Scan(&consumed)
	return consumed, err
}

const listIntegrationInstallsForProject = `-- name: ListIntegrationInstallsForProject :many
WITH listed AS (
SELECT install.id, install.org_id, install.project_id, install.agent_profile_id, install.agent_id,
       install.installed_by_user_id, install.provider, install.integration_kind, install.connection_mode,
       install.state, install.provider_tenant_id, install.provider_account_ref,
       install.provider_agent_display_name, install.credential_secret_id,
       install.provider_config, install.provider_identity, install.provider_metadata,
       install.last_oauth_flow_id, install.created_at, install.updated_at,
       CASE $6::text
         WHEN 'name' THEN lower(install.provider_agent_display_name)
         WHEN 'created_at' THEN to_char(install.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
         WHEN 'updated_at' THEN to_char(install.updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US')
       END::text AS sort_key
FROM integration_installs install
WHERE install.project_id = $7
  AND install.deleted_at IS NULL
  AND ($8::text = '' OR install.provider_agent_display_name ILIKE $8::text ESCAPE '\')
  AND ($9::uuid IS NULL OR install.agent_profile_id = $9::uuid)
  AND ($10::uuid IS NULL OR install.last_oauth_flow_id = $10::uuid)
)
SELECT id, org_id, project_id, agent_profile_id, agent_id, installed_by_user_id,
       provider, integration_kind, connection_mode, state,
       provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id,
       provider_config, provider_identity, provider_metadata,
       last_oauth_flow_id, created_at, updated_at, sort_key
FROM listed
WHERE $1::boolean = false
   OR ($2::boolean = false AND (sort_key, id) > ($3::text, $4::uuid))
   OR ($2::boolean = true AND (sort_key, id) < ($3::text, $4::uuid))
ORDER BY CASE WHEN $2::boolean = false THEN sort_key END ASC,
         CASE WHEN $2::boolean = true THEN sort_key END DESC,
         CASE WHEN $2::boolean = false THEN id END ASC,
         CASE WHEN $2::boolean = true THEN id END DESC
LIMIT $5
`

type ListIntegrationInstallsForProjectParams struct {
	CursorSet      bool
	SortDesc       bool
	CursorKey      string
	CursorID       uuid.UUID
	RowLimit       int32
	SortField      string
	ProjectID      uuid.UUID
	NamePattern    string
	AgentProfileID *uuid.UUID
	OauthFlowID    *uuid.UUID
}

type ListIntegrationInstallsForProjectRow struct {
	ID                       uuid.UUID
	OrgID                    uuid.UUID
	ProjectID                uuid.UUID
	AgentProfileID           *uuid.UUID
	AgentID                  *uuid.UUID
	InstalledByUserID        uuid.UUID
	Provider                 string
	IntegrationKind          string
	ConnectionMode           string
	State                    string
	ProviderTenantID         string
	ProviderAccountRef       string
	ProviderAgentDisplayName string
	CredentialSecretID       *uuid.UUID
	ProviderConfig           json.RawMessage
	ProviderIdentity         json.RawMessage
	ProviderMetadata         json.RawMessage
	LastOauthFlowID          *uuid.UUID
	CreatedAt                time.Time
	UpdatedAt                time.Time
	SortKey                  string
}

func (q *Queries) ListIntegrationInstallsForProject(ctx context.Context, arg ListIntegrationInstallsForProjectParams) ([]ListIntegrationInstallsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationInstallsForProject,
		arg.CursorSet,
		arg.SortDesc,
		arg.CursorKey,
		arg.CursorID,
		arg.RowLimit,
		arg.SortField,
		arg.ProjectID,
		arg.NamePattern,
		arg.AgentProfileID,
		arg.OauthFlowID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationInstallsForProjectRow{}
	for rows.Next() {
		var i ListIntegrationInstallsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.AgentProfileID,
			&i.AgentID,
			&i.InstalledByUserID,
			&i.Provider,
			&i.IntegrationKind,
			&i.ConnectionMode,
			&i.State,
			&i.ProviderTenantID,
			&i.ProviderAccountRef,
			&i.ProviderAgentDisplayName,
			&i.CredentialSecretID,
			&i.ProviderConfig,
			&i.ProviderIdentity,
			&i.ProviderMetadata,
			&i.LastOauthFlowID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationTargets = `-- name: ListIntegrationTargets :many
SELECT target.id,
  target.integration_install_id,
  target.target_ref,
  target.provider_ref,
  target.provider_ref_kind,
  target.display_name,
  install.provider, install.state AS install_state,
  CASE WHEN agent.integration_target_id = target.id THEN true ELSE false END AS is_current
FROM integration_targets target
JOIN agents agent
  ON agent.project_id = target.project_id
 AND agent.id = target.agent_id
JOIN integration_installs install
  ON install.project_id = target.project_id
 AND install.id = target.integration_install_id
 AND install.deleted_at IS NULL
WHERE target.project_id = $1
  AND target.agent_id = $2
  AND target.deleted_at IS NULL
ORDER BY is_current DESC, target.created_at ASC, target.id ASC
`

type ListIntegrationTargetsParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type ListIntegrationTargetsRow struct {
	ID                   uuid.UUID
	IntegrationInstallID uuid.UUID
	TargetRef            string
	ProviderRef          string
	ProviderRefKind      string
	DisplayName          string
	Provider             string
	InstallState         string
	IsCurrent            bool
}

func (q *Queries) ListIntegrationTargets(ctx context.Context, arg ListIntegrationTargetsParams) ([]ListIntegrationTargetsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationTargets, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationTargetsRow{}
	for rows.Next() {
		var i ListIntegrationTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationInstallID,
			&i.TargetRef,
			&i.ProviderRef,
			&i.ProviderRefKind,
			&i.DisplayName,
			&i.Provider,
			&i.InstallState,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIntegrationInstallByProviderAccount = `-- name: LockIntegrationInstallByProviderAccount :one
SELECT id, org_id, project_id, agent_profile_id, agent_id, installed_by_user_id,
  provider, integration_kind, connection_mode, state,
  provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id,
  provider_config, provider_identity, provider_metadata,
  last_oauth_flow_id, deleted_at, created_at, updated_at
FROM integration_installs
WHERE provider = $1
  AND provider_tenant_id = $2
  AND provider_account_ref = $3
  AND deleted_at IS NULL
FOR UPDATE
`

type LockIntegrationInstallByProviderAccountParams struct {
	Provider           string
	ProviderTenantID   *string
	ProviderAccountRef string
}

func (q *Queries) LockIntegrationInstallByProviderAccount(ctx context.Context, arg LockIntegrationInstallByProviderAccountParams) (IntegrationInstall, error) {
	row := q.db.QueryRow(ctx, lockIntegrationInstallByProviderAccount, arg.Provider, arg.ProviderTenantID, arg.ProviderAccountRef)
	var i IntegrationInstall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentProfileID,
		&i.AgentID,
		&i.InstalledByUserID,
		&i.Provider,
		&i.IntegrationKind,
		&i.ConnectionMode,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockIntegrationInstallForDisable = `-- name: LockIntegrationInstallForDisable :one
SELECT state, last_oauth_flow_id
FROM integration_installs
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type LockIntegrationInstallForDisableParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

type LockIntegrationInstallForDisableRow struct {
	State           string
	LastOauthFlowID *uuid.UUID
}

func (q *Queries) LockIntegrationInstallForDisable(ctx context.Context, arg LockIntegrationInstallForDisableParams) (LockIntegrationInstallForDisableRow, error) {
	row := q.db.QueryRow(ctx, lockIntegrationInstallForDisable, arg.ProjectID, arg.ID)
	var i LockIntegrationInstallForDisableRow
	err := row.Scan(&i.State, &i.LastOauthFlowID)
	return i, err
}

const setAgentIntegrationTarget = `-- name: SetAgentIntegrationTarget :one
UPDATE agents
SET integration_target_id = $1::uuid,
    updated_at = statement_timestamp()
WHERE agents.project_id = $2
  AND agents.id = $3
  AND (
    $1::uuid IS NULL
    OR EXISTS (
      SELECT 1
      FROM integration_targets target
      JOIN integration_installs install
        ON install.project_id = target.project_id
       AND install.id = target.integration_install_id
       AND install.state = 'active'
       AND install.deleted_at IS NULL
      WHERE target.project_id = agents.project_id
        AND target.agent_id = agents.id
        AND target.id = $1::uuid
        AND target.deleted_at IS NULL
    )
  )
RETURNING id, org_id, project_id, state, name,
  agent_profile_id, current_config_id, integration_target_id,
  coalesce(idempotency_key, '') AS idempotency_key,
  next_event_sequence, created_at, updated_at, archived_at
`

type SetAgentIntegrationTargetParams struct {
	IntegrationTargetID *uuid.UUID
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
}

type SetAgentIntegrationTargetRow struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	ProjectID           uuid.UUID
	State               string
	Name                string
	AgentProfileID      *uuid.UUID
	CurrentConfigID     uuid.UUID
	IntegrationTargetID *uuid.UUID
	IdempotencyKey      string
	NextEventSequence   int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ArchivedAt          *time.Time
}

func (q *Queries) SetAgentIntegrationTarget(ctx context.Context, arg SetAgentIntegrationTargetParams) (SetAgentIntegrationTargetRow, error) {
	row := q.db.QueryRow(ctx, setAgentIntegrationTarget, arg.IntegrationTargetID, arg.ProjectID, arg.AgentID)
	var i SetAgentIntegrationTargetRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.State,
		&i.Name,
		&i.AgentProfileID,
		&i.CurrentConfigID,
		&i.IntegrationTargetID,
		&i.IdempotencyKey,
		&i.NextEventSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateIntegrationInstall = `-- name: UpdateIntegrationInstall :one
UPDATE integration_installs
SET installed_by_user_id = $1,
    connection_mode = $2,
    state = $3,
    provider_agent_display_name = CASE
      WHEN $4::text = '' THEN provider_agent_display_name
      ELSE $4::text
    END,
    credential_secret_id = $5,
    provider_config = $6,
    provider_identity = $7,
    provider_metadata = $8,
    last_oauth_flow_id = coalesce($9, last_oauth_flow_id),
    updated_at = statement_timestamp()
WHERE project_id = $10
  AND id = $11
  AND deleted_at IS NULL
  AND (
    $9::uuid IS NULL
    OR last_oauth_flow_id IS NULL
    OR last_oauth_flow_id < $9::uuid
  )
RETURNING id, org_id, project_id, agent_profile_id, agent_id, installed_by_user_id,
  provider, integration_kind, connection_mode, state,
  provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id,
  provider_config, provider_identity, provider_metadata,
  last_oauth_flow_id, deleted_at, created_at, updated_at
`

type UpdateIntegrationInstallParams struct {
	InstalledByUserID        uuid.UUID
	ConnectionMode           string
	State                    string
	ProviderAgentDisplayName string
	CredentialSecretID       *uuid.UUID
	ProviderConfig           json.RawMessage
	ProviderIdentity         json.RawMessage
	ProviderMetadata         json.RawMessage
	LastOauthFlowID          *uuid.UUID
	ProjectID                uuid.UUID
	ID                       uuid.UUID
}

func (q *Queries) UpdateIntegrationInstall(ctx context.Context, arg UpdateIntegrationInstallParams) (IntegrationInstall, error) {
	row := q.db.QueryRow(ctx, updateIntegrationInstall,
		arg.InstalledByUserID,
		arg.ConnectionMode,
		arg.State,
		arg.ProviderAgentDisplayName,
		arg.CredentialSecretID,
		arg.ProviderConfig,
		arg.ProviderIdentity,
		arg.ProviderMetadata,
		arg.LastOauthFlowID,
		arg.ProjectID,
		arg.ID,
	)
	var i IntegrationInstall
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.AgentProfileID,
		&i.AgentID,
		&i.InstalledByUserID,
		&i.Provider,
		&i.IntegrationKind,
		&i.ConnectionMode,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIntegrationTargetDisplayNamesByProviderRefPrefix = `-- name: UpdateIntegrationTargetDisplayNamesByProviderRefPrefix :execrows
UPDATE integration_targets
SET display_name = $1,
    updated_at = transaction_timestamp()
WHERE project_id = $2
  AND integration_install_id = $3
  AND deleted_at IS NULL
  AND split_part(provider_ref, ':', 1) = $4
  AND display_name IS DISTINCT FROM $1
`

type UpdateIntegrationTargetDisplayNamesByProviderRefPrefixParams struct {
	DisplayName          string
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
	ProviderRefPrefix    string
}

func (q *Queries) UpdateIntegrationTargetDisplayNamesByProviderRefPrefix(ctx context.Context, arg UpdateIntegrationTargetDisplayNamesByProviderRefPrefixParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIntegrationTargetDisplayNamesByProviderRefPrefix,
		arg.DisplayName,
		arg.ProjectID,
		arg.IntegrationInstallID,
		arg.ProviderRefPrefix,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
