// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_connection_runtime.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const checkpointIntegrationConnectionRuntime = `-- name: CheckpointIntegrationConnectionRuntime :execrows
UPDATE integration_connection_runtime
SET checkpoint = $1::jsonb, updated_at = statement_timestamp()
WHERE project_id = $2 AND connection_id = $3 AND runtime_key = $4
  AND claim_token = $5::uuid AND claim_expires_at > statement_timestamp()
`

type CheckpointIntegrationConnectionRuntimeParams struct {
	Checkpoint   *json.RawMessage
	ProjectID    uuid.UUID
	ConnectionID uuid.UUID
	RuntimeKey   string
	ClaimToken   uuid.UUID
}

func (q *Queries) CheckpointIntegrationConnectionRuntime(ctx context.Context, arg CheckpointIntegrationConnectionRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, checkpointIntegrationConnectionRuntime,
		arg.Checkpoint,
		arg.ProjectID,
		arg.ConnectionID,
		arg.RuntimeKey,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimIntegrationConnectionRuntime = `-- name: ClaimIntegrationConnectionRuntime :one
INSERT INTO integration_connection_runtime(project_id, connection_id, runtime_key, connection_updated_at,
    credential_version_id, claim_token, claim_expires_at)
SELECT connection.project_id, connection.id, $1, connection.updated_at,
    $2, $3,
    statement_timestamp() + $4::bigint * interval '1 millisecond'
FROM integration_connections connection
WHERE connection.project_id = $5 AND connection.id = $6
  AND connection.updated_at = $7 AND connection.deleted_at IS NULL
ON CONFLICT (project_id, connection_id, runtime_key) DO UPDATE
SET checkpoint = CASE WHEN integration_connection_runtime.connection_updated_at = EXCLUDED.connection_updated_at
                       AND integration_connection_runtime.credential_version_id = EXCLUDED.credential_version_id
                      THEN integration_connection_runtime.checkpoint ELSE NULL END,
    connection_updated_at = EXCLUDED.connection_updated_at, credential_version_id = EXCLUDED.credential_version_id,
    claim_token = EXCLUDED.claim_token, claim_expires_at = EXCLUDED.claim_expires_at,
    last_error = NULL, updated_at = statement_timestamp()
WHERE (integration_connection_runtime.claim_expires_at IS NULL OR integration_connection_runtime.claim_expires_at <= statement_timestamp())
  AND (integration_connection_runtime.available_at <= statement_timestamp()
       OR integration_connection_runtime.connection_updated_at <> EXCLUDED.connection_updated_at
       OR integration_connection_runtime.credential_version_id <> EXCLUDED.credential_version_id)
RETURNING checkpoint, claim_expires_at
`

type ClaimIntegrationConnectionRuntimeParams struct {
	RuntimeKey          string
	CredentialVersionID uuid.UUID
	ClaimToken          *uuid.UUID
	LeaseMilliseconds   int64
	ProjectID           uuid.UUID
	ConnectionID        uuid.UUID
	ConnectionUpdatedAt time.Time
}

type ClaimIntegrationConnectionRuntimeRow struct {
	Checkpoint     *json.RawMessage
	ClaimExpiresAt *time.Time
}

// Caller holds project/connection/secret reference gates and validates revisions
// before locking the runtime. Token changes on every claim; stale owners cannot
// publish checkpoints even when the same process reacquires the unit later.
func (q *Queries) ClaimIntegrationConnectionRuntime(ctx context.Context, arg ClaimIntegrationConnectionRuntimeParams) (ClaimIntegrationConnectionRuntimeRow, error) {
	row := q.db.QueryRow(ctx, claimIntegrationConnectionRuntime,
		arg.RuntimeKey,
		arg.CredentialVersionID,
		arg.ClaimToken,
		arg.LeaseMilliseconds,
		arg.ProjectID,
		arg.ConnectionID,
		arg.ConnectionUpdatedAt,
	)
	var i ClaimIntegrationConnectionRuntimeRow
	err := row.Scan(&i.Checkpoint, &i.ClaimExpiresAt)
	return i, err
}

const integrationConnectionRuntimeClaimable = `-- name: IntegrationConnectionRuntimeClaimable :one
SELECT NOT EXISTS (
    SELECT 1 FROM integration_connection_runtime
    WHERE project_id = $1 AND connection_id = $2 AND runtime_key = $3
      AND (claim_expires_at > statement_timestamp()
           OR (available_at > statement_timestamp()
               AND connection_updated_at = $4
               AND credential_version_id = $5))
) AS claimable
`

type IntegrationConnectionRuntimeClaimableParams struct {
	ProjectID           uuid.UUID
	ConnectionID        uuid.UUID
	RuntimeKey          string
	ConnectionUpdatedAt time.Time
	CredentialVersionID uuid.UUID
}

// This unlocked hint avoids contending with the owner's heartbeat on every
// discovery scan. The claim below remains the authoritative atomic decision.
func (q *Queries) IntegrationConnectionRuntimeClaimable(ctx context.Context, arg IntegrationConnectionRuntimeClaimableParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationConnectionRuntimeClaimable,
		arg.ProjectID,
		arg.ConnectionID,
		arg.RuntimeKey,
		arg.ConnectionUpdatedAt,
		arg.CredentialVersionID,
	)
	var claimable bool
	err := row.Scan(&claimable)
	return claimable, err
}

const listPersistentIntegrationConnections = `-- name: ListPersistentIntegrationConnections :many
SELECT connection.id, connection.project_id
FROM integration_connections connection
JOIN projects project ON project.id = connection.project_id
JOIN orgs org ON org.id = project.org_id
WHERE connection.provider = 'discord' AND connection.state = 'active' AND connection.deleted_at IS NULL
  AND project.deleted_at IS NULL AND org.deleted_at IS NULL
  AND ($1::uuid IS NULL OR connection.id > $1::uuid)
ORDER BY connection.id
LIMIT $2
`

type ListPersistentIntegrationConnectionsParams struct {
	AfterID  *uuid.UUID
	RowLimit int32
}

type ListPersistentIntegrationConnectionsRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

// Only actual hosted persistent transports are enumerated. Cursor scanning keeps
// a busy prefix owned by other workers from hiding connections later in the set.
func (q *Queries) ListPersistentIntegrationConnections(ctx context.Context, arg ListPersistentIntegrationConnectionsParams) ([]ListPersistentIntegrationConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listPersistentIntegrationConnections, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersistentIntegrationConnectionsRow{}
	for rows.Next() {
		var i ListPersistentIntegrationConnectionsRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIntegrationConnectionRuntime = `-- name: LockIntegrationConnectionRuntime :one
SELECT runtime_key FROM integration_connection_runtime
WHERE project_id = $1 AND connection_id = $2 AND runtime_key = $3
FOR UPDATE
`

type LockIntegrationConnectionRuntimeParams struct {
	ProjectID    uuid.UUID
	ConnectionID uuid.UUID
	RuntimeKey   string
}

// Lock then re-read in a fresh statement: the lease can expire while waiting.
func (q *Queries) LockIntegrationConnectionRuntime(ctx context.Context, arg LockIntegrationConnectionRuntimeParams) (string, error) {
	row := q.db.QueryRow(ctx, lockIntegrationConnectionRuntime, arg.ProjectID, arg.ConnectionID, arg.RuntimeKey)
	var runtime_key string
	err := row.Scan(&runtime_key)
	return runtime_key, err
}

const readIntegrationConnectionRuntimeLease = `-- name: ReadIntegrationConnectionRuntimeLease :one
SELECT checkpoint, claim_expires_at
FROM integration_connection_runtime
WHERE project_id = $1 AND connection_id = $2 AND runtime_key = $3
  AND connection_updated_at = $4 AND credential_version_id = $5
  AND claim_token = $6::uuid AND claim_expires_at > statement_timestamp()
`

type ReadIntegrationConnectionRuntimeLeaseParams struct {
	ProjectID           uuid.UUID
	ConnectionID        uuid.UUID
	RuntimeKey          string
	ConnectionUpdatedAt time.Time
	CredentialVersionID uuid.UUID
	ClaimToken          uuid.UUID
}

type ReadIntegrationConnectionRuntimeLeaseRow struct {
	Checkpoint     *json.RawMessage
	ClaimExpiresAt *time.Time
}

func (q *Queries) ReadIntegrationConnectionRuntimeLease(ctx context.Context, arg ReadIntegrationConnectionRuntimeLeaseParams) (ReadIntegrationConnectionRuntimeLeaseRow, error) {
	row := q.db.QueryRow(ctx, readIntegrationConnectionRuntimeLease,
		arg.ProjectID,
		arg.ConnectionID,
		arg.RuntimeKey,
		arg.ConnectionUpdatedAt,
		arg.CredentialVersionID,
		arg.ClaimToken,
	)
	var i ReadIntegrationConnectionRuntimeLeaseRow
	err := row.Scan(&i.Checkpoint, &i.ClaimExpiresAt)
	return i, err
}

const releaseIntegrationConnectionRuntime = `-- name: ReleaseIntegrationConnectionRuntime :execrows
UPDATE integration_connection_runtime
SET claim_token = NULL, claim_expires_at = NULL,
    available_at = statement_timestamp() + $1::bigint * interval '1 millisecond',
    last_error = $2, updated_at = statement_timestamp()
WHERE project_id = $3 AND connection_id = $4 AND runtime_key = $5
  AND claim_token = $6::uuid AND claim_expires_at > statement_timestamp()
`

type ReleaseIntegrationConnectionRuntimeParams struct {
	DelayMilliseconds int64
	LastError         *string
	ProjectID         uuid.UUID
	ConnectionID      uuid.UUID
	RuntimeKey        string
	ClaimToken        uuid.UUID
}

// Release never publishes a checkpoint. It can relinquish a revoked parent's
// unit; the exact unexpired token still prevents releasing a replacement owner.
func (q *Queries) ReleaseIntegrationConnectionRuntime(ctx context.Context, arg ReleaseIntegrationConnectionRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIntegrationConnectionRuntime,
		arg.DelayMilliseconds,
		arg.LastError,
		arg.ProjectID,
		arg.ConnectionID,
		arg.RuntimeKey,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewIntegrationConnectionRuntime = `-- name: RenewIntegrationConnectionRuntime :execrows
UPDATE integration_connection_runtime
SET claim_expires_at = statement_timestamp() + $1::bigint * interval '1 millisecond', updated_at = statement_timestamp()
WHERE project_id = $2 AND connection_id = $3 AND runtime_key = $4
  AND claim_token = $5::uuid AND claim_expires_at > statement_timestamp()
`

type RenewIntegrationConnectionRuntimeParams struct {
	LeaseMilliseconds int64
	ProjectID         uuid.UUID
	ConnectionID      uuid.UUID
	RuntimeKey        string
	ClaimToken        uuid.UUID
}

func (q *Queries) RenewIntegrationConnectionRuntime(ctx context.Context, arg RenewIntegrationConnectionRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewIntegrationConnectionRuntime,
		arg.LeaseMilliseconds,
		arg.ProjectID,
		arg.ConnectionID,
		arg.RuntimeKey,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
