// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_runtime.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const claimIntegrationRuntimeUnits = `-- name: ClaimIntegrationRuntimeUnits :many
WITH candidate AS MATERIALIZED (
  SELECT unit.id, app.configuration_revision AS app_configuration_revision,
         install.configuration_revision AS install_configuration_revision
  FROM integration_runtime_units unit
  JOIN integration_apps app
    ON app.org_id = unit.org_id
   AND app.id = unit.integration_app_id
   AND app.state = 'active'
   AND app.deleted_at IS NULL
  LEFT JOIN integration_installs install
    ON install.org_id = unit.org_id
   AND install.project_id = unit.project_id
   AND install.id = unit.integration_install_id
   AND install.integration_app_id = unit.integration_app_id
   AND install.state = 'active'
   AND install.deleted_at IS NULL
  WHERE unit.connector_key = $3
    AND unit.provider = $4
    AND unit.desired_state = 'running'
    AND unit.deleted_at IS NULL
    AND unit.available_at <= statement_timestamp()
    AND (unit.lease_token IS NULL OR unit.lease_expires_at <= statement_timestamp())
    AND (unit.integration_install_id IS NULL OR install.id IS NOT NULL)
  ORDER BY unit.available_at, unit.id
  FOR UPDATE OF unit SKIP LOCKED
  LIMIT $5
)
UPDATE integration_runtime_units unit
SET status = 'running',
    lease_owner = $1::text,
    lease_token = uuidv7(),
    lease_generation = unit.lease_generation + 1,
    leased_at = statement_timestamp(),
    renewed_at = statement_timestamp(),
    lease_expires_at = statement_timestamp() +
      ($2::bigint * interval '1 microsecond'),
    available_at = statement_timestamp() +
      ($2::bigint * interval '1 microsecond'),
    lease_spec_revision = unit.spec_revision,
    lease_app_configuration_revision = candidate.app_configuration_revision,
    lease_install_configuration_revision = candidate.install_configuration_revision,
    last_error = '{}'::jsonb,
    updated_at = statement_timestamp()
FROM candidate
WHERE unit.id = candidate.id
RETURNING unit.id, unit.org_id, unit.integration_app_id, unit.project_id,
  unit.integration_install_id, unit.provider, unit.connector_key, unit.unit_key, unit.runtime_kind,
  unit.desired_state, unit.spec_revision, unit.configuration,
  unit.status, unit.failure_count, unit.available_at, unit.lease_owner, unit.lease_token, unit.lease_generation,
  unit.leased_at, unit.renewed_at, unit.lease_expires_at,
  unit.lease_spec_revision, unit.lease_app_configuration_revision,
  unit.lease_install_configuration_revision,
  unit.checkpoint_version, unit.checkpoint_revision, unit.checkpoint,
  unit.last_error, unit.deleted_at, unit.created_at, unit.updated_at
`

type ClaimIntegrationRuntimeUnitsParams struct {
	LeaseOwner        string
	LeaseMicroseconds int64
	ConnectorKey      string
	Provider          string
	RowLimit          int32
}

func (q *Queries) ClaimIntegrationRuntimeUnits(ctx context.Context, arg ClaimIntegrationRuntimeUnitsParams) ([]IntegrationRuntimeUnit, error) {
	rows, err := q.db.Query(ctx, claimIntegrationRuntimeUnits,
		arg.LeaseOwner,
		arg.LeaseMicroseconds,
		arg.ConnectorKey,
		arg.Provider,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationRuntimeUnit{}
	for rows.Next() {
		var i IntegrationRuntimeUnit
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.IntegrationAppID,
			&i.ProjectID,
			&i.IntegrationInstallID,
			&i.Provider,
			&i.ConnectorKey,
			&i.UnitKey,
			&i.RuntimeKind,
			&i.DesiredState,
			&i.SpecRevision,
			&i.Configuration,
			&i.Status,
			&i.FailureCount,
			&i.AvailableAt,
			&i.LeaseOwner,
			&i.LeaseToken,
			&i.LeaseGeneration,
			&i.LeasedAt,
			&i.RenewedAt,
			&i.LeaseExpiresAt,
			&i.LeaseSpecRevision,
			&i.LeaseAppConfigurationRevision,
			&i.LeaseInstallConfigurationRevision,
			&i.CheckpointVersion,
			&i.CheckpointRevision,
			&i.Checkpoint,
			&i.LastError,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteIntegrationInstallRuntimeUnits = `-- name: DeleteIntegrationInstallRuntimeUnits :exec
UPDATE integration_runtime_units
SET desired_state = 'stopped',
    status = 'stopped',
    lease_owner = NULL,
    lease_token = NULL,
    leased_at = NULL,
    renewed_at = NULL,
    lease_expires_at = NULL,
    lease_spec_revision = NULL,
    lease_app_configuration_revision = NULL,
    lease_install_configuration_revision = NULL,
    deleted_at = transaction_timestamp(),
    updated_at = transaction_timestamp()
WHERE project_id = $1::uuid
  AND integration_install_id = $2
  AND deleted_at IS NULL
`

type DeleteIntegrationInstallRuntimeUnitsParams struct {
	ProjectID            uuid.UUID
	IntegrationInstallID *uuid.UUID
}

func (q *Queries) DeleteIntegrationInstallRuntimeUnits(ctx context.Context, arg DeleteIntegrationInstallRuntimeUnitsParams) error {
	_, err := q.db.Exec(ctx, deleteIntegrationInstallRuntimeUnits, arg.ProjectID, arg.IntegrationInstallID)
	return err
}

const heartbeatIntegrationRuntimeUnit = `-- name: HeartbeatIntegrationRuntimeUnit :one
UPDATE integration_runtime_units unit
SET renewed_at = statement_timestamp(),
    lease_expires_at = statement_timestamp() +
      ($1::bigint * interval '1 microsecond'),
    available_at = statement_timestamp() +
      ($1::bigint * interval '1 microsecond'),
    checkpoint = CASE WHEN $2::boolean
      THEN $3::jsonb ELSE checkpoint END,
    checkpoint_version = CASE WHEN $2::boolean
      THEN $4::integer ELSE checkpoint_version END,
    checkpoint_revision = CASE WHEN $2::boolean
      THEN checkpoint_revision + 1 ELSE checkpoint_revision END,
    failure_count = 0,
    updated_at = statement_timestamp()
WHERE unit.id = $5
  AND unit.lease_token = $6::uuid
  AND unit.lease_generation = $7
  AND unit.spec_revision = unit.lease_spec_revision
  AND unit.desired_state = 'running'
  AND unit.lease_expires_at > statement_timestamp()
  AND unit.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM integration_apps app
    WHERE app.org_id = unit.org_id
      AND app.id = unit.integration_app_id
      AND EXISTS (
        SELECT 1
        FROM generate_subscripts($8::text[], 1) AS capability(index)
        WHERE ($8::text[])[capability.index] = unit.connector_key
          AND ($9::text[])[capability.index] = unit.provider
      )
      AND app.configuration_revision = unit.lease_app_configuration_revision
      AND app.state = 'active'
      AND app.deleted_at IS NULL
  )
  AND (
    unit.integration_install_id IS NULL
    OR EXISTS (
      SELECT 1
      FROM integration_installs install
      WHERE install.org_id = unit.org_id
        AND install.project_id = unit.project_id
        AND install.id = unit.integration_install_id
        AND install.integration_app_id = unit.integration_app_id
        AND install.state = 'active'
        AND install.deleted_at IS NULL
        AND install.configuration_revision = unit.lease_install_configuration_revision
    )
  )
RETURNING unit.id, unit.org_id, unit.integration_app_id, unit.project_id,
  unit.integration_install_id, unit.provider, unit.connector_key,
  unit.unit_key, unit.runtime_kind, unit.desired_state,
  unit.spec_revision, unit.configuration, unit.status, unit.failure_count,
  unit.available_at, unit.lease_owner,
  unit.lease_token, unit.lease_generation, unit.leased_at, unit.renewed_at,
  unit.lease_expires_at, unit.lease_spec_revision, unit.lease_app_configuration_revision,
  unit.lease_install_configuration_revision, unit.checkpoint_version, unit.checkpoint_revision,
  unit.checkpoint, unit.last_error, unit.deleted_at, unit.created_at, unit.updated_at
`

type HeartbeatIntegrationRuntimeUnitParams struct {
	LeaseMicroseconds int64
	WriteCheckpoint   bool
	Checkpoint        json.RawMessage
	CheckpointVersion int32
	ID                uuid.UUID
	LeaseToken        uuid.UUID
	LeaseGeneration   int64
	ConnectorKeys     []string
	Providers         []string
}

func (q *Queries) HeartbeatIntegrationRuntimeUnit(ctx context.Context, arg HeartbeatIntegrationRuntimeUnitParams) (IntegrationRuntimeUnit, error) {
	row := q.db.QueryRow(ctx, heartbeatIntegrationRuntimeUnit,
		arg.LeaseMicroseconds,
		arg.WriteCheckpoint,
		arg.Checkpoint,
		arg.CheckpointVersion,
		arg.ID,
		arg.LeaseToken,
		arg.LeaseGeneration,
		arg.ConnectorKeys,
		arg.Providers,
	)
	var i IntegrationRuntimeUnit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IntegrationAppID,
		&i.ProjectID,
		&i.IntegrationInstallID,
		&i.Provider,
		&i.ConnectorKey,
		&i.UnitKey,
		&i.RuntimeKind,
		&i.DesiredState,
		&i.SpecRevision,
		&i.Configuration,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseGeneration,
		&i.LeasedAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.LeaseSpecRevision,
		&i.LeaseAppConfigurationRevision,
		&i.LeaseInstallConfigurationRevision,
		&i.CheckpointVersion,
		&i.CheckpointRevision,
		&i.Checkpoint,
		&i.LastError,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const integrationRuntimeLeaseIsCurrent = `-- name: IntegrationRuntimeLeaseIsCurrent :one
SELECT EXISTS (
  SELECT 1
  FROM integration_runtime_units unit
  JOIN integration_apps app
    ON app.org_id = unit.org_id
   AND app.id = unit.integration_app_id
   AND app.state = 'active'
   AND app.deleted_at IS NULL
   AND app.configuration_revision = unit.lease_app_configuration_revision
  JOIN integration_installs install
    ON install.org_id = unit.org_id
   AND install.id = $1
   AND install.integration_app_id = unit.integration_app_id
   AND install.state = 'active'
   AND install.deleted_at IS NULL
  WHERE unit.id = $2
    AND unit.integration_app_id = $3
    AND (
      unit.integration_install_id IS NULL
      OR (
        unit.integration_install_id = install.id
        AND unit.project_id = install.project_id
        AND install.configuration_revision = unit.lease_install_configuration_revision
      )
    )
    AND unit.lease_token = $4::uuid
    AND unit.lease_generation = $5
    AND unit.spec_revision = unit.lease_spec_revision
    AND unit.lease_expires_at > statement_timestamp()
    AND unit.desired_state = 'running'
    AND unit.deleted_at IS NULL
)::boolean
`

type IntegrationRuntimeLeaseIsCurrentParams struct {
	IntegrationInstallID uuid.UUID
	ID                   uuid.UUID
	IntegrationAppID     uuid.UUID
	LeaseToken           uuid.UUID
	LeaseGeneration      int64
}

func (q *Queries) IntegrationRuntimeLeaseIsCurrent(ctx context.Context, arg IntegrationRuntimeLeaseIsCurrentParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationRuntimeLeaseIsCurrent,
		arg.IntegrationInstallID,
		arg.ID,
		arg.IntegrationAppID,
		arg.LeaseToken,
		arg.LeaseGeneration,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const lockIntegrationRuntimeLeaseForMutation = `-- name: LockIntegrationRuntimeLeaseForMutation :one
WITH install_authority AS MATERIALIZED (
  SELECT install.id, install.org_id, install.project_id, install.integration_app_id,
    install.configuration_revision
  FROM integration_installs install
  WHERE install.id = $1
    AND install.project_id = $2::uuid
    AND install.state = 'active'
    AND install.deleted_at IS NULL
  FOR SHARE OF install
), app_authority AS MATERIALIZED (
  SELECT app.id, app.org_id, app.configuration_revision
  FROM integration_apps app
  JOIN install_authority install
    ON install.integration_app_id = app.id
   AND install.org_id = app.org_id
  WHERE app.id = $3
    AND app.state = 'active'
    AND app.deleted_at IS NULL
  FOR SHARE OF app
), unit_authority AS MATERIALIZED (
  SELECT unit.id
  FROM integration_runtime_units unit
  JOIN install_authority install
    ON install.integration_app_id = unit.integration_app_id
  JOIN app_authority app
    ON app.id = unit.integration_app_id
   AND app.org_id = unit.org_id
  WHERE unit.id = $4
    AND (
      unit.integration_install_id IS NULL
      OR (
        unit.integration_install_id = install.id
        AND unit.project_id = install.project_id
        AND install.configuration_revision = unit.lease_install_configuration_revision
      )
    )
    AND unit.lease_token = $5::uuid
    AND unit.lease_generation = $6
    AND unit.spec_revision = unit.lease_spec_revision
    AND unit.lease_expires_at > statement_timestamp()
    AND unit.desired_state = 'running'
    AND unit.deleted_at IS NULL
    AND app.configuration_revision = unit.lease_app_configuration_revision
  FOR SHARE OF unit
)
SELECT EXISTS (SELECT 1 FROM unit_authority)::boolean
`

type LockIntegrationRuntimeLeaseForMutationParams struct {
	IntegrationInstallID uuid.UUID
	ProjectID            uuid.UUID
	IntegrationAppID     uuid.UUID
	ID                   uuid.UUID
	LeaseToken           uuid.UUID
	LeaseGeneration      int64
}

func (q *Queries) LockIntegrationRuntimeLeaseForMutation(ctx context.Context, arg LockIntegrationRuntimeLeaseForMutationParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockIntegrationRuntimeLeaseForMutation,
		arg.IntegrationInstallID,
		arg.ProjectID,
		arg.IntegrationAppID,
		arg.ID,
		arg.LeaseToken,
		arg.LeaseGeneration,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const releaseIntegrationRuntimeUnit = `-- name: ReleaseIntegrationRuntimeUnit :one
UPDATE integration_runtime_units unit
SET status = CASE
      WHEN desired_state = 'stopped' THEN 'stopped'
      WHEN $1::jsonb = '{}'::jsonb THEN 'idle'
      ELSE 'error'
    END,
    checkpoint = CASE WHEN $2::boolean
      THEN $3::jsonb ELSE checkpoint END,
    checkpoint_version = CASE WHEN $2::boolean
      THEN $4::integer ELSE checkpoint_version END,
    checkpoint_revision = CASE WHEN $2::boolean
      THEN checkpoint_revision + 1 ELSE checkpoint_revision END,
    lease_owner = NULL,
    lease_token = NULL,
    leased_at = NULL,
    renewed_at = NULL,
    lease_expires_at = NULL,
    lease_spec_revision = NULL,
    lease_app_configuration_revision = NULL,
    lease_install_configuration_revision = NULL,
    last_error = $1,
    failure_count = CASE
      WHEN $1::jsonb = '{}'::jsonb THEN 0
      ELSE least(unit.failure_count + 1, 30)
    END,
    available_at = CASE
      WHEN desired_state = 'stopped' OR $1::jsonb = '{}'::jsonb
        THEN statement_timestamp()
      ELSE statement_timestamp() + make_interval(
        secs => least(300.0, 5.0 * power(2.0, least(unit.failure_count, 6))) *
          (
            0.8 + 0.4 * (
              (hashtextextended(unit.id::text, unit.failure_count::bigint) & 2147483647)::double precision /
              2147483647.0
            )
          )
      )
    END,
    updated_at = statement_timestamp()
WHERE unit.id = $5
  AND unit.lease_token = $6::uuid
  AND unit.lease_generation = $7
  AND unit.spec_revision = unit.lease_spec_revision
  AND unit.desired_state = 'running'
  AND unit.lease_expires_at > statement_timestamp()
  AND unit.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM integration_apps app
    WHERE app.org_id = unit.org_id
      AND app.id = unit.integration_app_id
      AND EXISTS (
        SELECT 1
        FROM generate_subscripts($8::text[], 1) AS capability(index)
        WHERE ($8::text[])[capability.index] = unit.connector_key
          AND ($9::text[])[capability.index] = unit.provider
      )
      AND app.configuration_revision = unit.lease_app_configuration_revision
      AND app.state = 'active'
      AND app.deleted_at IS NULL
  )
  AND (
    unit.integration_install_id IS NULL
    OR EXISTS (
      SELECT 1
      FROM integration_installs install
      WHERE install.org_id = unit.org_id
        AND install.project_id = unit.project_id
        AND install.id = unit.integration_install_id
        AND install.integration_app_id = unit.integration_app_id
        AND install.configuration_revision = unit.lease_install_configuration_revision
        AND install.state = 'active'
        AND install.deleted_at IS NULL
    )
  )
RETURNING unit.id, unit.org_id, unit.integration_app_id, unit.project_id,
  unit.integration_install_id, unit.provider, unit.connector_key,
  unit.unit_key, unit.runtime_kind, unit.desired_state,
  unit.spec_revision, unit.configuration, unit.status, unit.failure_count,
  unit.available_at, unit.lease_owner,
  unit.lease_token, unit.lease_generation, unit.leased_at, unit.renewed_at,
  unit.lease_expires_at, unit.lease_spec_revision, unit.lease_app_configuration_revision,
  unit.lease_install_configuration_revision, unit.checkpoint_version, unit.checkpoint_revision,
  unit.checkpoint, unit.last_error, unit.deleted_at, unit.created_at, unit.updated_at
`

type ReleaseIntegrationRuntimeUnitParams struct {
	Error             json.RawMessage
	WriteCheckpoint   bool
	Checkpoint        json.RawMessage
	CheckpointVersion int32
	ID                uuid.UUID
	LeaseToken        uuid.UUID
	LeaseGeneration   int64
	ConnectorKeys     []string
	Providers         []string
}

func (q *Queries) ReleaseIntegrationRuntimeUnit(ctx context.Context, arg ReleaseIntegrationRuntimeUnitParams) (IntegrationRuntimeUnit, error) {
	row := q.db.QueryRow(ctx, releaseIntegrationRuntimeUnit,
		arg.Error,
		arg.WriteCheckpoint,
		arg.Checkpoint,
		arg.CheckpointVersion,
		arg.ID,
		arg.LeaseToken,
		arg.LeaseGeneration,
		arg.ConnectorKeys,
		arg.Providers,
	)
	var i IntegrationRuntimeUnit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IntegrationAppID,
		&i.ProjectID,
		&i.IntegrationInstallID,
		&i.Provider,
		&i.ConnectorKey,
		&i.UnitKey,
		&i.RuntimeKind,
		&i.DesiredState,
		&i.SpecRevision,
		&i.Configuration,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseGeneration,
		&i.LeasedAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.LeaseSpecRevision,
		&i.LeaseAppConfigurationRevision,
		&i.LeaseInstallConfigurationRevision,
		&i.CheckpointVersion,
		&i.CheckpointRevision,
		&i.Checkpoint,
		&i.LastError,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const relinquishStaleIntegrationRuntimeUnit = `-- name: RelinquishStaleIntegrationRuntimeUnit :one
UPDATE integration_runtime_units unit
SET status = CASE WHEN desired_state = 'stopped' THEN 'stopped' ELSE 'idle' END,
    lease_owner = NULL,
    lease_token = NULL,
    leased_at = NULL,
    renewed_at = NULL,
    lease_expires_at = NULL,
    lease_spec_revision = NULL,
    lease_app_configuration_revision = NULL,
    lease_install_configuration_revision = NULL,
    available_at = statement_timestamp(),
    updated_at = statement_timestamp()
WHERE unit.id = $1
  AND unit.lease_token = $2::uuid
  AND unit.lease_generation = $3
  AND unit.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM integration_apps app
    WHERE app.org_id = unit.org_id
      AND app.id = unit.integration_app_id
      AND EXISTS (
        SELECT 1
        FROM generate_subscripts($4::text[], 1) AS capability(index)
        WHERE ($4::text[])[capability.index] = unit.connector_key
          AND ($5::text[])[capability.index] = unit.provider
      )
  )
RETURNING unit.id, unit.org_id, unit.integration_app_id, unit.project_id,
  unit.integration_install_id, unit.provider, unit.connector_key,
  unit.unit_key, unit.runtime_kind, unit.desired_state,
  unit.spec_revision, unit.configuration, unit.status, unit.failure_count,
  unit.available_at, unit.lease_owner,
  unit.lease_token, unit.lease_generation, unit.leased_at, unit.renewed_at,
  unit.lease_expires_at, unit.lease_spec_revision, unit.lease_app_configuration_revision,
  unit.lease_install_configuration_revision, unit.checkpoint_version, unit.checkpoint_revision,
  unit.checkpoint, unit.last_error, unit.deleted_at, unit.created_at, unit.updated_at
`

type RelinquishStaleIntegrationRuntimeUnitParams struct {
	ID              uuid.UUID
	LeaseToken      uuid.UUID
	LeaseGeneration int64
	ConnectorKeys   []string
	Providers       []string
}

// A worker that notices its snapshot is stale should relinquish ownership
// promptly, but it must not publish an obsolete checkpoint, provider outcome,
// failure count, or retry delay. The lease token/generation still makes this a
// fenced compare-and-swap; a replacement that already claimed the unit wins.
func (q *Queries) RelinquishStaleIntegrationRuntimeUnit(ctx context.Context, arg RelinquishStaleIntegrationRuntimeUnitParams) (IntegrationRuntimeUnit, error) {
	row := q.db.QueryRow(ctx, relinquishStaleIntegrationRuntimeUnit,
		arg.ID,
		arg.LeaseToken,
		arg.LeaseGeneration,
		arg.ConnectorKeys,
		arg.Providers,
	)
	var i IntegrationRuntimeUnit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IntegrationAppID,
		&i.ProjectID,
		&i.IntegrationInstallID,
		&i.Provider,
		&i.ConnectorKey,
		&i.UnitKey,
		&i.RuntimeKind,
		&i.DesiredState,
		&i.SpecRevision,
		&i.Configuration,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseGeneration,
		&i.LeasedAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.LeaseSpecRevision,
		&i.LeaseAppConfigurationRevision,
		&i.LeaseInstallConfigurationRevision,
		&i.CheckpointVersion,
		&i.CheckpointRevision,
		&i.Checkpoint,
		&i.LastError,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIntegrationAppRuntimeUnit = `-- name: UpsertIntegrationAppRuntimeUnit :one
INSERT INTO integration_runtime_units(
  org_id, integration_app_id, project_id, integration_install_id,
  provider, connector_key, unit_key, runtime_kind, desired_state, spec_revision,
  configuration, status, failure_count, available_at, created_at, updated_at
)
SELECT
  $1, app.id, NULL, NULL, app.provider, app.connector_key,
  $2, $3,
  $4, $5,
  $6,
  CASE WHEN $4::text = 'stopped' THEN 'stopped' ELSE 'idle' END,
  0, transaction_timestamp(), transaction_timestamp(), transaction_timestamp()
FROM integration_apps app
WHERE app.org_id = $1
  AND app.id = $7
  AND app.deleted_at IS NULL
  AND ($4::text <> 'running' OR app.state = 'active')
ON CONFLICT (integration_app_id, unit_key)
  WHERE project_id IS NULL AND deleted_at IS NULL
DO UPDATE SET
  desired_state = excluded.desired_state,
  spec_revision = excluded.spec_revision,
  configuration = excluded.configuration,
  failure_count = CASE
    WHEN integration_runtime_units.spec_revision IS DISTINCT FROM excluded.spec_revision
      OR integration_runtime_units.configuration IS DISTINCT FROM excluded.configuration
      OR integration_runtime_units.desired_state IS DISTINCT FROM excluded.desired_state
      THEN 0
    ELSE integration_runtime_units.failure_count
  END,
  available_at = CASE
    WHEN integration_runtime_units.spec_revision IS DISTINCT FROM excluded.spec_revision
      OR integration_runtime_units.configuration IS DISTINCT FROM excluded.configuration
      OR integration_runtime_units.desired_state IS DISTINCT FROM excluded.desired_state
      THEN statement_timestamp()
    ELSE integration_runtime_units.available_at
  END,
  status = CASE
    WHEN excluded.desired_state = 'stopped' THEN 'stopped'
    WHEN integration_runtime_units.status = 'stopped' THEN 'idle'
    ELSE integration_runtime_units.status
  END,
  lease_owner = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_owner END,
  lease_token = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_token END,
  leased_at = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.leased_at END,
  renewed_at = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.renewed_at END,
  lease_expires_at = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_expires_at END,
  lease_spec_revision = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_spec_revision END,
  lease_app_configuration_revision = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_app_configuration_revision END,
  lease_install_configuration_revision = NULL,
  updated_at = statement_timestamp()
WHERE integration_runtime_units.deleted_at IS NULL
  AND integration_runtime_units.org_id = excluded.org_id
  AND integration_runtime_units.project_id IS NULL
  AND integration_runtime_units.integration_install_id IS NULL
  AND integration_runtime_units.runtime_kind = excluded.runtime_kind
  AND (
    excluded.spec_revision > integration_runtime_units.spec_revision
    OR (
      excluded.spec_revision = integration_runtime_units.spec_revision
      AND excluded.configuration = integration_runtime_units.configuration
    )
  )
RETURNING id, org_id, integration_app_id, project_id, integration_install_id,
  provider, connector_key, unit_key, runtime_kind, desired_state, spec_revision, configuration,
  status, failure_count, available_at, lease_owner, lease_token, lease_generation, leased_at, renewed_at,
  lease_expires_at, lease_spec_revision, lease_app_configuration_revision,
  lease_install_configuration_revision, checkpoint_version, checkpoint_revision, checkpoint,
  last_error, deleted_at, created_at, updated_at
`

type UpsertIntegrationAppRuntimeUnitParams struct {
	OrgID            uuid.UUID
	UnitKey          string
	RuntimeKind      string
	DesiredState     string
	SpecRevision     int32
	Configuration    json.RawMessage
	IntegrationAppID uuid.UUID
}

func (q *Queries) UpsertIntegrationAppRuntimeUnit(ctx context.Context, arg UpsertIntegrationAppRuntimeUnitParams) (IntegrationRuntimeUnit, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationAppRuntimeUnit,
		arg.OrgID,
		arg.UnitKey,
		arg.RuntimeKind,
		arg.DesiredState,
		arg.SpecRevision,
		arg.Configuration,
		arg.IntegrationAppID,
	)
	var i IntegrationRuntimeUnit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IntegrationAppID,
		&i.ProjectID,
		&i.IntegrationInstallID,
		&i.Provider,
		&i.ConnectorKey,
		&i.UnitKey,
		&i.RuntimeKind,
		&i.DesiredState,
		&i.SpecRevision,
		&i.Configuration,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseGeneration,
		&i.LeasedAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.LeaseSpecRevision,
		&i.LeaseAppConfigurationRevision,
		&i.LeaseInstallConfigurationRevision,
		&i.CheckpointVersion,
		&i.CheckpointRevision,
		&i.Checkpoint,
		&i.LastError,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIntegrationInstallRuntimeUnit = `-- name: UpsertIntegrationInstallRuntimeUnit :one
INSERT INTO integration_runtime_units(
  org_id, integration_app_id, project_id, integration_install_id,
  provider, connector_key, unit_key, runtime_kind, desired_state, spec_revision,
  configuration, status, failure_count, available_at, created_at, updated_at
)
SELECT
  $1, app.id, install.project_id, install.id,
  app.provider, app.connector_key, $2, $3,
  $4, $5, $6,
  CASE WHEN $4::text = 'stopped' THEN 'stopped' ELSE 'idle' END,
  0, transaction_timestamp(), transaction_timestamp(), transaction_timestamp()
FROM integration_installs install
JOIN integration_apps app
  ON app.org_id = install.org_id
 AND app.id = install.integration_app_id
 AND app.deleted_at IS NULL
WHERE install.org_id = $1
  AND install.project_id = $7::uuid
  AND install.id = $8
  AND install.integration_app_id = $9
  AND install.deleted_at IS NULL
  AND (
    $4::text <> 'running'
    OR (app.state = 'active' AND install.state = 'active')
  )
ON CONFLICT (integration_app_id, integration_install_id, unit_key)
  WHERE project_id IS NOT NULL AND deleted_at IS NULL
DO UPDATE SET
  desired_state = excluded.desired_state,
  spec_revision = excluded.spec_revision,
  configuration = excluded.configuration,
  failure_count = CASE
    WHEN integration_runtime_units.spec_revision IS DISTINCT FROM excluded.spec_revision
      OR integration_runtime_units.configuration IS DISTINCT FROM excluded.configuration
      OR integration_runtime_units.desired_state IS DISTINCT FROM excluded.desired_state
      THEN 0
    ELSE integration_runtime_units.failure_count
  END,
  available_at = CASE
    WHEN integration_runtime_units.spec_revision IS DISTINCT FROM excluded.spec_revision
      OR integration_runtime_units.configuration IS DISTINCT FROM excluded.configuration
      OR integration_runtime_units.desired_state IS DISTINCT FROM excluded.desired_state
      THEN statement_timestamp()
    ELSE integration_runtime_units.available_at
  END,
  status = CASE
    WHEN excluded.desired_state = 'stopped' THEN 'stopped'
    WHEN integration_runtime_units.status = 'stopped' THEN 'idle'
    ELSE integration_runtime_units.status
  END,
  lease_owner = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_owner END,
  lease_token = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_token END,
  leased_at = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.leased_at END,
  renewed_at = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.renewed_at END,
  lease_expires_at = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_expires_at END,
  lease_spec_revision = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_spec_revision END,
  lease_app_configuration_revision = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_app_configuration_revision END,
  lease_install_configuration_revision = CASE WHEN excluded.desired_state = 'stopped'
    THEN NULL ELSE integration_runtime_units.lease_install_configuration_revision END,
  updated_at = statement_timestamp()
WHERE integration_runtime_units.deleted_at IS NULL
  AND integration_runtime_units.org_id = excluded.org_id
  AND integration_runtime_units.project_id = excluded.project_id
  AND integration_runtime_units.integration_install_id = excluded.integration_install_id
  AND integration_runtime_units.runtime_kind = excluded.runtime_kind
  AND (
    excluded.spec_revision > integration_runtime_units.spec_revision
    OR (
      excluded.spec_revision = integration_runtime_units.spec_revision
      AND excluded.configuration = integration_runtime_units.configuration
    )
  )
RETURNING id, org_id, integration_app_id, project_id, integration_install_id,
  provider, connector_key, unit_key, runtime_kind, desired_state, spec_revision, configuration,
  status, failure_count, available_at, lease_owner, lease_token, lease_generation, leased_at, renewed_at,
  lease_expires_at, lease_spec_revision, lease_app_configuration_revision,
  lease_install_configuration_revision, checkpoint_version, checkpoint_revision, checkpoint,
  last_error, deleted_at, created_at, updated_at
`

type UpsertIntegrationInstallRuntimeUnitParams struct {
	OrgID                uuid.UUID
	UnitKey              string
	RuntimeKind          string
	DesiredState         string
	SpecRevision         int32
	Configuration        json.RawMessage
	ProjectID            uuid.UUID
	IntegrationInstallID uuid.UUID
	IntegrationAppID     uuid.UUID
}

func (q *Queries) UpsertIntegrationInstallRuntimeUnit(ctx context.Context, arg UpsertIntegrationInstallRuntimeUnitParams) (IntegrationRuntimeUnit, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationInstallRuntimeUnit,
		arg.OrgID,
		arg.UnitKey,
		arg.RuntimeKind,
		arg.DesiredState,
		arg.SpecRevision,
		arg.Configuration,
		arg.ProjectID,
		arg.IntegrationInstallID,
		arg.IntegrationAppID,
	)
	var i IntegrationRuntimeUnit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.IntegrationAppID,
		&i.ProjectID,
		&i.IntegrationInstallID,
		&i.Provider,
		&i.ConnectorKey,
		&i.UnitKey,
		&i.RuntimeKind,
		&i.DesiredState,
		&i.SpecRevision,
		&i.Configuration,
		&i.Status,
		&i.FailureCount,
		&i.AvailableAt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseGeneration,
		&i.LeasedAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.LeaseSpecRevision,
		&i.LeaseAppConfigurationRevision,
		&i.LeaseInstallConfigurationRevision,
		&i.CheckpointVersion,
		&i.CheckpointRevision,
		&i.Checkpoint,
		&i.LastError,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
