// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_interactions.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getInteractionCallbackAgent = `-- name: GetInteractionCallbackAgent :one
SELECT agent_id
FROM agent_interaction_read_projection
WHERE project_id = $1 AND id = $2
  AND destination ->> 'integration_id' = $3::text
`

type GetInteractionCallbackAgentParams struct {
	ProjectID     uuid.UUID
	InteractionID uuid.UUID
	IntegrationID string
}

func (q *Queries) GetInteractionCallbackAgent(ctx context.Context, arg GetInteractionCallbackAgentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getInteractionCallbackAgent, arg.ProjectID, arg.InteractionID, arg.IntegrationID)
	var agent_id uuid.UUID
	err := row.Scan(&agent_id)
	return agent_id, err
}

const getInteractionCallbackIntegrationID = `-- name: GetInteractionCallbackIntegrationID :one
SELECT (destination ->> 'integration_id')::uuid AS integration_id
FROM agent_interactions
WHERE id = $1 AND destination ->> 'integration_id' IS NOT NULL
`

type GetInteractionCallbackIntegrationIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetInteractionCallbackIntegrationID(ctx context.Context, arg GetInteractionCallbackIntegrationIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getInteractionCallbackIntegrationID, arg.ID)
	var integration_id uuid.UUID
	err := row.Scan(&integration_id)
	return integration_id, err
}

const getInteractionDestinationTarget = `-- name: GetInteractionDestinationTarget :one
SELECT target.id, target.integration_id AS integration_id,
       target.provider_ref_kind, target.provider_ref, target.display_name,
       integration.state AS integration_state
FROM integration_targets target
JOIN project_integrations integration
  ON integration.project_id = target.project_id AND integration.id = target.integration_id
WHERE target.project_id = $1 AND target.agent_id = $2
  AND target.id = $3 AND target.deleted_at IS NULL
  AND integration.deleted_at IS NULL
`

type GetInteractionDestinationTargetParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	TargetID  uuid.UUID
}

type GetInteractionDestinationTargetRow struct {
	ID               uuid.UUID
	IntegrationID    uuid.UUID
	ProviderRefKind  string
	ProviderRef      string
	DisplayName      string
	IntegrationState string
}

func (q *Queries) GetInteractionDestinationTarget(ctx context.Context, arg GetInteractionDestinationTargetParams) (GetInteractionDestinationTargetRow, error) {
	row := q.db.QueryRow(ctx, getInteractionDestinationTarget, arg.ProjectID, arg.AgentID, arg.TargetID)
	var i GetInteractionDestinationTargetRow
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.ProviderRefKind,
		&i.ProviderRef,
		&i.DisplayName,
		&i.IntegrationState,
	)
	return i, err
}

const getInteractionSelection = `-- name: GetInteractionSelection :one
SELECT current_config_id, integration_target_id,
       coalesce(interaction_handler_key, '') AS handler_key, interaction_handler_args AS handler_args
FROM agents
WHERE project_id = $1 AND id = $2
`

type GetInteractionSelectionParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type GetInteractionSelectionRow struct {
	CurrentConfigID     uuid.UUID
	IntegrationTargetID *uuid.UUID
	HandlerKey          string
	HandlerArgs         *json.RawMessage
}

func (q *Queries) GetInteractionSelection(ctx context.Context, arg GetInteractionSelectionParams) (GetInteractionSelectionRow, error) {
	row := q.db.QueryRow(ctx, getInteractionSelection, arg.ProjectID, arg.AgentID)
	var i GetInteractionSelectionRow
	err := row.Scan(
		&i.CurrentConfigID,
		&i.IntegrationTargetID,
		&i.HandlerKey,
		&i.HandlerArgs,
	)
	return i, err
}

const recordAgentInteractionPresentationReceipt = `-- name: RecordAgentInteractionPresentationReceipt :execrows
UPDATE agent_interactions interaction
SET presentation_receipt = $1::jsonb
WHERE interaction.agent_id = $2 AND interaction.id = $3
  AND interaction.destination = $4::jsonb
  AND interaction.presentation_receipt IS NULL
  AND EXISTS (
    SELECT 1 FROM agents agent
    WHERE agent.project_id = $5 AND agent.id = interaction.agent_id
  )
`

type RecordAgentInteractionPresentationReceiptParams struct {
	Receipt     json.RawMessage
	AgentID     uuid.UUID
	ID          uuid.UUID
	Destination json.RawMessage
	ProjectID   uuid.UUID
}

func (q *Queries) RecordAgentInteractionPresentationReceipt(ctx context.Context, arg RecordAgentInteractionPresentationReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAgentInteractionPresentationReceipt,
		arg.Receipt,
		arg.AgentID,
		arg.ID,
		arg.Destination,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInteractionSelection = `-- name: SetInteractionSelection :execrows
UPDATE agents
SET integration_target_id = $1::uuid,
    interaction_handler_key = $2::text,
    interaction_handler_args = $3::jsonb,
    updated_at = statement_timestamp()
WHERE agents.project_id = $4 AND agents.id = $5
  AND (($1::uuid IS NULL AND $2::text IS NULL AND $3::jsonb IS NULL)
    OR ($2::text <> '' AND jsonb_typeof($3::jsonb) = 'object' AND EXISTS (
      SELECT 1 FROM integration_targets target
      JOIN project_integrations integration
        ON integration.project_id = target.project_id
       AND integration.id = target.integration_id
      WHERE target.project_id = agents.project_id AND target.agent_id = agents.id
        AND target.id = $1::uuid AND target.deleted_at IS NULL
        AND integration.deleted_at IS NULL AND integration.state = 'active'
    )))
`

type SetInteractionSelectionParams struct {
	TargetID    *uuid.UUID
	HandlerKey  *string
	HandlerArgs *json.RawMessage
	ProjectID   uuid.UUID
	AgentID     uuid.UUID
}

func (q *Queries) SetInteractionSelection(ctx context.Context, arg SetInteractionSelectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInteractionSelection,
		arg.TargetID,
		arg.HandlerKey,
		arg.HandlerArgs,
		arg.ProjectID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
