// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kernel_event_authority.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getModelOutputByModelContext = `-- name: GetModelOutputByModelContext :one
SELECT output.id, agent.project_id, output.agent_id,
  (
    SELECT context_turn.turn_id
    FROM model_call_context_turns context_turn
    WHERE context_turn.project_id = agent.project_id
      AND context_turn.agent_id = output.agent_id
      AND context_turn.model_call_context_id = output.model_call_context_id
  ) AS turn_id,
  output.model_call_context_id,
  output.served_provider_model_slug,
  output.stop_reason, context.provider_response_id,
  output.provider_replay,
  context.input_tokens_total, context.uncached_input_tokens,
  context.cache_read_input_tokens, context.cache_write_input_tokens,
  context.output_tokens_total, context.reasoning_output_tokens,
  output.created_at
FROM model_outputs output
JOIN agents agent ON agent.id = output.agent_id
JOIN model_call_contexts context ON context.project_id = agent.project_id
  AND context.agent_id = output.agent_id
  AND context.id = output.model_call_context_id
WHERE agent.project_id = $1
  AND output.agent_id = $2
  AND output.model_call_context_id = $3
`

type GetModelOutputByModelContextParams struct {
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	ModelCallContextID uuid.UUID
}

type GetModelOutputByModelContextRow struct {
	ID                      uuid.UUID
	ProjectID               uuid.UUID
	AgentID                 uuid.UUID
	TurnID                  uuid.UUID
	ModelCallContextID      uuid.UUID
	ServedProviderModelSlug string
	StopReason              string
	ProviderResponseID      string
	ProviderReplay          *json.RawMessage
	InputTokensTotal        *int32
	UncachedInputTokens     *int32
	CacheReadInputTokens    *int32
	CacheWriteInputTokens   *int32
	OutputTokensTotal       *int32
	ReasoningOutputTokens   *int32
	CreatedAt               time.Time
}

func (q *Queries) GetModelOutputByModelContext(ctx context.Context, arg GetModelOutputByModelContextParams) (GetModelOutputByModelContextRow, error) {
	row := q.db.QueryRow(ctx, getModelOutputByModelContext, arg.ProjectID, arg.AgentID, arg.ModelCallContextID)
	var i GetModelOutputByModelContextRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.ModelCallContextID,
		&i.ServedProviderModelSlug,
		&i.StopReason,
		&i.ProviderResponseID,
		&i.ProviderReplay,
		&i.InputTokensTotal,
		&i.UncachedInputTokens,
		&i.CacheReadInputTokens,
		&i.CacheWriteInputTokens,
		&i.OutputTokensTotal,
		&i.ReasoningOutputTokens,
		&i.CreatedAt,
	)
	return i, err
}

const getToolCallProviderCallID = `-- name: GetToolCallProviderCallID :one
SELECT provider_call_id
FROM tool_call_read_projection
WHERE project_id = $1
  AND agent_id = $2
  AND id = $3
`

type GetToolCallProviderCallIDParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetToolCallProviderCallID(ctx context.Context, arg GetToolCallProviderCallIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getToolCallProviderCallID, arg.ProjectID, arg.AgentID, arg.ID)
	var provider_call_id string
	err := row.Scan(&provider_call_id)
	return provider_call_id, err
}

const getToolCallResultByToolCall = `-- name: GetToolCallResultByToolCall :one
SELECT result.id, agent.project_id, result.agent_id,
  source_event.turn_id AS turn_id,
  result.tool_call_id, result.outcome, result.completed_at
FROM tool_call_results result
JOIN agents agent ON agent.id = result.agent_id
JOIN tool_calls tool_call ON tool_call.agent_id = result.agent_id
  AND tool_call.id = result.tool_call_id
JOIN agent_events source_event ON source_event.agent_id = tool_call.agent_id
  AND source_event.model_output_id = tool_call.model_output_id
  AND source_event.event_kind = 'model_output'
WHERE agent.project_id = $1
  AND result.agent_id = $2
  AND result.tool_call_id = $3
`

type GetToolCallResultByToolCallParams struct {
	ProjectID  uuid.UUID
	AgentID    uuid.UUID
	ToolCallID uuid.UUID
}

type GetToolCallResultByToolCallRow struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	AgentID     uuid.UUID
	TurnID      uuid.UUID
	ToolCallID  uuid.UUID
	Outcome     string
	CompletedAt time.Time
}

func (q *Queries) GetToolCallResultByToolCall(ctx context.Context, arg GetToolCallResultByToolCallParams) (GetToolCallResultByToolCallRow, error) {
	row := q.db.QueryRow(ctx, getToolCallResultByToolCall, arg.ProjectID, arg.AgentID, arg.ToolCallID)
	var i GetToolCallResultByToolCallRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.ToolCallID,
		&i.Outcome,
		&i.CompletedAt,
	)
	return i, err
}

const getTypedAgentEventByIdempotency = `-- name: GetTypedAgentEventByIdempotency :one
SELECT event.id, event.agent_id, event.turn_id, event.is_opening_event,
       event.sequence, event.event_kind, event.created_at,
       coalesce(event.idempotency_key, '') AS idempotency_key,
       event.agent_input_id, event.model_output_id, event.tool_call_result_id,
       event.context_checkpoint_id
FROM agent_events event
JOIN agents agent ON agent.id = event.agent_id
WHERE agent.project_id = $1
  AND event.agent_id = $2
  AND event.idempotency_key = $3::text
`

type GetTypedAgentEventByIdempotencyParams struct {
	ProjectID      uuid.UUID
	AgentID        uuid.UUID
	IdempotencyKey string
}

type GetTypedAgentEventByIdempotencyRow struct {
	ID                  uuid.UUID
	AgentID             uuid.UUID
	TurnID              uuid.UUID
	IsOpeningEvent      bool
	Sequence            int64
	EventKind           string
	CreatedAt           time.Time
	IdempotencyKey      string
	AgentInputID        *uuid.UUID
	ModelOutputID       *uuid.UUID
	ToolCallResultID    *uuid.UUID
	ContextCheckpointID *uuid.UUID
}

func (q *Queries) GetTypedAgentEventByIdempotency(ctx context.Context, arg GetTypedAgentEventByIdempotencyParams) (GetTypedAgentEventByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getTypedAgentEventByIdempotency, arg.ProjectID, arg.AgentID, arg.IdempotencyKey)
	var i GetTypedAgentEventByIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TurnID,
		&i.IsOpeningEvent,
		&i.Sequence,
		&i.EventKind,
		&i.CreatedAt,
		&i.IdempotencyKey,
		&i.AgentInputID,
		&i.ModelOutputID,
		&i.ToolCallResultID,
		&i.ContextCheckpointID,
	)
	return i, err
}

const getTypedAgentEventByModelOutput = `-- name: GetTypedAgentEventByModelOutput :one
SELECT event.id, event.agent_id, event.turn_id, event.is_opening_event,
       event.sequence, event.event_kind, event.created_at,
       coalesce(event.idempotency_key, '') AS idempotency_key,
       event.agent_input_id, event.model_output_id, event.tool_call_result_id,
       event.context_checkpoint_id
FROM agent_events event
JOIN agents agent ON agent.id = event.agent_id
WHERE agent.project_id = $1
  AND event.agent_id = $2
  AND event.model_output_id = $3
`

type GetTypedAgentEventByModelOutputParams struct {
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	ModelOutputID *uuid.UUID
}

type GetTypedAgentEventByModelOutputRow struct {
	ID                  uuid.UUID
	AgentID             uuid.UUID
	TurnID              uuid.UUID
	IsOpeningEvent      bool
	Sequence            int64
	EventKind           string
	CreatedAt           time.Time
	IdempotencyKey      string
	AgentInputID        *uuid.UUID
	ModelOutputID       *uuid.UUID
	ToolCallResultID    *uuid.UUID
	ContextCheckpointID *uuid.UUID
}

func (q *Queries) GetTypedAgentEventByModelOutput(ctx context.Context, arg GetTypedAgentEventByModelOutputParams) (GetTypedAgentEventByModelOutputRow, error) {
	row := q.db.QueryRow(ctx, getTypedAgentEventByModelOutput, arg.ProjectID, arg.AgentID, arg.ModelOutputID)
	var i GetTypedAgentEventByModelOutputRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TurnID,
		&i.IsOpeningEvent,
		&i.Sequence,
		&i.EventKind,
		&i.CreatedAt,
		&i.IdempotencyKey,
		&i.AgentInputID,
		&i.ModelOutputID,
		&i.ToolCallResultID,
		&i.ContextCheckpointID,
	)
	return i, err
}

const insertConfigChangeAgentInput = `-- name: InsertConfigChangeAgentInput :one
WITH generated AS (
  SELECT uuidv7() AS id
),
inserted AS (
INSERT INTO agent_inputs(
  id, project_id, agent_id, state,
  actor_id, input_kind, delivery_mode,
  agent_config_id, idempotency_scope, input_idempotency_key, queued_at, metadata
)
SELECT generated.id, agent.project_id, agent.id, 'received',
       $1::uuid, 'config_change', 'immediate',
       $2,
       $3, $4,
       statement_timestamp(), $5
FROM agents agent
JOIN generated ON true
WHERE agent.project_id = $6
  AND agent.id = $7
ON CONFLICT DO NOTHING
RETURNING id, project_id, agent_id,
  state, input_rank, actor_id, input_kind,
  coalesce(idempotency_scope, '') AS idempotency_scope,
  coalesce(input_idempotency_key, '') AS input_idempotency_key,
  queued_at, admitted_event_id, admitted_at, canceled_at, delivery_mode,
  coalesce(control_type, '') AS control_type, target_interaction_id, agent_config_id, resolved_at,
  coalesce(rejected_reason, '') AS rejected_reason, metadata
)
SELECT id, project_id, agent_id,
  state, input_rank, actor_id, input_kind,
  idempotency_scope,
  input_idempotency_key,
  queued_at, admitted_event_id, admitted_at, canceled_at, delivery_mode,
  control_type, target_interaction_id, agent_config_id, resolved_at,
  rejected_reason, metadata
FROM inserted
UNION ALL
SELECT id, project_id, agent_id,
  state, input_rank, actor_id, input_kind,
  coalesce(idempotency_scope, '') AS idempotency_scope,
  coalesce(input_idempotency_key, '') AS input_idempotency_key,
  queued_at, admitted_event_id, admitted_at, canceled_at, delivery_mode,
  coalesce(control_type, '') AS control_type, target_interaction_id, agent_config_id, resolved_at,
  coalesce(rejected_reason, '') AS rejected_reason, metadata
FROM agent_inputs
WHERE project_id = $6
  AND agent_id = $7
  AND idempotency_scope = $3
  AND input_idempotency_key = $4
LIMIT 1
`

type InsertConfigChangeAgentInputParams struct {
	ActorID             *uuid.UUID
	AgentConfigID       *uuid.UUID
	IdempotencyScope    *string
	InputIdempotencyKey *string
	Metadata            json.RawMessage
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
}

type InsertConfigChangeAgentInputRow struct {
	ID                  uuid.UUID
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
	State               string
	InputRank           int64
	ActorID             *uuid.UUID
	InputKind           string
	IdempotencyScope    string
	InputIdempotencyKey string
	QueuedAt            time.Time
	AdmittedEventID     *uuid.UUID
	AdmittedAt          *time.Time
	CanceledAt          *time.Time
	DeliveryMode        string
	ControlType         string
	TargetInteractionID *uuid.UUID
	AgentConfigID       *uuid.UUID
	ResolvedAt          *time.Time
	RejectedReason      string
	Metadata            json.RawMessage
}

func (q *Queries) InsertConfigChangeAgentInput(ctx context.Context, arg InsertConfigChangeAgentInputParams) (InsertConfigChangeAgentInputRow, error) {
	row := q.db.QueryRow(ctx, insertConfigChangeAgentInput,
		arg.ActorID,
		arg.AgentConfigID,
		arg.IdempotencyScope,
		arg.InputIdempotencyKey,
		arg.Metadata,
		arg.ProjectID,
		arg.AgentID,
	)
	var i InsertConfigChangeAgentInputRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.State,
		&i.InputRank,
		&i.ActorID,
		&i.InputKind,
		&i.IdempotencyScope,
		&i.InputIdempotencyKey,
		&i.QueuedAt,
		&i.AdmittedEventID,
		&i.AdmittedAt,
		&i.CanceledAt,
		&i.DeliveryMode,
		&i.ControlType,
		&i.TargetInteractionID,
		&i.AgentConfigID,
		&i.ResolvedAt,
		&i.RejectedReason,
		&i.Metadata,
	)
	return i, err
}

const insertContentBlock = `-- name: InsertContentBlock :one
WITH content_owner AS (
  SELECT input.queued_at AS created_at
  FROM agent_inputs input
  WHERE input.project_id = $1
    AND input.agent_id = $2
    AND input.id = $3::uuid

  UNION ALL

  SELECT output.created_at
  FROM model_outputs output
  JOIN agents agent ON agent.id = output.agent_id
  WHERE agent.project_id = $1
    AND output.agent_id = $2
    AND output.id = $4::uuid

  UNION ALL

  SELECT result.completed_at
  FROM tool_call_results result
  JOIN agents agent ON agent.id = result.agent_id
  WHERE agent.project_id = $1
    AND result.agent_id = $2
    AND result.id = $5::uuid
),
inserted AS (
  INSERT INTO content_blocks(
    agent_id, owner_kind, owner_agent_input_id,
    owner_model_output_id, owner_tool_call_result_id, ordinal, block_kind,
    text_content, structured_data, artifact_id, tool_call_id,
    exclude_from_model_context, metadata, created_at
  )
  SELECT
    $2, $6,
    $3::uuid, $4::uuid,
    $5::uuid, $7, $8,
    $9, $10::jsonb, $11::uuid, $12::uuid,
    $13, $14::jsonb, content_owner.created_at
  FROM content_owner
  RETURNING id, agent_id, owner_kind, owner_agent_input_id,
            owner_model_output_id, owner_tool_call_result_id, ordinal, block_kind,
            coalesce(text_content, '') AS text_content, structured_data,
            artifact_id, tool_call_id, created_at
)
SELECT inserted.id, agent.project_id, inserted.agent_id, inserted.owner_kind,
       inserted.owner_agent_input_id, inserted.owner_model_output_id,
       inserted.owner_tool_call_result_id, inserted.ordinal, inserted.block_kind,
       inserted.text_content, inserted.structured_data, inserted.artifact_id,
       inserted.tool_call_id, inserted.created_at
FROM inserted
JOIN agents agent ON agent.id = inserted.agent_id
`

type InsertContentBlockParams struct {
	ProjectID               uuid.UUID
	AgentID                 uuid.UUID
	OwnerAgentInputID       *uuid.UUID
	OwnerModelOutputID      *uuid.UUID
	OwnerToolCallResultID   *uuid.UUID
	OwnerKind               string
	Ordinal                 int32
	BlockKind               string
	TextContent             *string
	StructuredData          *json.RawMessage
	ArtifactID              *uuid.UUID
	ToolCallID              *uuid.UUID
	ExcludeFromModelContext bool
	Metadata                json.RawMessage
}

type InsertContentBlockRow struct {
	ID                    uuid.UUID
	ProjectID             uuid.UUID
	AgentID               uuid.UUID
	OwnerKind             string
	OwnerAgentInputID     *uuid.UUID
	OwnerModelOutputID    *uuid.UUID
	OwnerToolCallResultID *uuid.UUID
	Ordinal               int32
	BlockKind             string
	TextContent           string
	StructuredData        *json.RawMessage
	ArtifactID            *uuid.UUID
	ToolCallID            *uuid.UUID
	CreatedAt             time.Time
}

func (q *Queries) InsertContentBlock(ctx context.Context, arg InsertContentBlockParams) (InsertContentBlockRow, error) {
	row := q.db.QueryRow(ctx, insertContentBlock,
		arg.ProjectID,
		arg.AgentID,
		arg.OwnerAgentInputID,
		arg.OwnerModelOutputID,
		arg.OwnerToolCallResultID,
		arg.OwnerKind,
		arg.Ordinal,
		arg.BlockKind,
		arg.TextContent,
		arg.StructuredData,
		arg.ArtifactID,
		arg.ToolCallID,
		arg.ExcludeFromModelContext,
		arg.Metadata,
	)
	var i InsertContentBlockRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.OwnerKind,
		&i.OwnerAgentInputID,
		&i.OwnerModelOutputID,
		&i.OwnerToolCallResultID,
		&i.Ordinal,
		&i.BlockKind,
		&i.TextContent,
		&i.StructuredData,
		&i.ArtifactID,
		&i.ToolCallID,
		&i.CreatedAt,
	)
	return i, err
}

const insertControlAgentInput = `-- name: InsertControlAgentInput :one
WITH generated AS (
  SELECT uuidv7() AS id
)
INSERT INTO agent_inputs(
  id, project_id, agent_id, state,
  actor_id, input_kind, delivery_mode, control_type,
  idempotency_scope, input_idempotency_key, queued_at, metadata
)
SELECT generated.id, agent.project_id, agent.id, 'received',
       $1, 'control', 'immediate',
       $2, $3, $4,
       statement_timestamp(), $5
FROM agents agent
JOIN generated ON true
WHERE agent.project_id = $6
  AND agent.id = $7
ON CONFLICT DO NOTHING
RETURNING id, project_id, agent_id,
  state, input_rank, actor_id, input_kind,
  coalesce(idempotency_scope, '') AS idempotency_scope,
  coalesce(input_idempotency_key, '') AS input_idempotency_key,
  queued_at, admitted_event_id, admitted_at, canceled_at, delivery_mode,
  coalesce(control_type, '') AS control_type, target_interaction_id, agent_config_id, resolved_at,
  coalesce(rejected_reason, '') AS rejected_reason, metadata
`

type InsertControlAgentInputParams struct {
	ActorID             *uuid.UUID
	ControlType         *string
	IdempotencyScope    *string
	InputIdempotencyKey *string
	Metadata            json.RawMessage
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
}

type InsertControlAgentInputRow struct {
	ID                  uuid.UUID
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
	State               string
	InputRank           int64
	ActorID             *uuid.UUID
	InputKind           string
	IdempotencyScope    string
	InputIdempotencyKey string
	QueuedAt            time.Time
	AdmittedEventID     *uuid.UUID
	AdmittedAt          *time.Time
	CanceledAt          *time.Time
	DeliveryMode        string
	ControlType         string
	TargetInteractionID *uuid.UUID
	AgentConfigID       *uuid.UUID
	ResolvedAt          *time.Time
	RejectedReason      string
	Metadata            json.RawMessage
}

func (q *Queries) InsertControlAgentInput(ctx context.Context, arg InsertControlAgentInputParams) (InsertControlAgentInputRow, error) {
	row := q.db.QueryRow(ctx, insertControlAgentInput,
		arg.ActorID,
		arg.ControlType,
		arg.IdempotencyScope,
		arg.InputIdempotencyKey,
		arg.Metadata,
		arg.ProjectID,
		arg.AgentID,
	)
	var i InsertControlAgentInputRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.State,
		&i.InputRank,
		&i.ActorID,
		&i.InputKind,
		&i.IdempotencyScope,
		&i.InputIdempotencyKey,
		&i.QueuedAt,
		&i.AdmittedEventID,
		&i.AdmittedAt,
		&i.CanceledAt,
		&i.DeliveryMode,
		&i.ControlType,
		&i.TargetInteractionID,
		&i.AgentConfigID,
		&i.ResolvedAt,
		&i.RejectedReason,
		&i.Metadata,
	)
	return i, err
}

const insertModelOutputAuthority = `-- name: InsertModelOutputAuthority :one
WITH inserted AS (
  INSERT INTO model_outputs(
    agent_id, model_call_context_id,
    served_provider_model_slug, stop_reason, provider_replay, created_at
  )
  SELECT agent.id, context.id,
    $1, $2,
    $3::jsonb, statement_timestamp()
  FROM agents agent
  JOIN model_call_contexts context ON context.project_id = agent.project_id
    AND context.agent_id = agent.id
    AND context.id = $4::uuid
  WHERE agent.project_id = $5
    AND agent.id = $6
  ON CONFLICT (agent_id, model_call_context_id) DO NOTHING
  RETURNING id, agent_id, model_call_context_id,
    served_provider_model_slug, stop_reason, provider_replay, created_at
)
SELECT inserted.id, agent.project_id, inserted.agent_id,
  (
    SELECT context_turn.turn_id
    FROM model_call_context_turns context_turn
    WHERE context_turn.project_id = agent.project_id
      AND context_turn.agent_id = inserted.agent_id
      AND context_turn.model_call_context_id = inserted.model_call_context_id
  ) AS turn_id,
  inserted.model_call_context_id,
  inserted.served_provider_model_slug, inserted.stop_reason,
  context.provider_response_id,
  inserted.provider_replay,
  context.input_tokens_total, context.uncached_input_tokens,
  context.cache_read_input_tokens, context.cache_write_input_tokens,
  context.output_tokens_total, context.reasoning_output_tokens,
  inserted.created_at
FROM inserted
JOIN agents agent ON agent.id = inserted.agent_id
JOIN model_call_contexts context ON context.project_id = agent.project_id
  AND context.agent_id = inserted.agent_id
  AND context.id = inserted.model_call_context_id
`

type InsertModelOutputAuthorityParams struct {
	ServedProviderModelSlug string
	StopReason              string
	ProviderReplay          *json.RawMessage
	ModelCallContextID      uuid.UUID
	ProjectID               uuid.UUID
	AgentID                 uuid.UUID
}

type InsertModelOutputAuthorityRow struct {
	ID                      uuid.UUID
	ProjectID               uuid.UUID
	AgentID                 uuid.UUID
	TurnID                  uuid.UUID
	ModelCallContextID      uuid.UUID
	ServedProviderModelSlug string
	StopReason              string
	ProviderResponseID      string
	ProviderReplay          *json.RawMessage
	InputTokensTotal        *int32
	UncachedInputTokens     *int32
	CacheReadInputTokens    *int32
	CacheWriteInputTokens   *int32
	OutputTokensTotal       *int32
	ReasoningOutputTokens   *int32
	CreatedAt               time.Time
}

func (q *Queries) InsertModelOutputAuthority(ctx context.Context, arg InsertModelOutputAuthorityParams) (InsertModelOutputAuthorityRow, error) {
	row := q.db.QueryRow(ctx, insertModelOutputAuthority,
		arg.ServedProviderModelSlug,
		arg.StopReason,
		arg.ProviderReplay,
		arg.ModelCallContextID,
		arg.ProjectID,
		arg.AgentID,
	)
	var i InsertModelOutputAuthorityRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.ModelCallContextID,
		&i.ServedProviderModelSlug,
		&i.StopReason,
		&i.ProviderResponseID,
		&i.ProviderReplay,
		&i.InputTokensTotal,
		&i.UncachedInputTokens,
		&i.CacheReadInputTokens,
		&i.CacheWriteInputTokens,
		&i.OutputTokensTotal,
		&i.ReasoningOutputTokens,
		&i.CreatedAt,
	)
	return i, err
}

const insertToolCallResultAuthority = `-- name: InsertToolCallResultAuthority :one
WITH inserted AS (
  INSERT INTO tool_call_results(
    agent_id, tool_call_id, outcome, completed_at
  )
  SELECT tool_call.agent_id, tool_call.id,
    $1, statement_timestamp()
  FROM tool_call_read_projection tool_call
  WHERE tool_call.project_id = $2
    AND tool_call.agent_id = $3
    AND tool_call.id = $4
    AND tool_call.state = 'completed'
  ON CONFLICT (agent_id, tool_call_id) DO NOTHING
  RETURNING id, agent_id, tool_call_id, outcome, completed_at
)
SELECT inserted.id, agent.project_id, inserted.agent_id,
       source_event.turn_id, inserted.tool_call_id, inserted.outcome,
       inserted.completed_at
FROM inserted
JOIN agents agent ON agent.id = inserted.agent_id
JOIN tool_calls tool_call ON tool_call.agent_id = inserted.agent_id
  AND tool_call.id = inserted.tool_call_id
JOIN agent_events source_event ON source_event.agent_id = tool_call.agent_id
  AND source_event.model_output_id = tool_call.model_output_id
  AND source_event.event_kind = 'model_output'
`

type InsertToolCallResultAuthorityParams struct {
	Outcome    string
	ProjectID  uuid.UUID
	AgentID    uuid.UUID
	ToolCallID uuid.UUID
}

type InsertToolCallResultAuthorityRow struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	AgentID     uuid.UUID
	TurnID      uuid.UUID
	ToolCallID  uuid.UUID
	Outcome     string
	CompletedAt time.Time
}

func (q *Queries) InsertToolCallResultAuthority(ctx context.Context, arg InsertToolCallResultAuthorityParams) (InsertToolCallResultAuthorityRow, error) {
	row := q.db.QueryRow(ctx, insertToolCallResultAuthority,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
		arg.ToolCallID,
	)
	var i InsertToolCallResultAuthorityRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.ToolCallID,
		&i.Outcome,
		&i.CompletedAt,
	)
	return i, err
}

const insertTypedAgentEvent = `-- name: InsertTypedAgentEvent :one
WITH event_time AS (
  SELECT statement_timestamp() AS created_at
  FROM agent_inputs input
  WHERE input.project_id = $12
    AND input.agent_id = $2
    AND input.id = $7::uuid

  UNION ALL

  SELECT output.created_at
  FROM model_outputs output
  JOIN agents agent ON agent.id = output.agent_id
  WHERE agent.project_id = $12
    AND output.agent_id = $2
    AND output.id = $8::uuid

  UNION ALL

  SELECT result.completed_at
  FROM tool_call_results result
  JOIN agents agent ON agent.id = result.agent_id
  WHERE agent.project_id = $12
    AND result.agent_id = $2
    AND result.id = $9::uuid

  UNION ALL

  SELECT checkpoint.created_at
  FROM context_checkpoints checkpoint
  JOIN agents agent ON agent.id = checkpoint.agent_id
  WHERE agent.project_id = $12
    AND checkpoint.agent_id = $2
    AND checkpoint.id = $10::uuid
)
INSERT INTO agent_events(
  id, agent_id, turn_id, sequence, event_kind,
  idempotency_key, agent_input_id, model_output_id,
  tool_call_result_id, context_checkpoint_id, is_opening_event, created_at
)
SELECT
  coalesce($1::uuid, uuidv7()),
  $2, $3, $4,
  $5,
  $6,
  $7::uuid, $8::uuid,
  $9::uuid, $10::uuid,
  $11, event_time.created_at
FROM event_time
ON CONFLICT (agent_id, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, agent_id, turn_id, is_opening_event, sequence, event_kind, created_at, coalesce(idempotency_key, '') AS idempotency_key, agent_input_id, model_output_id, tool_call_result_id, context_checkpoint_id
`

type InsertTypedAgentEventParams struct {
	ID                  *uuid.UUID
	AgentID             uuid.UUID
	TurnID              uuid.UUID
	Sequence            int64
	EventKind           string
	IdempotencyKey      *string
	AgentInputID        *uuid.UUID
	ModelOutputID       *uuid.UUID
	ToolCallResultID    *uuid.UUID
	ContextCheckpointID *uuid.UUID
	IsOpeningEvent      bool
	ProjectID           uuid.UUID
}

type InsertTypedAgentEventRow struct {
	ID                  uuid.UUID
	AgentID             uuid.UUID
	TurnID              uuid.UUID
	IsOpeningEvent      bool
	Sequence            int64
	EventKind           string
	CreatedAt           time.Time
	IdempotencyKey      string
	AgentInputID        *uuid.UUID
	ModelOutputID       *uuid.UUID
	ToolCallResultID    *uuid.UUID
	ContextCheckpointID *uuid.UUID
}

func (q *Queries) InsertTypedAgentEvent(ctx context.Context, arg InsertTypedAgentEventParams) (InsertTypedAgentEventRow, error) {
	row := q.db.QueryRow(ctx, insertTypedAgentEvent,
		arg.ID,
		arg.AgentID,
		arg.TurnID,
		arg.Sequence,
		arg.EventKind,
		arg.IdempotencyKey,
		arg.AgentInputID,
		arg.ModelOutputID,
		arg.ToolCallResultID,
		arg.ContextCheckpointID,
		arg.IsOpeningEvent,
		arg.ProjectID,
	)
	var i InsertTypedAgentEventRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TurnID,
		&i.IsOpeningEvent,
		&i.Sequence,
		&i.EventKind,
		&i.CreatedAt,
		&i.IdempotencyKey,
		&i.AgentInputID,
		&i.ModelOutputID,
		&i.ToolCallResultID,
		&i.ContextCheckpointID,
	)
	return i, err
}

const listContentBlocksForAgentInputs = `-- name: ListContentBlocksForAgentInputs :many
SELECT block.id, agent.project_id, block.agent_id, block.owner_kind,
       block.owner_agent_input_id, block.owner_model_output_id,
       block.owner_tool_call_result_id, block.ordinal, block.block_kind,
       coalesce(block.text_content, '') AS text_content, block.structured_data,
       block.artifact_id, block.tool_call_id, block.metadata, block.created_at
FROM content_blocks block
JOIN agents agent ON agent.id = block.agent_id
WHERE agent.project_id = $1
  AND block.agent_id = $2
  AND block.owner_agent_input_id = ANY($3::uuid[])
ORDER BY block.owner_agent_input_id ASC, block.ordinal ASC, block.id ASC
`

type ListContentBlocksForAgentInputsParams struct {
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	AgentInputIds []uuid.UUID
}

type ListContentBlocksForAgentInputsRow struct {
	ID                    uuid.UUID
	ProjectID             uuid.UUID
	AgentID               uuid.UUID
	OwnerKind             string
	OwnerAgentInputID     *uuid.UUID
	OwnerModelOutputID    *uuid.UUID
	OwnerToolCallResultID *uuid.UUID
	Ordinal               int32
	BlockKind             string
	TextContent           string
	StructuredData        *json.RawMessage
	ArtifactID            *uuid.UUID
	ToolCallID            *uuid.UUID
	Metadata              json.RawMessage
	CreatedAt             time.Time
}

func (q *Queries) ListContentBlocksForAgentInputs(ctx context.Context, arg ListContentBlocksForAgentInputsParams) ([]ListContentBlocksForAgentInputsRow, error) {
	rows, err := q.db.Query(ctx, listContentBlocksForAgentInputs, arg.ProjectID, arg.AgentID, arg.AgentInputIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentBlocksForAgentInputsRow{}
	for rows.Next() {
		var i ListContentBlocksForAgentInputsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.OwnerKind,
			&i.OwnerAgentInputID,
			&i.OwnerModelOutputID,
			&i.OwnerToolCallResultID,
			&i.Ordinal,
			&i.BlockKind,
			&i.TextContent,
			&i.StructuredData,
			&i.ArtifactID,
			&i.ToolCallID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentBlocksForModelOutput = `-- name: ListContentBlocksForModelOutput :many
SELECT block.id, agent.project_id, block.agent_id, block.owner_kind,
       block.owner_agent_input_id, block.owner_model_output_id,
       block.owner_tool_call_result_id, block.ordinal, block.block_kind,
       coalesce(block.text_content, '') AS text_content, block.structured_data,
       block.artifact_id, block.tool_call_id, block.created_at
FROM content_blocks block
JOIN agents agent ON agent.id = block.agent_id
WHERE agent.project_id = $1
  AND block.agent_id = $2
  AND block.owner_model_output_id = $3
ORDER BY block.ordinal ASC, block.id ASC
`

type ListContentBlocksForModelOutputParams struct {
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	ModelOutputID *uuid.UUID
}

type ListContentBlocksForModelOutputRow struct {
	ID                    uuid.UUID
	ProjectID             uuid.UUID
	AgentID               uuid.UUID
	OwnerKind             string
	OwnerAgentInputID     *uuid.UUID
	OwnerModelOutputID    *uuid.UUID
	OwnerToolCallResultID *uuid.UUID
	Ordinal               int32
	BlockKind             string
	TextContent           string
	StructuredData        *json.RawMessage
	ArtifactID            *uuid.UUID
	ToolCallID            *uuid.UUID
	CreatedAt             time.Time
}

func (q *Queries) ListContentBlocksForModelOutput(ctx context.Context, arg ListContentBlocksForModelOutputParams) ([]ListContentBlocksForModelOutputRow, error) {
	rows, err := q.db.Query(ctx, listContentBlocksForModelOutput, arg.ProjectID, arg.AgentID, arg.ModelOutputID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentBlocksForModelOutputRow{}
	for rows.Next() {
		var i ListContentBlocksForModelOutputRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.OwnerKind,
			&i.OwnerAgentInputID,
			&i.OwnerModelOutputID,
			&i.OwnerToolCallResultID,
			&i.Ordinal,
			&i.BlockKind,
			&i.TextContent,
			&i.StructuredData,
			&i.ArtifactID,
			&i.ToolCallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallResultContentBlocks = `-- name: ListToolCallResultContentBlocks :many
SELECT block.id, agent.project_id, block.agent_id, block.owner_kind,
       block.owner_agent_input_id, block.owner_model_output_id,
       block.owner_tool_call_result_id, block.ordinal, block.block_kind,
       coalesce(block.text_content, '') AS text_content, block.structured_data,
       block.artifact_id, block.tool_call_id, block.exclude_from_model_context,
       block.metadata, block.created_at
FROM content_blocks block
JOIN agents agent ON agent.id = block.agent_id
WHERE agent.project_id = $1
  AND block.agent_id = $2
  AND block.owner_tool_call_result_id = $3
ORDER BY block.ordinal
`

type ListToolCallResultContentBlocksParams struct {
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	ToolCallResultID *uuid.UUID
}

type ListToolCallResultContentBlocksRow struct {
	ID                      uuid.UUID
	ProjectID               uuid.UUID
	AgentID                 uuid.UUID
	OwnerKind               string
	OwnerAgentInputID       *uuid.UUID
	OwnerModelOutputID      *uuid.UUID
	OwnerToolCallResultID   *uuid.UUID
	Ordinal                 int32
	BlockKind               string
	TextContent             string
	StructuredData          *json.RawMessage
	ArtifactID              *uuid.UUID
	ToolCallID              *uuid.UUID
	ExcludeFromModelContext bool
	Metadata                json.RawMessage
	CreatedAt               time.Time
}

func (q *Queries) ListToolCallResultContentBlocks(ctx context.Context, arg ListToolCallResultContentBlocksParams) ([]ListToolCallResultContentBlocksRow, error) {
	rows, err := q.db.Query(ctx, listToolCallResultContentBlocks, arg.ProjectID, arg.AgentID, arg.ToolCallResultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolCallResultContentBlocksRow{}
	for rows.Next() {
		var i ListToolCallResultContentBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.OwnerKind,
			&i.OwnerAgentInputID,
			&i.OwnerModelOutputID,
			&i.OwnerToolCallResultID,
			&i.Ordinal,
			&i.BlockKind,
			&i.TextContent,
			&i.StructuredData,
			&i.ArtifactID,
			&i.ToolCallID,
			&i.ExcludeFromModelContext,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveConfigChangeAgentInput = `-- name: ResolveConfigChangeAgentInput :one
WITH causal_event AS MATERIALIZED (
  SELECT input.agent_config_id, event.created_at
  FROM agent_inputs input
  JOIN agent_events event ON event.agent_id = input.agent_id
    AND event.agent_input_id = input.id
  WHERE input.project_id = $1
    AND input.agent_id = $2
    AND input.id = $3
    AND input.input_kind = 'config_change'
    AND input.state = 'received'
    AND event.id = $4
    AND event.event_kind = 'agent_input'
),
resolved AS (
  UPDATE agent_inputs input
  SET state = 'resolved',
      admitted_event_id = $4,
      admitted_at = causal_event.created_at,
      resolved_at = causal_event.created_at
  FROM causal_event
  WHERE input.project_id = $1
    AND input.agent_id = $2
    AND input.id = $3
    AND input.state = 'received'
  RETURNING input.admitted_at, input.resolved_at, input.agent_config_id
),
updated_agent AS (
  UPDATE agents agent
  SET current_config_id = resolved.agent_config_id,
      updated_at = resolved.resolved_at
  FROM resolved
  WHERE agent.project_id = $1
    AND agent.id = $2
  RETURNING agent.id
)
SELECT resolved.admitted_at, resolved.resolved_at
FROM resolved
JOIN updated_agent ON true
`

type ResolveConfigChangeAgentInputParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
	EventID   uuid.UUID
}

type ResolveConfigChangeAgentInputRow struct {
	AdmittedAt *time.Time
	ResolvedAt *time.Time
}

func (q *Queries) ResolveConfigChangeAgentInput(ctx context.Context, arg ResolveConfigChangeAgentInputParams) (ResolveConfigChangeAgentInputRow, error) {
	row := q.db.QueryRow(ctx, resolveConfigChangeAgentInput,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
		arg.EventID,
	)
	var i ResolveConfigChangeAgentInputRow
	err := row.Scan(&i.AdmittedAt, &i.ResolvedAt)
	return i, err
}

const resolveControlAgentInput = `-- name: ResolveControlAgentInput :exec
UPDATE agent_inputs
SET state = 'resolved',
    admitted_event_id = $1,
    admitted_at = statement_timestamp(),
    resolved_at = statement_timestamp()
WHERE project_id = $2
  AND agent_id = $3
  AND id = $4
  AND input_kind = 'control'
  AND control_type = $5
  AND state = 'received'
`

type ResolveControlAgentInputParams struct {
	EventID     *uuid.UUID
	ProjectID   uuid.UUID
	AgentID     uuid.UUID
	ID          uuid.UUID
	ControlType *string
}

func (q *Queries) ResolveControlAgentInput(ctx context.Context, arg ResolveControlAgentInputParams) error {
	_, err := q.db.Exec(ctx, resolveControlAgentInput,
		arg.EventID,
		arg.ProjectID,
		arg.AgentID,
		arg.ID,
		arg.ControlType,
	)
	return err
}

const toolCallResultHasTypedEvent = `-- name: ToolCallResultHasTypedEvent :one
SELECT EXISTS (
  SELECT 1
  FROM agent_events event
  JOIN agents agent ON agent.id = event.agent_id
  WHERE agent.project_id = $1
    AND event.agent_id = $2
    AND event.tool_call_result_id = $3
    AND event.event_kind = 'tool_result'
)::boolean
`

type ToolCallResultHasTypedEventParams struct {
	ProjectID        uuid.UUID
	AgentID          uuid.UUID
	ToolCallResultID *uuid.UUID
}

func (q *Queries) ToolCallResultHasTypedEvent(ctx context.Context, arg ToolCallResultHasTypedEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, toolCallResultHasTypedEvent, arg.ProjectID, arg.AgentID, arg.ToolCallResultID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
