// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_integrations.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const agentProfileHasProjectIntegration = `-- name: AgentProfileHasProjectIntegration :one
SELECT EXISTS (
    SELECT 1 FROM project_integrations integration
    WHERE integration.project_id = $1 AND integration.deleted_at IS NULL
      AND integration.settings @> jsonb_build_object('launcher', jsonb_build_object('slots',
          jsonb_build_array(jsonb_build_object('agent_profile_id', $2::uuid::text))))
) AS referenced
`

type AgentProfileHasProjectIntegrationParams struct {
	ProjectID uuid.UUID
	ProfileID uuid.UUID
}

func (q *Queries) AgentProfileHasProjectIntegration(ctx context.Context, arg AgentProfileHasProjectIntegrationParams) (bool, error) {
	row := q.db.QueryRow(ctx, agentProfileHasProjectIntegration, arg.ProjectID, arg.ProfileID)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const configureProjectIntegration = `-- name: ConfigureProjectIntegration :one
UPDATE project_integrations
SET installed_by_user_id = $1,
    provider_tenant_id = $2,
    provider_account_ref = $3,
    provider_agent_display_name = $4,
    credential_secret_id = $5::uuid,
    provider_config = $6, provider_identity = $7,
    provider_metadata = $8,
    last_oauth_flow_id = coalesce($9::uuid, last_oauth_flow_id),
    state = 'active', setup_revision = setup_revision + 1, updated_at = statement_timestamp()
WHERE project_id = $10 AND id = $11 AND deleted_at IS NULL
  AND setup_revision = $12
RETURNING id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_type, settings, setup_revision
`

type ConfigureProjectIntegrationParams struct {
	InstalledByUserID        *uuid.UUID
	ProviderTenantID         *string
	ProviderAccountRef       *string
	ProviderAgentDisplayName string
	CredentialSecretID       uuid.UUID
	ProviderConfig           json.RawMessage
	ProviderIdentity         json.RawMessage
	ProviderMetadata         json.RawMessage
	OauthFlowID              *uuid.UUID
	ProjectID                uuid.UUID
	ID                       uuid.UUID
	ExpectedSetupRevision    int64
}

func (q *Queries) ConfigureProjectIntegration(ctx context.Context, arg ConfigureProjectIntegrationParams) (ProjectIntegration, error) {
	row := q.db.QueryRow(ctx, configureProjectIntegration,
		arg.InstalledByUserID,
		arg.ProviderTenantID,
		arg.ProviderAccountRef,
		arg.ProviderAgentDisplayName,
		arg.CredentialSecretID,
		arg.ProviderConfig,
		arg.ProviderIdentity,
		arg.ProviderMetadata,
		arg.OauthFlowID,
		arg.ProjectID,
		arg.ID,
		arg.ExpectedSetupRevision,
	)
	var i ProjectIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationType,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const countProjectIntegrations = `-- name: CountProjectIntegrations :one
SELECT count(*)::bigint FROM project_integrations WHERE project_id = $1 AND deleted_at IS NULL
`

type CountProjectIntegrationsParams struct {
	ProjectID uuid.UUID
}

func (q *Queries) CountProjectIntegrations(ctx context.Context, arg CountProjectIntegrationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectIntegrations, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteProjectIntegration = `-- name: DeleteProjectIntegration :execrows
UPDATE project_integrations
SET state = 'disconnected', credential_secret_id = NULL, deleted_at = statement_timestamp(),
    setup_revision = setup_revision + 1, updated_at = statement_timestamp()
WHERE project_id = $1 AND id = $2 AND deleted_at IS NULL
`

type DeleteProjectIntegrationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) DeleteProjectIntegration(ctx context.Context, arg DeleteProjectIntegrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectIntegration, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectIntegrationsForProjectDeletion = `-- name: DeleteProjectIntegrationsForProjectDeletion :exec
UPDATE project_integrations
SET state = 'disconnected', credential_secret_id = NULL, deleted_at = statement_timestamp(),
    setup_revision = setup_revision + 1, updated_at = statement_timestamp()
WHERE project_id = $1 AND deleted_at IS NULL
`

type DeleteProjectIntegrationsForProjectDeletionParams struct {
	ProjectID uuid.UUID
}

func (q *Queries) DeleteProjectIntegrationsForProjectDeletion(ctx context.Context, arg DeleteProjectIntegrationsForProjectDeletionParams) error {
	_, err := q.db.Exec(ctx, deleteProjectIntegrationsForProjectDeletion, arg.ProjectID)
	return err
}

const disconnectProjectIntegration = `-- name: DisconnectProjectIntegration :execrows
UPDATE project_integrations
SET state = 'disconnected', setup_revision = setup_revision + 1, updated_at = statement_timestamp()
WHERE project_id = $1 AND id = $2
  AND deleted_at IS NULL
  AND ($3::bigint IS NULL OR setup_revision = $3)
`

type DisconnectProjectIntegrationParams struct {
	ProjectID             uuid.UUID
	ID                    uuid.UUID
	ExpectedSetupRevision *int64
}

func (q *Queries) DisconnectProjectIntegration(ctx context.Context, arg DisconnectProjectIntegrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, disconnectProjectIntegration, arg.ProjectID, arg.ID, arg.ExpectedSetupRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectIntegration = `-- name: GetProjectIntegration :one
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_type, settings, setup_revision
FROM project_integrations
WHERE project_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetProjectIntegrationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetProjectIntegration(ctx context.Context, arg GetProjectIntegrationParams) (ProjectIntegration, error) {
	row := q.db.QueryRow(ctx, getProjectIntegration, arg.ProjectID, arg.ID)
	var i ProjectIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationType,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const getProjectIntegrationByID = `-- name: GetProjectIntegrationByID :one
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_type, settings, setup_revision
FROM project_integrations WHERE id = $1 AND deleted_at IS NULL
`

type GetProjectIntegrationByIDParams struct {
	ID uuid.UUID
}

func (q *Queries) GetProjectIntegrationByID(ctx context.Context, arg GetProjectIntegrationByIDParams) (ProjectIntegration, error) {
	row := q.db.QueryRow(ctx, getProjectIntegrationByID, arg.ID)
	var i ProjectIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationType,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const getProjectIntegrationByName = `-- name: GetProjectIntegrationByName :one
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_type, settings, setup_revision
FROM project_integrations
WHERE project_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetProjectIntegrationByNameParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) GetProjectIntegrationByName(ctx context.Context, arg GetProjectIntegrationByNameParams) (ProjectIntegration, error) {
	row := q.db.QueryRow(ctx, getProjectIntegrationByName, arg.ProjectID, arg.Name)
	var i ProjectIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationType,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const insertProjectIntegration = `-- name: InsertProjectIntegration :one
INSERT INTO project_integrations(org_id, project_id, name, integration_type, settings, state, created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5, 'disconnected', statement_timestamp(), statement_timestamp())
RETURNING id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_type, settings, setup_revision
`

type InsertProjectIntegrationParams struct {
	OrgID           uuid.UUID
	ProjectID       uuid.UUID
	Name            string
	IntegrationType string
	Settings        json.RawMessage
}

func (q *Queries) InsertProjectIntegration(ctx context.Context, arg InsertProjectIntegrationParams) (ProjectIntegration, error) {
	row := q.db.QueryRow(ctx, insertProjectIntegration,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.IntegrationType,
		arg.Settings,
	)
	var i ProjectIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationType,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const integrationOAuthFlowConsumed = `-- name: IntegrationOAuthFlowConsumed :one
SELECT EXISTS (SELECT 1 FROM project_integrations WHERE last_oauth_flow_id = $1) AS consumed
`

type IntegrationOAuthFlowConsumedParams struct {
	FlowID *uuid.UUID
}

// @sqlc-vet-disable project-integrations-deleted-at
// Tombstones also prevent reusing a completed setup attempt.
func (q *Queries) IntegrationOAuthFlowConsumed(ctx context.Context, arg IntegrationOAuthFlowConsumedParams) (bool, error) {
	row := q.db.QueryRow(ctx, integrationOAuthFlowConsumed, arg.FlowID)
	var consumed bool
	err := row.Scan(&consumed)
	return consumed, err
}

const listProjectIntegrationMetadataByIDs = `-- name: ListProjectIntegrationMetadataByIDs :many
SELECT id, project_id, name, integration_type, state, deleted_at
FROM project_integrations
WHERE project_id = $1 AND id = ANY($2::uuid[])
ORDER BY id
`

type ListProjectIntegrationMetadataByIDsParams struct {
	ProjectID uuid.UUID
	Ids       []uuid.UUID
}

type ListProjectIntegrationMetadataByIDsRow struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	Name            string
	IntegrationType string
	State           string
	DeletedAt       *time.Time
}

func (q *Queries) ListProjectIntegrationMetadataByIDs(ctx context.Context, arg ListProjectIntegrationMetadataByIDsParams) ([]ListProjectIntegrationMetadataByIDsRow, error) {
	rows, err := q.db.Query(ctx, listProjectIntegrationMetadataByIDs, arg.ProjectID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectIntegrationMetadataByIDsRow{}
	for rows.Next() {
		var i ListProjectIntegrationMetadataByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IntegrationType,
			&i.State,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIntegrations = `-- name: ListProjectIntegrations :many
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_type, settings, setup_revision
FROM project_integrations
WHERE project_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE $2::text ESCAPE '\')
  AND (NOT $3::boolean OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListProjectIntegrationsParams struct {
	ProjectID       uuid.UUID
	NamePattern     string
	CursorSet       bool
	CursorCreatedAt time.Time
	CursorID        uuid.UUID
	RowLimit        int32
}

func (q *Queries) ListProjectIntegrations(ctx context.Context, arg ListProjectIntegrationsParams) ([]ProjectIntegration, error) {
	rows, err := q.db.Query(ctx, listProjectIntegrations,
		arg.ProjectID,
		arg.NamePattern,
		arg.CursorSet,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectIntegration{}
	for rows.Next() {
		var i ProjectIntegration
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.InstalledByUserID,
			&i.State,
			&i.ProviderTenantID,
			&i.ProviderAccountRef,
			&i.ProviderAgentDisplayName,
			&i.CredentialSecretID,
			&i.ProviderConfig,
			&i.ProviderIdentity,
			&i.ProviderMetadata,
			&i.LastOauthFlowID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.IntegrationType,
			&i.Settings,
			&i.SetupRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIntegrationsByProviderIdentity = `-- name: ListProjectIntegrationsByProviderIdentity :many
SELECT integration.id, integration.org_id, integration.project_id, integration.installed_by_user_id, integration.state, integration.provider_tenant_id, integration.provider_account_ref, integration.provider_agent_display_name, integration.credential_secret_id, integration.provider_config, integration.provider_identity, integration.provider_metadata, integration.last_oauth_flow_id, integration.deleted_at, integration.created_at, integration.updated_at, integration.name, integration.integration_type, integration.settings, integration.setup_revision
FROM project_integrations integration
JOIN projects project ON project.id = integration.project_id
JOIN orgs org ON org.id = integration.org_id
WHERE integration.integration_type = ANY($1::text[]) AND integration.provider_tenant_id = $2
  AND ($3::text IS NULL OR integration.provider_account_ref = $3::text)
  AND (integration.state = 'active' OR ($4::boolean
    AND integration.state = 'disconnected' AND integration.credential_secret_id IS NOT NULL))
  AND integration.deleted_at IS NULL
  AND project.deleted_at IS NULL AND org.deleted_at IS NULL
  AND ($5::uuid IS NULL OR integration.id > $5::uuid)
ORDER BY integration.id LIMIT $6
`

type ListProjectIntegrationsByProviderIdentityParams struct {
	IntegrationTypes    []string
	ProviderTenantID    *string
	ProviderAccountRef  *string
	IncludeDisconnected bool
	AfterID             *uuid.UUID
	RowLimit            int32
}

func (q *Queries) ListProjectIntegrationsByProviderIdentity(ctx context.Context, arg ListProjectIntegrationsByProviderIdentityParams) ([]ProjectIntegration, error) {
	rows, err := q.db.Query(ctx, listProjectIntegrationsByProviderIdentity,
		arg.IntegrationTypes,
		arg.ProviderTenantID,
		arg.ProviderAccountRef,
		arg.IncludeDisconnected,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectIntegration{}
	for rows.Next() {
		var i ProjectIntegration
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.InstalledByUserID,
			&i.State,
			&i.ProviderTenantID,
			&i.ProviderAccountRef,
			&i.ProviderAgentDisplayName,
			&i.CredentialSecretID,
			&i.ProviderConfig,
			&i.ProviderIdentity,
			&i.ProviderMetadata,
			&i.LastOauthFlowID,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.IntegrationType,
			&i.Settings,
			&i.SetupRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectIntegration = `-- name: LockProjectIntegration :one
SELECT id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_type, settings, setup_revision
FROM project_integrations
WHERE project_id = $1 AND id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type LockProjectIntegrationParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) LockProjectIntegration(ctx context.Context, arg LockProjectIntegrationParams) (ProjectIntegration, error) {
	row := q.db.QueryRow(ctx, lockProjectIntegration, arg.ProjectID, arg.ID)
	var i ProjectIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationType,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}

const lockProjectIntegrationLifecycleExclusive = `-- name: LockProjectIntegrationLifecycleExclusive :exec
SELECT pg_advisory_xact_lock(hashtextextended('project_integration:' || $1::uuid::text, 0))
`

type LockProjectIntegrationLifecycleExclusiveParams struct {
	IntegrationID uuid.UUID
}

func (q *Queries) LockProjectIntegrationLifecycleExclusive(ctx context.Context, arg LockProjectIntegrationLifecycleExclusiveParams) error {
	_, err := q.db.Exec(ctx, lockProjectIntegrationLifecycleExclusive, arg.IntegrationID)
	return err
}

const lockProjectIntegrationLifecycleShared = `-- name: LockProjectIntegrationLifecycleShared :exec
SELECT pg_advisory_xact_lock_shared(hashtextextended('project_integration:' || $1::uuid::text, 0))
`

type LockProjectIntegrationLifecycleSharedParams struct {
	IntegrationID uuid.UUID
}

// Lock order: project/integration gates (sorted integration IDs), inbox receipt, conversation gate, profile/agent rows.
func (q *Queries) LockProjectIntegrationLifecycleShared(ctx context.Context, arg LockProjectIntegrationLifecycleSharedParams) error {
	_, err := q.db.Exec(ctx, lockProjectIntegrationLifecycleShared, arg.IntegrationID)
	return err
}

const updateProjectIntegrationSettings = `-- name: UpdateProjectIntegrationSettings :one
UPDATE project_integrations SET settings = $1, updated_at = statement_timestamp()
WHERE project_id = $2 AND id = $3 AND deleted_at IS NULL
RETURNING id, org_id, project_id, installed_by_user_id, state, provider_tenant_id, provider_account_ref, provider_agent_display_name, credential_secret_id, provider_config, provider_identity, provider_metadata, last_oauth_flow_id, deleted_at, created_at, updated_at, name, integration_type, settings, setup_revision
`

type UpdateProjectIntegrationSettingsParams struct {
	Settings  json.RawMessage
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) UpdateProjectIntegrationSettings(ctx context.Context, arg UpdateProjectIntegrationSettingsParams) (ProjectIntegration, error) {
	row := q.db.QueryRow(ctx, updateProjectIntegrationSettings, arg.Settings, arg.ProjectID, arg.ID)
	var i ProjectIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.InstalledByUserID,
		&i.State,
		&i.ProviderTenantID,
		&i.ProviderAccountRef,
		&i.ProviderAgentDisplayName,
		&i.CredentialSecretID,
		&i.ProviderConfig,
		&i.ProviderIdentity,
		&i.ProviderMetadata,
		&i.LastOauthFlowID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IntegrationType,
		&i.Settings,
		&i.SetupRevision,
	)
	return i, err
}
