// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_limits.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const countActiveAgentProfilesForProject = `-- name: CountActiveAgentProfilesForProject :one
SELECT count(*)::bigint
FROM agent_profiles
WHERE project_id = $1
  AND deleted_at IS NULL
`

type CountActiveAgentProfilesForProjectParams struct {
	ProjectID uuid.UUID
}

func (q *Queries) CountActiveAgentProfilesForProject(ctx context.Context, arg CountActiveAgentProfilesForProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAgentProfilesForProject, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveAgentsForProject = `-- name: CountActiveAgentsForProject :one
SELECT count(*)::bigint
FROM agents
WHERE project_id = $1
  AND state = 'active'
`

type CountActiveAgentsForProjectParams struct {
	ProjectID uuid.UUID
}

func (q *Queries) CountActiveAgentsForProject(ctx context.Context, arg CountActiveAgentsForProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAgentsForProject, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveConfiguredModelsForProvider = `-- name: CountActiveConfiguredModelsForProvider :one
SELECT count(*)::bigint
FROM configured_models
WHERE org_id = $1
  AND model_provider_config_id = $2
  AND deleted_at IS NULL
`

type CountActiveConfiguredModelsForProviderParams struct {
	OrgID                 uuid.UUID
	ModelProviderConfigID uuid.UUID
}

func (q *Queries) CountActiveConfiguredModelsForProvider(ctx context.Context, arg CountActiveConfiguredModelsForProviderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveConfiguredModelsForProvider, arg.OrgID, arg.ModelProviderConfigID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveMachineDaemonTokensForMachine = `-- name: CountActiveMachineDaemonTokensForMachine :one
SELECT count(*)::bigint
FROM machine_daemon_tokens
WHERE org_id = $1
  AND machine_id = $2
  AND revoked_at IS NULL
`

type CountActiveMachineDaemonTokensForMachineParams struct {
	OrgID     uuid.UUID
	MachineID uuid.UUID
}

func (q *Queries) CountActiveMachineDaemonTokensForMachine(ctx context.Context, arg CountActiveMachineDaemonTokensForMachineParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMachineDaemonTokensForMachine, arg.OrgID, arg.MachineID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveOrgAPIKeysForOrg = `-- name: CountActiveOrgAPIKeysForOrg :one
SELECT count(*)::bigint
FROM org_api_keys
WHERE org_id = $1
  AND revoked_at IS NULL
`

type CountActiveOrgAPIKeysForOrgParams struct {
	OrgID uuid.UUID
}

func (q *Queries) CountActiveOrgAPIKeysForOrg(ctx context.Context, arg CountActiveOrgAPIKeysForOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrgAPIKeysForOrg, arg.OrgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActivePersonalAccessTokensForUser = `-- name: CountActivePersonalAccessTokensForUser :one
SELECT count(*)::bigint
FROM personal_access_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
`

type CountActivePersonalAccessTokensForUserParams struct {
	UserID uuid.UUID
}

func (q *Queries) CountActivePersonalAccessTokensForUser(ctx context.Context, arg CountActivePersonalAccessTokensForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePersonalAccessTokensForUser, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveProjectsForOrg = `-- name: CountActiveProjectsForOrg :one
SELECT count(*)::bigint
FROM projects
WHERE org_id = $1
  AND deleted_at IS NULL
`

type CountActiveProjectsForOrgParams struct {
	OrgID uuid.UUID
}

func (q *Queries) CountActiveProjectsForOrg(ctx context.Context, arg CountActiveProjectsForOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProjectsForOrg, arg.OrgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveSkillsForOwner = `-- name: CountActiveSkillsForOwner :one
SELECT count(*)::bigint
FROM skills
WHERE org_id = $1
  AND owner_kind = $2
  AND owner_project_id IS NOT DISTINCT FROM $3::uuid
  AND owner_user_id IS NOT DISTINCT FROM $4::uuid
  AND deleted_at IS NULL
`

type CountActiveSkillsForOwnerParams struct {
	OrgID          uuid.UUID
	OwnerKind      string
	OwnerProjectID *uuid.UUID
	OwnerUserID    *uuid.UUID
}

func (q *Queries) CountActiveSkillsForOwner(ctx context.Context, arg CountActiveSkillsForOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSkillsForOwner,
		arg.OrgID,
		arg.OwnerKind,
		arg.OwnerProjectID,
		arg.OwnerUserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveTenantMachinePoolsForOrg = `-- name: CountActiveTenantMachinePoolsForOrg :one
SELECT count(*)::bigint
FROM machine_pools
WHERE org_id = $1
  AND management_kind = 'tenant'
  AND deleted_at IS NULL
`

type CountActiveTenantMachinePoolsForOrgParams struct {
	OrgID uuid.UUID
}

func (q *Queries) CountActiveTenantMachinePoolsForOrg(ctx context.Context, arg CountActiveTenantMachinePoolsForOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTenantMachinePoolsForOrg, arg.OrgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveTenantModelProviderConfigsForOrg = `-- name: CountActiveTenantModelProviderConfigsForOrg :one
SELECT count(*)::bigint
FROM model_provider_configs
WHERE org_id = $1
  AND management_kind = 'tenant'
  AND deleted_at IS NULL
`

type CountActiveTenantModelProviderConfigsForOrgParams struct {
	OrgID uuid.UUID
}

func (q *Queries) CountActiveTenantModelProviderConfigsForOrg(ctx context.Context, arg CountActiveTenantModelProviderConfigsForOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTenantModelProviderConfigsForOrg, arg.OrgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countActiveTenantSecretsForOwner = `-- name: CountActiveTenantSecretsForOwner :one
SELECT count(*)::bigint
FROM secrets
WHERE org_id = $1
  AND management_kind = 'tenant'
  AND owner_kind = $2
  AND owner_project_id IS NOT DISTINCT FROM $3::uuid
  AND owner_user_id IS NOT DISTINCT FROM $4::uuid
  AND deleted_at IS NULL
`

type CountActiveTenantSecretsForOwnerParams struct {
	OrgID          uuid.UUID
	OwnerKind      string
	OwnerProjectID *uuid.UUID
	OwnerUserID    *uuid.UUID
}

func (q *Queries) CountActiveTenantSecretsForOwner(ctx context.Context, arg CountActiveTenantSecretsForOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTenantSecretsForOwner,
		arg.OrgID,
		arg.OwnerKind,
		arg.OwnerProjectID,
		arg.OwnerUserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAgentConfigsForProject = `-- name: CountAgentConfigsForProject :one
SELECT count(*)::bigint
FROM agent_configs
WHERE project_id = $1
`

type CountAgentConfigsForProjectParams struct {
	ProjectID uuid.UUID
}

func (q *Queries) CountAgentConfigsForProject(ctx context.Context, arg CountAgentConfigsForProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentConfigsForProject, arg.ProjectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countLiveMachinesForOrg = `-- name: CountLiveMachinesForOrg :one
SELECT count(*)::bigint
FROM machines
WHERE org_id = $1
  AND deleted_at IS NULL
`

type CountLiveMachinesForOrgParams struct {
	OrgID uuid.UUID
}

func (q *Queries) CountLiveMachinesForOrg(ctx context.Context, arg CountLiveMachinesForOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveMachinesForOrg, arg.OrgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingOrgInvitationsForOrg = `-- name: CountPendingOrgInvitationsForOrg :one
SELECT count(*)::bigint
FROM org_invitations
WHERE org_id = $1
`

type CountPendingOrgInvitationsForOrgParams struct {
	OrgID uuid.UUID
}

func (q *Queries) CountPendingOrgInvitationsForOrg(ctx context.Context, arg CountPendingOrgInvitationsForOrgParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOrgInvitationsForOrg, arg.OrgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getEffectiveResourceLimits = `-- name: GetEffectiveResourceLimits :one
SELECT
    org_id,
    max_active_projects_per_org,
    max_pending_org_invitations_per_org,
    max_active_org_api_keys_per_org,
    max_active_tenant_model_provider_configs_per_org,
    max_active_configured_models_per_provider,
    max_agent_configs_per_project,
    max_active_agent_profiles_per_project,
    max_active_agents_per_project,
    max_active_tenant_secrets_per_owner,
    max_active_skills_per_owner,
    max_active_tenant_machine_pools_per_org,
    max_live_machines_per_org,
    max_active_byo_daemon_tokens_per_machine,
    max_non_terminal_processes_per_agent
FROM effective_resource_limits
WHERE org_id = $1
`

type GetEffectiveResourceLimitsParams struct {
	OrgID uuid.UUID
}

func (q *Queries) GetEffectiveResourceLimits(ctx context.Context, arg GetEffectiveResourceLimitsParams) (EffectiveResourceLimit, error) {
	row := q.db.QueryRow(ctx, getEffectiveResourceLimits, arg.OrgID)
	var i EffectiveResourceLimit
	err := row.Scan(
		&i.OrgID,
		&i.MaxActiveProjectsPerOrg,
		&i.MaxPendingOrgInvitationsPerOrg,
		&i.MaxActiveOrgApiKeysPerOrg,
		&i.MaxActiveTenantModelProviderConfigsPerOrg,
		&i.MaxActiveConfiguredModelsPerProvider,
		&i.MaxAgentConfigsPerProject,
		&i.MaxActiveAgentProfilesPerProject,
		&i.MaxActiveAgentsPerProject,
		&i.MaxActiveTenantSecretsPerOwner,
		&i.MaxActiveSkillsPerOwner,
		&i.MaxActiveTenantMachinePoolsPerOrg,
		&i.MaxLiveMachinesPerOrg,
		&i.MaxActiveByoDaemonTokensPerMachine,
		&i.MaxNonTerminalProcessesPerAgent,
	)
	return i, err
}

const lockResourceCreation = `-- name: LockResourceCreation :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        'resource_creation:' || $1::text || ':' || $2::text,
        0
    )
)
`

type LockResourceCreationParams struct {
	ResourceKind string
	Scope        string
}

func (q *Queries) LockResourceCreation(ctx context.Context, arg LockResourceCreationParams) error {
	_, err := q.db.Exec(ctx, lockResourceCreation, arg.ResourceKind, arg.Scope)
	return err
}
