// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subagents.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countActiveChildAgentsForLaunch = `-- name: CountActiveChildAgentsForLaunch :one
SELECT count(*)::integer AS total,
       count(*) FILTER (WHERE agent.subagent_key = $1::text)::integer AS same_key
FROM agents agent
WHERE agent.project_id = $2
  AND agent.parent_agent_id = $3
  AND agent.state = 'active'
`

type CountActiveChildAgentsForLaunchParams struct {
	SubagentKey   string
	ProjectID     uuid.UUID
	ParentAgentID *uuid.UUID
}

type CountActiveChildAgentsForLaunchRow struct {
	Total   int32
	SameKey int32
}

func (q *Queries) CountActiveChildAgentsForLaunch(ctx context.Context, arg CountActiveChildAgentsForLaunchParams) (CountActiveChildAgentsForLaunchRow, error) {
	row := q.db.QueryRow(ctx, countActiveChildAgentsForLaunch, arg.SubagentKey, arg.ProjectID, arg.ParentAgentID)
	var i CountActiveChildAgentsForLaunchRow
	err := row.Scan(&i.Total, &i.SameKey)
	return i, err
}

const countAgentAncestors = `-- name: CountAgentAncestors :one
WITH RECURSIVE ancestors AS (
  SELECT agent.id, agent.parent_agent_id, 1 AS depth
  FROM agents agent
  WHERE agent.project_id = $1
    AND agent.id = $2
  UNION ALL
  SELECT parent.id, parent.parent_agent_id, ancestors.depth + 1
  FROM agents parent
  JOIN ancestors ON parent.id = ancestors.parent_agent_id
  WHERE parent.project_id = $1
    AND ancestors.depth < 64
)
SELECT count(*)::integer
FROM ancestors
WHERE ancestors.parent_agent_id IS NOT NULL
`

type CountAgentAncestorsParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

func (q *Queries) CountAgentAncestors(ctx context.Context, arg CountAgentAncestorsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAgentAncestors, arg.ProjectID, arg.AgentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getAgentParentID = `-- name: GetAgentParentID :one
SELECT parent_agent_id
FROM agents
WHERE project_id = $1
  AND id = $2
`

type GetAgentParentIDParams struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetAgentParentID(ctx context.Context, arg GetAgentParentIDParams) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAgentParentID, arg.ProjectID, arg.ID)
	var parent_agent_id *uuid.UUID
	err := row.Scan(&parent_agent_id)
	return parent_agent_id, err
}

const listActiveChildAgentIDs = `-- name: ListActiveChildAgentIDs :many
SELECT agent.id
FROM agents agent
WHERE agent.project_id = $1
  AND agent.parent_agent_id = $2
  AND agent.state = 'active'
ORDER BY agent.created_at, agent.id
`

type ListActiveChildAgentIDsParams struct {
	ProjectID     uuid.UUID
	ParentAgentID *uuid.UUID
}

func (q *Queries) ListActiveChildAgentIDs(ctx context.Context, arg ListActiveChildAgentIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveChildAgentIDs, arg.ProjectID, arg.ParentAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentDescendantIDs = `-- name: ListAgentDescendantIDs :many
WITH RECURSIVE descendants AS (
  SELECT agent.id, 1 AS depth
  FROM agents agent
  WHERE agent.project_id = $1
    AND agent.parent_agent_id = $2
  UNION ALL
  SELECT child.id, descendants.depth + 1
  FROM agents child
  JOIN descendants ON child.parent_agent_id = descendants.id
  WHERE child.project_id = $1
    AND descendants.depth < 64
)
SELECT descendants.id
FROM descendants
ORDER BY descendants.depth, descendants.id
`

type ListAgentDescendantIDsParams struct {
	ProjectID uuid.UUID
	AgentID   *uuid.UUID
}

func (q *Queries) ListAgentDescendantIDs(ctx context.Context, arg ListAgentDescendantIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentDescendantIDs, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentInteractionsForAgents = `-- name: ListAgentInteractionsForAgents :many
SELECT interaction.id, interaction.project_id, interaction.agent_id, interaction.turn_id,
       interaction.model_call_context_id, interaction.tool_call_id, interaction.provider_call_id,
       interaction.interaction_kind, interaction.state, interaction.request, interaction.resolution,
       interaction.resolved_by_input_id, interaction.created_at, interaction.resolved_at,
       agent.name AS agent_name, agent.subagent_key
FROM agent_interaction_read_projection interaction
JOIN agents agent ON agent.project_id = interaction.project_id
  AND agent.id = interaction.agent_id
WHERE interaction.project_id = $1
  AND interaction.agent_id = ANY($2::uuid[])
  AND ($3::text = '' OR interaction.state = $3)
  AND (
    $4::timestamptz IS NULL
    OR (interaction.created_at, interaction.id) > ($4::timestamptz, $5::uuid)
  )
ORDER BY interaction.created_at ASC, interaction.id ASC
LIMIT $6::bigint
`

type ListAgentInteractionsForAgentsParams struct {
	ProjectID       uuid.UUID
	AgentIds        []uuid.UUID
	State           string
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	RowLimit        int64
}

type ListAgentInteractionsForAgentsRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	ModelCallContextID uuid.UUID
	ToolCallID         uuid.UUID
	ProviderCallID     string
	InteractionKind    string
	State              string
	Request            json.RawMessage
	Resolution         json.RawMessage
	ResolvedByInputID  *uuid.UUID
	CreatedAt          time.Time
	ResolvedAt         *time.Time
	AgentName          string
	SubagentKey        string
}

func (q *Queries) ListAgentInteractionsForAgents(ctx context.Context, arg ListAgentInteractionsForAgentsParams) ([]ListAgentInteractionsForAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgentInteractionsForAgents,
		arg.ProjectID,
		arg.AgentIds,
		arg.State,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentInteractionsForAgentsRow{}
	for rows.Next() {
		var i ListAgentInteractionsForAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.TurnID,
			&i.ModelCallContextID,
			&i.ToolCallID,
			&i.ProviderCallID,
			&i.InteractionKind,
			&i.State,
			&i.Request,
			&i.Resolution,
			&i.ResolvedByInputID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.AgentName,
			&i.SubagentKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildAgents = `-- name: ListChildAgents :many
SELECT agent.id,
       agent.name,
       agent.state,
       agent.subagent_key,
       coalesce((
         SELECT event.created_at
         FROM agent_events event
         WHERE event.agent_id = agent.id
         ORDER BY event.sequence DESC
         LIMIT 1
       ), agent.created_at) AS last_activity_at,
       EXISTS (
         SELECT 1
         FROM agent_interactions interaction
         WHERE interaction.agent_id = agent.id
           AND interaction.interaction_kind = 'question'
           AND interaction.state = 'open'
       ) AS has_open_question,
       EXISTS (
         SELECT 1
         FROM agent_interactions interaction
         WHERE interaction.agent_id = agent.id
           AND interaction.interaction_kind = 'permission'
           AND interaction.state = 'open'
       ) AS has_open_permission,
       (
         EXISTS (
           SELECT 1
           FROM agent_runtime_locks runtime_lock
           WHERE runtime_lock.agent_id = agent.id
         )
         OR EXISTS (
           SELECT 1
           FROM agent_wakeups wake
           WHERE wake.agent_id = agent.id
         )
         OR agent_next_wakeup_ready_at(agent.project_id, agent.id) IS NOT NULL
       )::boolean AS is_running
FROM agents agent
WHERE agent.project_id = $1
  AND agent.parent_agent_id = $2
  AND ($3::boolean OR agent.state = 'active')
ORDER BY agent.created_at, agent.id
`

type ListChildAgentsParams struct {
	ProjectID       uuid.UUID
	ParentAgentID   *uuid.UUID
	IncludeArchived bool
}

type ListChildAgentsRow struct {
	ID                uuid.UUID
	Name              string
	State             string
	SubagentKey       string
	LastActivityAt    time.Time
	HasOpenQuestion   bool
	HasOpenPermission bool
	IsRunning         bool
}

func (q *Queries) ListChildAgents(ctx context.Context, arg ListChildAgentsParams) ([]ListChildAgentsRow, error) {
	rows, err := q.db.Query(ctx, listChildAgents, arg.ProjectID, arg.ParentAgentID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildAgentsRow{}
	for rows.Next() {
		var i ListChildAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.SubagentKey,
			&i.LastActivityAt,
			&i.HasOpenQuestion,
			&i.HasOpenPermission,
			&i.IsRunning,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleSubagentsForArchive = `-- name: ListIdleSubagentsForArchive :many
WITH RECURSIVE candidate AS (
  SELECT agent.project_id, agent.id, agent.created_at
  FROM agents agent
  WHERE agent.parent_agent_id IS NOT NULL
    AND agent.state = 'active'
    AND agent.archive_after_idle_minutes IS NOT NULL
    AND coalesce((
      SELECT event.created_at
      FROM agent_events event
      WHERE event.agent_id = agent.id
      ORDER BY event.sequence DESC
      LIMIT 1
    ), agent.created_at) < coalesce($2::timestamptz, statement_timestamp())
      - make_interval(mins => agent.archive_after_idle_minutes)
), subtree AS (
  SELECT candidate.id AS root_id, candidate.project_id, candidate.id, 1 AS depth
  FROM candidate
  UNION ALL
  SELECT subtree.root_id, child.project_id, child.id, subtree.depth + 1
  FROM agents child
  JOIN subtree ON child.parent_agent_id = subtree.id
  WHERE child.project_id = subtree.project_id
    AND child.state = 'active'
    AND subtree.depth < 64
)
SELECT candidate.project_id, candidate.id
FROM candidate
WHERE NOT EXISTS (
  SELECT 1
  FROM subtree
  WHERE subtree.root_id = candidate.id
    AND (
      EXISTS (
        SELECT 1
        FROM agent_runtime_locks runtime_lock
        WHERE runtime_lock.agent_id = subtree.id
      )
      OR EXISTS (
        SELECT 1
        FROM agent_wakeups wake
        WHERE wake.agent_id = subtree.id
      )
      OR EXISTS (
        SELECT 1
        FROM tool_calls call
        WHERE call.agent_id = subtree.id
          AND call.state IN ('running', 'waiting', 'awaiting_permission')
      )
    )
)
ORDER BY candidate.created_at, candidate.id
LIMIT $1::integer
`

type ListIdleSubagentsForArchiveParams struct {
	RowLimit int32
	AsOf     *time.Time
}

type ListIdleSubagentsForArchiveRow struct {
	ProjectID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) ListIdleSubagentsForArchive(ctx context.Context, arg ListIdleSubagentsForArchiveParams) ([]ListIdleSubagentsForArchiveRow, error) {
	rows, err := q.db.Query(ctx, listIdleSubagentsForArchive, arg.RowLimit, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdleSubagentsForArchiveRow{}
	for rows.Next() {
		var i ListIdleSubagentsForArchiveRow
		if err := rows.Scan(&i.ProjectID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentMachineBindingsForSharing = `-- name: ListParentMachineBindingsForSharing :many
SELECT pmgrant.id AS project_machine_grant_id,
       binding.machine_id,
       binding.cwd,
       binding.env_overlay,
       binding.secret_env_overlay,
       binding.description
FROM agent_machine_bindings binding
JOIN project_machine_grants pmgrant ON pmgrant.project_id = binding.project_id
  AND pmgrant.machine_id = binding.machine_id
JOIN machines machine ON machine.org_id = binding.org_id
  AND machine.id = binding.machine_id
  AND machine.deleted_at IS NULL
  AND machine.lifecycle_state NOT IN ('deleting', 'delete_failed', 'deleted')
WHERE binding.project_id = $1
  AND binding.agent_id = $2
  AND binding.state = 'attached'
ORDER BY binding.created_at, binding.id
`

type ListParentMachineBindingsForSharingParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type ListParentMachineBindingsForSharingRow struct {
	ProjectMachineGrantID uuid.UUID
	MachineID             uuid.UUID
	Cwd                   string
	EnvOverlay            json.RawMessage
	SecretEnvOverlay      json.RawMessage
	Description           string
}

func (q *Queries) ListParentMachineBindingsForSharing(ctx context.Context, arg ListParentMachineBindingsForSharingParams) ([]ListParentMachineBindingsForSharingRow, error) {
	rows, err := q.db.Query(ctx, listParentMachineBindingsForSharing, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentMachineBindingsForSharingRow{}
	for rows.Next() {
		var i ListParentMachineBindingsForSharingRow
		if err := rows.Scan(
			&i.ProjectMachineGrantID,
			&i.MachineID,
			&i.Cwd,
			&i.EnvOverlay,
			&i.SecretEnvOverlay,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
