// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_calls.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cancelNonTerminalToolCallsForAgent = `-- name: CancelNonTerminalToolCallsForAgent :many
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $2
    AND agent.id = $3
  FOR UPDATE
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM locked_agent agent
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = agent.id
  AND call.state <> 'completed'
  AND projection.project_id = agent.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
  AND projection.turn_id = $1
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  'canceled'::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CancelNonTerminalToolCallsForAgentParams struct {
	TurnID    uuid.UUID
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type CancelNonTerminalToolCallsForAgentRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CancelNonTerminalToolCallsForAgent(ctx context.Context, arg CancelNonTerminalToolCallsForAgentParams) ([]CancelNonTerminalToolCallsForAgentRow, error) {
	rows, err := q.db.Query(ctx, cancelNonTerminalToolCallsForAgent, arg.TurnID, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelNonTerminalToolCallsForAgentRow{}
	for rows.Next() {
		var i CancelNonTerminalToolCallsForAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.TurnID,
			&i.SourceEventID,
			&i.ModelCallContextID,
			&i.ProviderCallID,
			&i.Name,
			&i.Input,
			&i.Type,
			&i.State,
			&i.Outcome,
			&i.RuntimeLockID,
			&i.ResultContentParts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeCustomToolCall = `-- name: CompleteCustomToolCall :one
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  JOIN tool_calls tool_call ON tool_call.agent_id = agent.id
  WHERE agent.project_id = $3
    AND tool_call.agent_id = $4
    AND tool_call.id = $1
  FOR UPDATE OF agent
)
UPDATE tool_calls call
SET state = 'completed'
FROM locked_agent agent
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = agent.id
  AND call.id = $1
  AND call.state = 'ready'
  AND call.runtime_lock_id IS NULL
  AND call.type = 'custom'
  AND $2::text IN ('succeeded', 'failed')
  AND projection.project_id = agent.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $2::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteCustomToolCallParams struct {
	ID        uuid.UUID
	Outcome   string
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type CompleteCustomToolCallRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteCustomToolCall(ctx context.Context, arg CompleteCustomToolCallParams) (CompleteCustomToolCallRow, error) {
	row := q.db.QueryRow(ctx, completeCustomToolCall,
		arg.ID,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
	)
	var i CompleteCustomToolCallRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const completeMachineUnreachableToolCall = `-- name: CompleteMachineUnreachableToolCall :one
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $3
    AND agent.id = $4
  FOR UPDATE
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM locked_agent agent
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = agent.id
  AND call.id = $1
  AND call.state = 'waiting'
  AND call.type = 'built_in'
  AND projection.project_id = agent.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $2::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteMachineUnreachableToolCallParams struct {
	ID        uuid.UUID
	Outcome   string
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type CompleteMachineUnreachableToolCallRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteMachineUnreachableToolCall(ctx context.Context, arg CompleteMachineUnreachableToolCallParams) (CompleteMachineUnreachableToolCallRow, error) {
	row := q.db.QueryRow(ctx, completeMachineUnreachableToolCall,
		arg.ID,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
	)
	var i CompleteMachineUnreachableToolCallRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const completeRuntimeToolCall = `-- name: CompleteRuntimeToolCall :one
WITH live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $3
    AND runtime_lock.agent_id = $4
    AND runtime_lock.id = $5
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM live_runtime runtime_lock
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = runtime_lock.agent_id
  AND call.id = $1
  AND call.state = 'running'
  AND call.runtime_lock_id = runtime_lock.id
  AND call.type IN ('built_in', 'mcp')
  AND projection.project_id = runtime_lock.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $2::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteRuntimeToolCallParams struct {
	ID            uuid.UUID
	Outcome       string
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	RuntimeLockID uuid.UUID
}

type CompleteRuntimeToolCallRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteRuntimeToolCall(ctx context.Context, arg CompleteRuntimeToolCallParams) (CompleteRuntimeToolCallRow, error) {
	row := q.db.QueryRow(ctx, completeRuntimeToolCall,
		arg.ID,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
		arg.RuntimeLockID,
	)
	var i CompleteRuntimeToolCallRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const completeToolCall = `-- name: CompleteToolCall :one
WITH live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $5
    AND runtime_lock.agent_id = $1
    AND runtime_lock.id = $4
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM live_runtime runtime_lock
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = $1
  AND call.id = $2
  AND call.state <> 'completed'
  AND (
    (call.type IN ('built_in', 'mcp') AND call.state = 'ready')
    OR (
      call.state IN ('awaiting_authorization', 'awaiting_permission')
      AND $3::text IN ('failed', 'denied', 'canceled')
    )
  )
  AND runtime_lock.agent_id = call.agent_id
  AND runtime_lock.id = $4
  AND projection.project_id = runtime_lock.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $3::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteToolCallParams struct {
	AgentID       uuid.UUID
	ID            uuid.UUID
	Outcome       string
	RuntimeLockID uuid.UUID
	ProjectID     uuid.UUID
}

type CompleteToolCallRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteToolCall(ctx context.Context, arg CompleteToolCallParams) (CompleteToolCallRow, error) {
	row := q.db.QueryRow(ctx, completeToolCall,
		arg.AgentID,
		arg.ID,
		arg.Outcome,
		arg.RuntimeLockID,
		arg.ProjectID,
	)
	var i CompleteToolCallRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const completeToolCallFromPermissionInteraction = `-- name: CompleteToolCallFromPermissionInteraction :one
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $2
    AND agent.id = $3
  FOR UPDATE
),
permission_interaction AS MATERIALIZED (
  SELECT agent.project_id, interaction.agent_id, interaction.tool_call_id
  FROM agent_interactions interaction
  JOIN locked_agent agent ON agent.id = interaction.agent_id
  WHERE interaction.agent_id = $3
    AND interaction.id = $4
    AND interaction.interaction_kind = 'permission'
    AND interaction.state IN ('resolved', 'canceled')
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM permission_interaction interaction
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = interaction.agent_id
  AND call.id = interaction.tool_call_id
  AND call.state = 'awaiting_permission'
  AND projection.project_id = interaction.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $1::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteToolCallFromPermissionInteractionParams struct {
	Outcome       string
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	InteractionID uuid.UUID
}

type CompleteToolCallFromPermissionInteractionRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteToolCallFromPermissionInteraction(ctx context.Context, arg CompleteToolCallFromPermissionInteractionParams) (CompleteToolCallFromPermissionInteractionRow, error) {
	row := q.db.QueryRow(ctx, completeToolCallFromPermissionInteraction,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
		arg.InteractionID,
	)
	var i CompleteToolCallFromPermissionInteractionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const completeToolCallFromProcess = `-- name: CompleteToolCallFromProcess :one
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $4
    AND agent.id = $5
  FOR UPDATE
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM processes tp
CROSS JOIN locked_agent agent
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = agent.id
  AND call.id = $1
  AND call.state = 'waiting'
  AND call.type = 'built_in'
  AND tp.project_id = agent.project_id
  AND tp.agent_id = call.agent_id
  AND tp.id = $2
  AND tp.tool_call_id = call.id
  AND tp.state IN ('exited', 'failed', 'killed', 'unknown')
  AND projection.project_id = agent.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $3::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteToolCallFromProcessParams struct {
	ID        uuid.UUID
	ProcessID uuid.UUID
	Outcome   string
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type CompleteToolCallFromProcessRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteToolCallFromProcess(ctx context.Context, arg CompleteToolCallFromProcessParams) (CompleteToolCallFromProcessRow, error) {
	row := q.db.QueryRow(ctx, completeToolCallFromProcess,
		arg.ID,
		arg.ProcessID,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
	)
	var i CompleteToolCallFromProcessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const completeToolCallFromProcessAction = `-- name: CompleteToolCallFromProcessAction :one
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $5
    AND agent.id = $6
  FOR UPDATE
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM process_actions action
CROSS JOIN locked_agent agent
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = agent.id
  AND call.id = action.tool_call_id
  AND call.id = $1
  AND call.state = 'waiting'
  AND call.type = 'built_in'
  AND action.project_id = agent.project_id
  AND action.agent_id = call.agent_id
  AND action.process_id = $2
  AND action.id = $3
  AND action.state IN ('applied', 'failed', 'unknown')
  AND projection.project_id = agent.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $4::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteToolCallFromProcessActionParams struct {
	ToolCallID      uuid.UUID
	ProcessID       uuid.UUID
	ProcessActionID uuid.UUID
	Outcome         string
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
}

type CompleteToolCallFromProcessActionRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteToolCallFromProcessAction(ctx context.Context, arg CompleteToolCallFromProcessActionParams) (CompleteToolCallFromProcessActionRow, error) {
	row := q.db.QueryRow(ctx, completeToolCallFromProcessAction,
		arg.ToolCallID,
		arg.ProcessID,
		arg.ProcessActionID,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
	)
	var i CompleteToolCallFromProcessActionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const completeToolCallFromQuestionInteraction = `-- name: CompleteToolCallFromQuestionInteraction :one
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $3
    AND agent.id = $4
  FOR UPDATE
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM locked_agent agent
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = agent.id
  AND call.state IN ('running', 'waiting')
  AND call.type = 'built_in'
  AND EXISTS (
    SELECT 1
    FROM agent_interactions question
    WHERE question.agent_id = call.agent_id
      AND question.tool_call_id = call.id
      AND question.id = $1
      AND question.interaction_kind = 'question'
      AND question.state IN ('resolved', 'canceled')
  )
  AND projection.project_id = agent.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $2::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteToolCallFromQuestionInteractionParams struct {
	InteractionID uuid.UUID
	Outcome       string
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
}

type CompleteToolCallFromQuestionInteractionRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteToolCallFromQuestionInteraction(ctx context.Context, arg CompleteToolCallFromQuestionInteractionParams) (CompleteToolCallFromQuestionInteractionRow, error) {
	row := q.db.QueryRow(ctx, completeToolCallFromQuestionInteraction,
		arg.InteractionID,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
	)
	var i CompleteToolCallFromQuestionInteractionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const completeToolCallFromStartedProcess = `-- name: CompleteToolCallFromStartedProcess :one
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $4
    AND agent.id = $5
  FOR UPDATE
)
UPDATE tool_calls call
SET state = 'completed',
    runtime_lock_id = NULL
FROM processes process
CROSS JOIN locked_agent agent
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = agent.id
  AND call.id = $1
  AND call.state = 'waiting'
  AND call.type = 'built_in'
  AND process.project_id = agent.project_id
  AND process.agent_id = call.agent_id
  AND process.id = $2
  AND process.tool_call_id = call.id
  AND process.state = 'running'
  AND projection.project_id = agent.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  $3::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at
`

type CompleteToolCallFromStartedProcessParams struct {
	ID        uuid.UUID
	ProcessID uuid.UUID
	Outcome   string
	ProjectID uuid.UUID
	AgentID   uuid.UUID
}

type CompleteToolCallFromStartedProcessRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) CompleteToolCallFromStartedProcess(ctx context.Context, arg CompleteToolCallFromStartedProcessParams) (CompleteToolCallFromStartedProcessRow, error) {
	row := q.db.QueryRow(ctx, completeToolCallFromStartedProcess,
		arg.ID,
		arg.ProcessID,
		arg.Outcome,
		arg.ProjectID,
		arg.AgentID,
	)
	var i CompleteToolCallFromStartedProcessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
	)
	return i, err
}

const getToolCall = `-- name: GetToolCall :one
SELECT tc.id, tc.project_id, tc.agent_id, tc.turn_id,
  tc.source_event_id, tc.model_call_context_id, tc.provider_call_id,
  tc.name, tc.input, tc.type,
  tc.state, coalesce(result.outcome, '') AS outcome,
  tc.runtime_lock_id,
  coalesce(result_blocks.content_parts, '[]'::jsonb)::jsonb AS result_content_parts,
  tc.created_at,
  result.completed_at
FROM tool_call_read_projection tc
LEFT JOIN tool_call_results result ON result.agent_id = tc.agent_id
  AND result.tool_call_id = tc.id
LEFT JOIN LATERAL (
  SELECT coalesce(jsonb_agg(
    CASE
      WHEN block.block_kind = 'text' THEN jsonb_build_object('type', 'text', 'text', block.text_content)
      WHEN block.block_kind = 'structured_data' THEN jsonb_build_object('type', 'structured_data', 'value', block.structured_data)
      WHEN block.block_kind = 'artifact' THEN
        jsonb_build_object('type', 'media_ref', 'artifact_id', block.artifact_id::text) ||
        CASE
          WHEN block.exclude_from_model_context THEN jsonb_build_object('exclude_from_model_context', true)
          ELSE '{}'::jsonb
        END
    END
    ORDER BY block.ordinal, block.id
  ) FILTER (WHERE block.id IS NOT NULL AND block.block_kind IN ('text', 'structured_data', 'artifact')), '[]'::jsonb) AS content_parts
  FROM content_blocks block
  WHERE block.agent_id = result.agent_id
    AND block.owner_tool_call_result_id = result.id
) result_blocks ON true
WHERE tc.project_id = $1 AND tc.agent_id = $2 AND tc.id = $3
`

type GetToolCallParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
}

type GetToolCallRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
	CompletedAt        *time.Time
}

func (q *Queries) GetToolCall(ctx context.Context, arg GetToolCallParams) (GetToolCallRow, error) {
	row := q.db.QueryRow(ctx, getToolCall, arg.ProjectID, arg.AgentID, arg.ID)
	var i GetToolCallRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getToolCallByProviderCall = `-- name: GetToolCallByProviderCall :one
SELECT tc.id, tc.project_id, tc.agent_id, tc.turn_id,
  tc.source_event_id, tc.model_call_context_id, tc.provider_call_id,
  tc.name, tc.input, tc.type,
  tc.state, coalesce(result.outcome, '') AS outcome,
  tc.runtime_lock_id,
  coalesce(result_blocks.content_parts, '[]'::jsonb)::jsonb AS result_content_parts,
  tc.created_at,
  result.completed_at
FROM tool_call_read_projection tc
LEFT JOIN tool_call_results result ON result.agent_id = tc.agent_id
  AND result.tool_call_id = tc.id
LEFT JOIN LATERAL (
  SELECT coalesce(jsonb_agg(
    CASE
      WHEN block.block_kind = 'text' THEN jsonb_build_object('type', 'text', 'text', block.text_content)
      WHEN block.block_kind = 'structured_data' THEN jsonb_build_object('type', 'structured_data', 'value', block.structured_data)
      WHEN block.block_kind = 'artifact' THEN
        jsonb_build_object('type', 'media_ref', 'artifact_id', block.artifact_id::text) ||
        CASE
          WHEN block.exclude_from_model_context THEN jsonb_build_object('exclude_from_model_context', true)
          ELSE '{}'::jsonb
        END
    END
    ORDER BY block.ordinal, block.id
  ) FILTER (WHERE block.id IS NOT NULL AND block.block_kind IN ('text', 'structured_data', 'artifact')), '[]'::jsonb) AS content_parts
  FROM content_blocks block
  WHERE block.agent_id = result.agent_id
    AND block.owner_tool_call_result_id = result.id
) result_blocks ON true
WHERE tc.project_id = $1 AND tc.agent_id = $2 AND tc.model_call_context_id = $3 AND tc.provider_call_id = $4
`

type GetToolCallByProviderCallParams struct {
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
}

type GetToolCallByProviderCallRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
	CompletedAt        *time.Time
}

func (q *Queries) GetToolCallByProviderCall(ctx context.Context, arg GetToolCallByProviderCallParams) (GetToolCallByProviderCallRow, error) {
	row := q.db.QueryRow(ctx, getToolCallByProviderCall,
		arg.ProjectID,
		arg.AgentID,
		arg.ModelCallContextID,
		arg.ProviderCallID,
	)
	var i GetToolCallByProviderCallRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getToolCallDispatchState = `-- name: GetToolCallDispatchState :one
SELECT state, runtime_lock_id
FROM tool_call_read_projection
WHERE project_id = $1
  AND agent_id = $2
  AND id = $3
`

type GetToolCallDispatchStateParams struct {
	ProjectID uuid.UUID
	AgentID   uuid.UUID
	ID        uuid.UUID
}

type GetToolCallDispatchStateRow struct {
	State         string
	RuntimeLockID *uuid.UUID
}

func (q *Queries) GetToolCallDispatchState(ctx context.Context, arg GetToolCallDispatchStateParams) (GetToolCallDispatchStateRow, error) {
	row := q.db.QueryRow(ctx, getToolCallDispatchState, arg.ProjectID, arg.AgentID, arg.ID)
	var i GetToolCallDispatchStateRow
	err := row.Scan(&i.State, &i.RuntimeLockID)
	return i, err
}

const insertToolCall = `-- name: InsertToolCall :one
WITH live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $1
    AND runtime_lock.agent_id = $2
    AND runtime_lock.id = $3
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
),
source_event AS MATERIALIZED (
  SELECT event.id, event.turn_id, event.model_output_id, model_output.created_at
  FROM agent_events event
  JOIN agents agent ON agent.id = event.agent_id
  JOIN model_outputs model_output ON model_output.agent_id = event.agent_id
    AND model_output.id = event.model_output_id
  WHERE agent.project_id = $1
    AND event.agent_id = $2
    AND event.id = $4
    AND event.event_kind = 'model_output'
    AND event.model_output_id IS NOT NULL
    AND model_output.model_call_context_id = $5
),
candidate AS MATERIALIZED (
  SELECT coalesce($6::uuid, uuidv7()) AS id,
         mcc.project_id,
         mcc.agent_id,
         mcc.id AS model_call_context_id,
         source_event.id AS source_event_id,
         source_event.turn_id,
         source_event.model_output_id,
         $7::text AS provider_call_id,
         $8::text AS name,
         $9::jsonb AS input,
         $10::text AS type,
         source_event.created_at
  FROM model_call_contexts mcc
  JOIN live_runtime runtime_lock ON runtime_lock.project_id = mcc.project_id
    AND runtime_lock.agent_id = mcc.agent_id
    AND runtime_lock.id = mcc.runtime_lock_id
  JOIN source_event ON true
  WHERE mcc.project_id = $1
    AND mcc.agent_id = $2
    AND mcc.id = $5
    AND mcc.runtime_lock_id = $3
),
inserted_call AS (
  INSERT INTO tool_calls(
    id, agent_id, model_output_id,
    provider_call_id, name, input,
    type, state, created_at
  )
  SELECT id, agent_id, model_output_id,
         provider_call_id, name, input,
         type, 'awaiting_authorization', created_at
  FROM candidate
  RETURNING id, agent_id,
            model_output_id, provider_call_id, name,
            input, type, state,
            runtime_lock_id, created_at
)
SELECT call.id, candidate.project_id, call.agent_id,
  candidate.turn_id, candidate.source_event_id,
  candidate.model_call_context_id, call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  ''::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at, NULL::timestamptz AS completed_at
FROM inserted_call call
JOIN candidate ON candidate.id = call.id
`

type InsertToolCallParams struct {
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	RuntimeLockID      uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ToolCallID         *uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
}

type InsertToolCallRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
	CompletedAt        *time.Time
}

func (q *Queries) InsertToolCall(ctx context.Context, arg InsertToolCallParams) (InsertToolCallRow, error) {
	row := q.db.QueryRow(ctx, insertToolCall,
		arg.ProjectID,
		arg.AgentID,
		arg.RuntimeLockID,
		arg.SourceEventID,
		arg.ModelCallContextID,
		arg.ToolCallID,
		arg.ProviderCallID,
		arg.Name,
		arg.Input,
		arg.Type,
	)
	var i InsertToolCallRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCompletedToolCallsAtWatermark = `-- name: ListCompletedToolCallsAtWatermark :many
SELECT tc.id, tc.project_id, tc.agent_id, tc.turn_id,
  tc.source_event_id, tc.source_event_sequence,
  tc.model_call_context_id, result.id AS tool_call_result_id,
  tool_result_event.id AS tool_result_event_id,
  tool_result_event.sequence AS tool_result_event_sequence,
  tc.provider_call_id, tc.name, tc.input, tc.type, tc.state, result.outcome,
  tc.runtime_lock_id,
  coalesce(result_blocks.content_parts, '[]'::jsonb)::jsonb AS result_content_parts,
  tc.created_at, result.completed_at
FROM tool_call_read_projection tc
JOIN content_blocks call_block
  ON call_block.agent_id = tc.agent_id
 AND call_block.tool_call_id = tc.id
 AND call_block.block_kind = 'tool_call'
JOIN tool_call_results result
  ON result.agent_id = tc.agent_id
 AND result.tool_call_id = tc.id
JOIN agent_events tool_result_event
  ON tool_result_event.agent_id = result.agent_id
 AND tool_result_event.tool_call_result_id = result.id
 AND tool_result_event.event_kind = 'tool_result'
LEFT JOIN LATERAL (
  SELECT coalesce(jsonb_agg(
    CASE
      WHEN block.block_kind = 'text' THEN jsonb_build_object('type', 'text', 'text', block.text_content)
      WHEN block.block_kind = 'structured_data' THEN jsonb_build_object('type', 'structured_data', 'value', block.structured_data)
      WHEN block.block_kind = 'artifact' THEN
        jsonb_build_object('type', 'media_ref', 'artifact_id', block.artifact_id::text)
    END
    ORDER BY block.ordinal, block.id
  ) FILTER (
    WHERE block.id IS NOT NULL
      AND block.block_kind IN ('text', 'structured_data', 'artifact')
      AND NOT block.exclude_from_model_context
  ), '[]'::jsonb) AS content_parts
  FROM content_blocks block
  WHERE block.agent_id = result.agent_id
    AND block.owner_tool_call_result_id = result.id
) result_blocks ON true
WHERE tc.project_id = $1
  AND tc.agent_id = $2
  AND tc.state = 'completed'
  AND tc.source_event_sequence > $3
  AND tool_result_event.sequence > $3
  AND tc.source_event_sequence <= $4
  AND tool_result_event.sequence <= $4
ORDER BY tc.source_event_sequence, call_block.ordinal, tc.created_at, tc.id
`

type ListCompletedToolCallsAtWatermarkParams struct {
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	AfterEventSequence int64
	MaxEventSequence   int64
}

type ListCompletedToolCallsAtWatermarkRow struct {
	ID                      uuid.UUID
	ProjectID               uuid.UUID
	AgentID                 uuid.UUID
	TurnID                  uuid.UUID
	SourceEventID           uuid.UUID
	SourceEventSequence     int64
	ModelCallContextID      uuid.UUID
	ToolCallResultID        uuid.UUID
	ToolResultEventID       uuid.UUID
	ToolResultEventSequence int64
	ProviderCallID          string
	Name                    string
	Input                   json.RawMessage
	Type                    string
	State                   string
	Outcome                 string
	RuntimeLockID           *uuid.UUID
	ResultContentParts      json.RawMessage
	CreatedAt               time.Time
	CompletedAt             time.Time
}

func (q *Queries) ListCompletedToolCallsAtWatermark(ctx context.Context, arg ListCompletedToolCallsAtWatermarkParams) ([]ListCompletedToolCallsAtWatermarkRow, error) {
	rows, err := q.db.Query(ctx, listCompletedToolCallsAtWatermark,
		arg.ProjectID,
		arg.AgentID,
		arg.AfterEventSequence,
		arg.MaxEventSequence,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletedToolCallsAtWatermarkRow{}
	for rows.Next() {
		var i ListCompletedToolCallsAtWatermarkRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.TurnID,
			&i.SourceEventID,
			&i.SourceEventSequence,
			&i.ModelCallContextID,
			&i.ToolCallResultID,
			&i.ToolResultEventID,
			&i.ToolResultEventSequence,
			&i.ProviderCallID,
			&i.Name,
			&i.Input,
			&i.Type,
			&i.State,
			&i.Outcome,
			&i.RuntimeLockID,
			&i.ResultContentParts,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsForAgent = `-- name: ListToolCallsForAgent :many
SELECT call.id, call.project_id, call.agent_id,
  call.turn_id, call.source_event_id,
  call.model_call_context_id, call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  coalesce(result.outcome, '') AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at, result.completed_at
FROM tool_call_read_projection call
LEFT JOIN tool_call_results result ON result.agent_id = call.agent_id
  AND result.tool_call_id = call.id
WHERE call.project_id = $1
  AND call.agent_id = $2
  AND ($3::text = '' OR call.state = $3)
  AND ($4::text = '' OR call.type = $4)
  AND (
    $5::timestamptz IS NULL
    OR (call.created_at, call.id) > (
      $5::timestamptz,
      $6::uuid
    )
  )
ORDER BY call.created_at ASC, call.id ASC
LIMIT $7::bigint
`

type ListToolCallsForAgentParams struct {
	ProjectID       uuid.UUID
	AgentID         uuid.UUID
	State           string
	Type            string
	CursorCreatedAt *time.Time
	CursorID        *uuid.UUID
	RowLimit        int64
}

type ListToolCallsForAgentRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
	CompletedAt        *time.Time
}

func (q *Queries) ListToolCallsForAgent(ctx context.Context, arg ListToolCallsForAgentParams) ([]ListToolCallsForAgentRow, error) {
	rows, err := q.db.Query(ctx, listToolCallsForAgent,
		arg.ProjectID,
		arg.AgentID,
		arg.State,
		arg.Type,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolCallsForAgentRow{}
	for rows.Next() {
		var i ListToolCallsForAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.TurnID,
			&i.SourceEventID,
			&i.ModelCallContextID,
			&i.ProviderCallID,
			&i.Name,
			&i.Input,
			&i.Type,
			&i.State,
			&i.Outcome,
			&i.RuntimeLockID,
			&i.ResultContentParts,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsForModelContext = `-- name: ListToolCallsForModelContext :many
SELECT tc.id, tc.project_id, tc.agent_id,
  tc.turn_id, tc.source_event_id, tc.model_call_context_id,
  tc.provider_call_id, tc.name, tc.input, tc.type, tc.state,
  coalesce(result.outcome, '') AS outcome, tc.runtime_lock_id,
  coalesce(result_blocks.content_parts, '[]'::jsonb)::jsonb AS result_content_parts,
  tc.created_at, result.completed_at
FROM tool_call_read_projection tc
LEFT JOIN tool_call_results result
  ON result.agent_id = tc.agent_id
 AND result.tool_call_id = tc.id
LEFT JOIN LATERAL (
  SELECT coalesce(jsonb_agg(
    CASE
      WHEN block.block_kind = 'text' THEN jsonb_build_object('type', 'text', 'text', block.text_content)
      WHEN block.block_kind = 'structured_data' THEN jsonb_build_object('type', 'structured_data', 'value', block.structured_data)
      WHEN block.block_kind = 'artifact' THEN
        jsonb_build_object('type', 'media_ref', 'artifact_id', block.artifact_id::text)
    END
    ORDER BY block.ordinal, block.id
  ) FILTER (
    WHERE block.id IS NOT NULL
      AND block.block_kind IN ('text', 'structured_data', 'artifact')
  ), '[]'::jsonb) AS content_parts
  FROM content_blocks block
  WHERE block.agent_id = result.agent_id
    AND block.owner_tool_call_result_id = result.id
) result_blocks ON true
WHERE tc.project_id = $1
  AND tc.agent_id = $2
  AND tc.model_call_context_id = $3
ORDER BY tc.created_at, tc.id
`

type ListToolCallsForModelContextParams struct {
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	ModelCallContextID uuid.UUID
}

type ListToolCallsForModelContextRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
	CompletedAt        *time.Time
}

func (q *Queries) ListToolCallsForModelContext(ctx context.Context, arg ListToolCallsForModelContextParams) ([]ListToolCallsForModelContextRow, error) {
	rows, err := q.db.Query(ctx, listToolCallsForModelContext, arg.ProjectID, arg.AgentID, arg.ModelCallContextID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListToolCallsForModelContextRow{}
	for rows.Next() {
		var i ListToolCallsForModelContextRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.TurnID,
			&i.SourceEventID,
			&i.ModelCallContextID,
			&i.ProviderCallID,
			&i.Name,
			&i.Input,
			&i.Type,
			&i.State,
			&i.Outcome,
			&i.RuntimeLockID,
			&i.ResultContentParts,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markToolCallAwaitingPermission = `-- name: MarkToolCallAwaitingPermission :one
WITH live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $3
    AND runtime_lock.agent_id = $4
    AND runtime_lock.id = $2
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
)
UPDATE tool_calls call
SET state = 'awaiting_permission'
FROM live_runtime runtime_lock
WHERE call.agent_id = runtime_lock.agent_id
  AND call.id = $1
  AND call.state = 'awaiting_authorization'
  AND runtime_lock.id = $2
RETURNING call.id
`

type MarkToolCallAwaitingPermissionParams struct {
	ID            uuid.UUID
	RuntimeLockID uuid.UUID
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
}

func (q *Queries) MarkToolCallAwaitingPermission(ctx context.Context, arg MarkToolCallAwaitingPermissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markToolCallAwaitingPermission,
		arg.ID,
		arg.RuntimeLockID,
		arg.ProjectID,
		arg.AgentID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markToolCallReady = `-- name: MarkToolCallReady :one
WITH live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $3
    AND runtime_lock.agent_id = $4
    AND runtime_lock.id = $2
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
)
UPDATE tool_calls call
SET state = 'ready'
FROM live_runtime runtime_lock
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = runtime_lock.agent_id
  AND call.id = $1
  AND call.state = 'awaiting_authorization'
  AND runtime_lock.id = $2
  AND projection.project_id = runtime_lock.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  ''::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at, NULL::timestamptz AS completed_at
`

type MarkToolCallReadyParams struct {
	ID            uuid.UUID
	RuntimeLockID uuid.UUID
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
}

type MarkToolCallReadyRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
	CompletedAt        *time.Time
}

func (q *Queries) MarkToolCallReady(ctx context.Context, arg MarkToolCallReadyParams) (MarkToolCallReadyRow, error) {
	row := q.db.QueryRow(ctx, markToolCallReady,
		arg.ID,
		arg.RuntimeLockID,
		arg.ProjectID,
		arg.AgentID,
	)
	var i MarkToolCallReadyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markToolCallReadyFromInteraction = `-- name: MarkToolCallReadyFromInteraction :one
WITH locked_agent AS MATERIALIZED (
  SELECT agent.project_id, agent.id
  FROM agents agent
  WHERE agent.project_id = $1
    AND agent.id = $2
  FOR UPDATE
),
permission_interaction AS MATERIALIZED (
  SELECT agent.project_id, interaction.agent_id, interaction.tool_call_id
  FROM agent_interactions interaction
  JOIN locked_agent agent ON agent.id = interaction.agent_id
  WHERE interaction.agent_id = $2
    AND interaction.id = $3
    AND interaction.interaction_kind = 'permission'
    AND interaction.state = 'resolved'
)
UPDATE tool_calls call
SET state = 'ready'
FROM permission_interaction interaction
CROSS JOIN tool_call_read_projection projection
WHERE call.agent_id = interaction.agent_id
  AND call.id = interaction.tool_call_id
  AND call.state = 'awaiting_permission'
  AND projection.project_id = interaction.project_id
  AND projection.agent_id = call.agent_id
  AND projection.id = call.id
RETURNING call.id, projection.project_id, call.agent_id,
  projection.turn_id, projection.source_event_id, projection.model_call_context_id,
  call.provider_call_id,
  call.name, call.input,
  call.type, call.state,
  ''::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at, NULL::timestamptz AS completed_at
`

type MarkToolCallReadyFromInteractionParams struct {
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	InteractionID uuid.UUID
}

type MarkToolCallReadyFromInteractionRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
	CompletedAt        *time.Time
}

func (q *Queries) MarkToolCallReadyFromInteraction(ctx context.Context, arg MarkToolCallReadyFromInteractionParams) (MarkToolCallReadyFromInteractionRow, error) {
	row := q.db.QueryRow(ctx, markToolCallReadyFromInteraction, arg.ProjectID, arg.AgentID, arg.InteractionID)
	var i MarkToolCallReadyFromInteractionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const nextRunnableToolCallForModelOutput = `-- name: NextRunnableToolCallForModelOutput :one
SELECT call.id, call.project_id, call.agent_id,
  call.turn_id, call.source_event_id,
  call.model_call_context_id,
  call.provider_call_id, call.name, call.input,
  call.type, call.state,
  ''::text AS outcome, call.runtime_lock_id,
  '[]'::jsonb AS result_content_parts,
  call.created_at, NULL::timestamptz AS completed_at
FROM tool_call_read_projection call
LEFT JOIN content_blocks call_block ON call_block.agent_id = call.agent_id
  AND call_block.tool_call_id = call.id
  AND call_block.block_kind = 'tool_call'
WHERE call.project_id = $1
  AND call.agent_id = $2
  AND call.model_output_id = $3
  AND (
    COALESCE(cardinality($4::uuid[]), 0) = 0
    OR NOT (call.id = ANY($4::uuid[]))
  )
  AND (
    call.state = 'awaiting_authorization'
    OR (call.state = 'ready' AND call.type IN ('built_in', 'mcp'))
  )
ORDER BY coalesce(call_block.ordinal, 2147483647), call.created_at, call.id
LIMIT 1
`

type NextRunnableToolCallForModelOutputParams struct {
	ProjectID           uuid.UUID
	AgentID             uuid.UUID
	ModelOutputID       uuid.UUID
	ExcludedToolCallIds []uuid.UUID
}

type NextRunnableToolCallForModelOutputRow struct {
	ID                 uuid.UUID
	ProjectID          uuid.UUID
	AgentID            uuid.UUID
	TurnID             uuid.UUID
	SourceEventID      uuid.UUID
	ModelCallContextID uuid.UUID
	ProviderCallID     string
	Name               string
	Input              json.RawMessage
	Type               string
	State              string
	Outcome            string
	RuntimeLockID      *uuid.UUID
	ResultContentParts json.RawMessage
	CreatedAt          time.Time
	CompletedAt        *time.Time
}

func (q *Queries) NextRunnableToolCallForModelOutput(ctx context.Context, arg NextRunnableToolCallForModelOutputParams) (NextRunnableToolCallForModelOutputRow, error) {
	row := q.db.QueryRow(ctx, nextRunnableToolCallForModelOutput,
		arg.ProjectID,
		arg.AgentID,
		arg.ModelOutputID,
		arg.ExcludedToolCallIds,
	)
	var i NextRunnableToolCallForModelOutputRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TurnID,
		&i.SourceEventID,
		&i.ModelCallContextID,
		&i.ProviderCallID,
		&i.Name,
		&i.Input,
		&i.Type,
		&i.State,
		&i.Outcome,
		&i.RuntimeLockID,
		&i.ResultContentParts,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const releaseToolCallRuntimeOwnership = `-- name: ReleaseToolCallRuntimeOwnership :execrows
WITH live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $2
    AND runtime_lock.agent_id = $3
    AND runtime_lock.id = $4
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
)
UPDATE tool_calls call
SET state = 'waiting',
    runtime_lock_id = NULL
FROM live_runtime runtime_lock
WHERE call.agent_id = runtime_lock.agent_id
  AND call.id = $1
  AND call.state = 'running'
  AND call.runtime_lock_id = runtime_lock.id
  AND EXISTS (
    SELECT 1
    FROM agent_interactions interaction
    WHERE interaction.agent_id = call.agent_id
      AND interaction.tool_call_id = call.id
      AND interaction.interaction_kind = 'question'
      AND interaction.state = 'open'
  )
`

type ReleaseToolCallRuntimeOwnershipParams struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	RuntimeLockID uuid.UUID
}

func (q *Queries) ReleaseToolCallRuntimeOwnership(ctx context.Context, arg ReleaseToolCallRuntimeOwnershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseToolCallRuntimeOwnership,
		arg.ID,
		arg.ProjectID,
		arg.AgentID,
		arg.RuntimeLockID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueRuntimeToolCall = `-- name: RequeueRuntimeToolCall :execrows
WITH live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $2
    AND runtime_lock.agent_id = $3
    AND runtime_lock.id = $4
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
)
UPDATE tool_calls call
SET state = 'ready',
    runtime_lock_id = NULL
FROM live_runtime runtime_lock
WHERE call.agent_id = runtime_lock.agent_id
  AND call.id = $1
  AND call.state = 'running'
  AND call.runtime_lock_id = runtime_lock.id
`

type RequeueRuntimeToolCallParams struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	AgentID       uuid.UUID
	RuntimeLockID uuid.UUID
}

func (q *Queries) RequeueRuntimeToolCall(ctx context.Context, arg RequeueRuntimeToolCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueRuntimeToolCall,
		arg.ID,
		arg.ProjectID,
		arg.AgentID,
		arg.RuntimeLockID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startToolCall = `-- name: StartToolCall :execrows
WITH live_runtime AS MATERIALIZED (
  SELECT agent.project_id, runtime_lock.agent_id, runtime_lock.id
  FROM agent_runtime_locks runtime_lock
  JOIN agents agent ON agent.id = runtime_lock.agent_id
  WHERE agent.project_id = $5
    AND runtime_lock.agent_id = $2
    AND runtime_lock.id = $4
    AND runtime_lock.cancel_requested_at IS NULL
    AND runtime_lock.lease_expires_at > statement_timestamp()
)
UPDATE tool_calls call
SET state = CASE
      WHEN $1::boolean THEN 'running'
      ELSE 'waiting'
    END,
    runtime_lock_id = CASE
      WHEN $1::boolean THEN runtime_lock.id
      ELSE NULL
    END
FROM live_runtime runtime_lock
WHERE call.agent_id = $2
  AND call.id = $3
  AND call.state = 'ready'
  AND call.runtime_lock_id IS NULL
  AND call.type IN ('built_in', 'mcp')
  AND (
    $1::boolean
    OR call.type = 'built_in'
  )
  AND runtime_lock.agent_id = call.agent_id
  AND runtime_lock.id = $4
`

type StartToolCallParams struct {
	RetainRuntimeOwnership bool
	AgentID                uuid.UUID
	ID                     uuid.UUID
	RuntimeLockID          uuid.UUID
	ProjectID              uuid.UUID
}

func (q *Queries) StartToolCall(ctx context.Context, arg StartToolCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, startToolCall,
		arg.RetainRuntimeOwnership,
		arg.AgentID,
		arg.ID,
		arg.RuntimeLockID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
