package executionstore

import (
	"github.com/omnara-ai/omnara/internal/storage/internal/dbsqlc"
)

func machineRecordFromInsertSQLC(row dbsqlc.InsertMachineRow) MachineRecord {
	return machineRecordFromSQLC(
		row.ID,
		row.OrgID,
		row.MachinePoolID,
		row.SourceKind,
		row.DisplayName,
		row.Description,
		row.Provider,
		row.LifecycleState,
		row.ProviderResourceID,
		row.ProviderProvisionAttemptedAt,
		row.ConnectionState,
		row.LastObservedAt,
		row.Cpu,
		row.MemoryMb,
		row.Cwd,
		row.Env,
		row.SecretEnv,
		row.ProviderOptions,
		row.IdempotencyKey,
		row.LifecycleReasonCode,
		row.LifecycleReasonMessage,
		row.NextReconcileAfter,
		row.ProvisionAttempts,
		row.DeleteAttempts,
		row.Metadata,
		row.DeletedAt,
		row.CreatedAt,
		row.UpdatedAt,
		row.LifecycleChangedAt,
		row.LifecycleVersion,
	)
}

func machineRecordFromIdempotencySQLC(row dbsqlc.GetMachineByIdempotencyRow) MachineRecord {
	return machineRecordFromSQLC(
		row.ID,
		row.OrgID,
		row.MachinePoolID,
		row.SourceKind,
		row.DisplayName,
		row.Description,
		row.Provider,
		row.LifecycleState,
		row.ProviderResourceID,
		row.ProviderProvisionAttemptedAt,
		row.ConnectionState,
		row.LastObservedAt,
		row.Cpu,
		row.MemoryMb,
		row.Cwd,
		row.Env,
		row.SecretEnv,
		row.ProviderOptions,
		row.IdempotencyKey,
		row.LifecycleReasonCode,
		row.LifecycleReasonMessage,
		row.NextReconcileAfter,
		row.ProvisionAttempts,
		row.DeleteAttempts,
		row.Metadata,
		row.DeletedAt,
		row.CreatedAt,
		row.UpdatedAt,
		row.LifecycleChangedAt,
		row.LifecycleVersion,
	)
}

func machineRecordFromGetSQLC(row dbsqlc.GetMachineRow) MachineRecord {
	return machineRecordFromSQLC(
		row.ID,
		row.OrgID,
		row.MachinePoolID,
		row.SourceKind,
		row.DisplayName,
		row.Description,
		row.Provider,
		row.LifecycleState,
		row.ProviderResourceID,
		row.ProviderProvisionAttemptedAt,
		row.ConnectionState,
		row.LastObservedAt,
		row.Cpu,
		row.MemoryMb,
		row.Cwd,
		row.Env,
		row.SecretEnv,
		row.ProviderOptions,
		row.IdempotencyKey,
		row.LifecycleReasonCode,
		row.LifecycleReasonMessage,
		row.NextReconcileAfter,
		row.ProvisionAttempts,
		row.DeleteAttempts,
		row.Metadata,
		row.DeletedAt,
		row.CreatedAt,
		row.UpdatedAt,
		row.LifecycleChangedAt,
		row.LifecycleVersion,
	)
}

func machineSummaryFromVisibleSourceSQLC(row dbsqlc.ListVisibleMachineSourcesForPrincipalRow) MachineSummaryRecord {
	return machineSummaryRecordFromSQLC(
		row.ID,
		row.OrgID,
		row.SourceKind,
		row.DisplayName,
		row.Description,
		row.Provider,
		row.LifecycleState,
		row.ConnectionState,
		row.LastObservedAt,
		row.DeletedAt,
		row.CreatedAt,
		row.UpdatedAt,
	)
}

func machineSummaryFromProjectVisibleSQLC(row dbsqlc.ListProjectVisibleMachinesRow) MachineSummaryRecord {
	return machineSummaryRecordFromSQLC(
		row.ID,
		row.OrgID,
		row.SourceKind,
		row.DisplayName,
		row.Description,
		row.Provider,
		row.LifecycleState,
		row.ConnectionState,
		row.LastObservedAt,
		row.DeletedAt,
		row.CreatedAt,
		row.UpdatedAt,
	)
}

func machineRecordFromDeleteSQLC(row dbsqlc.DeleteMachineRow) MachineRecord {
	return machineRecordFromSQLC(
		row.ID,
		row.OrgID,
		row.MachinePoolID,
		row.SourceKind,
		row.DisplayName,
		row.Description,
		row.Provider,
		row.LifecycleState,
		row.ProviderResourceID,
		row.ProviderProvisionAttemptedAt,
		row.ConnectionState,
		row.LastObservedAt,
		row.Cpu,
		row.MemoryMb,
		row.Cwd,
		row.Env,
		row.SecretEnv,
		row.ProviderOptions,
		row.IdempotencyKey,
		row.LifecycleReasonCode,
		row.LifecycleReasonMessage,
		row.NextReconcileAfter,
		row.ProvisionAttempts,
		row.DeleteAttempts,
		row.Metadata,
		row.DeletedAt,
		row.CreatedAt,
		row.UpdatedAt,
		row.LifecycleChangedAt,
		row.LifecycleVersion,
	)
}

func machineRecordFromClaimPoolProvisioningSQLC(row dbsqlc.ClaimPoolMachineForProvisioningRow) MachineRecord {
	return machineRecordFromSQLC(
		row.ID,
		row.OrgID,
		row.MachinePoolID,
		row.SourceKind,
		row.DisplayName,
		row.Description,
		row.Provider,
		row.LifecycleState,
		row.ProviderResourceID,
		row.ProviderProvisionAttemptedAt,
		row.ConnectionState,
		row.LastObservedAt,
		row.Cpu,
		row.MemoryMb,
		row.Cwd,
		row.Env,
		row.SecretEnv,
		row.ProviderOptions,
		row.IdempotencyKey,
		row.LifecycleReasonCode,
		row.LifecycleReasonMessage,
		row.NextReconcileAfter,
		row.ProvisionAttempts,
		row.DeleteAttempts,
		row.Metadata,
		row.DeletedAt,
		row.CreatedAt,
		row.UpdatedAt,
		row.LifecycleChangedAt,
		row.LifecycleVersion,
	)
}

func machineRecordFromListPoolProvisioningSQLC(row dbsqlc.ListPoolMachinesForProvisioningRow) MachineRecord {
	return machineRecordFromSQLC(
		row.ID,
		row.OrgID,
		row.MachinePoolID,
		row.SourceKind,
		row.DisplayName,
		row.Description,
		row.Provider,
		row.LifecycleState,
		row.ProviderResourceID,
		row.ProviderProvisionAttemptedAt,
		row.ConnectionState,
		row.LastObservedAt,
		row.Cpu,
		row.MemoryMb,
		row.Cwd,
		row.Env,
		row.SecretEnv,
		row.ProviderOptions,
		row.IdempotencyKey,
		row.LifecycleReasonCode,
		row.LifecycleReasonMessage,
		row.NextReconcileAfter,
		row.ProvisionAttempts,
		row.DeleteAttempts,
		row.Metadata,
		row.DeletedAt,
		row.CreatedAt,
		row.UpdatedAt,
		row.LifecycleChangedAt,
		row.LifecycleVersion,
	)
}
